import { lessonQuiz, q } from "./helpers";

export const buyingCarQuiz = lessonQuiz(
  "lm-buying-car",
  "Buying a Car",
  "Life Skills",
  "Car buying, loans, and ownership costs",
  [
    q(
      1,
      "The 20/4/10 Rule",
      "Buying a car isn't just about the sticker price. To keep your finances safe, use the 20/4/10 rule: put down at least a 20% down payment, limit the loan to 4 years, and ensure total monthly car expenses don't exceed 10% of your gross income.",
      "If your gross monthly income is KSh 200,000, what is the maximum amount you should spend on your monthly car payment, insurance, and fuel combined according to the 20/4/10 rule?",
      ["KSh 40,000", "KSh 20,000", "KSh 10,000", "KSh 50,000"],
      1,
      "Correct! 10% of KSh 200,000 is KSh 20,000. Keeping your total costs under this cap ensures your car doesn't crowd out other vital financial goals.",
      'Not quite! Remember, the "10" in the 20/4/10 rule stands for 10% of your gross income. Try multiplying your income by 0.10.',
    ),
    q(
      2,
      "Depreciation",
      "A car is a depreciating asset, meaning it loses value over time. A brand-new car can lose up to 20% of its value in the first year alone. Buying used lets the previous owner take that initial financial hit.",
      'Which of the following best describes "depreciation" in the context of buying a vehicle?',
      [
        "The rate at which your auto loan interest grows",
        "The decline in the car's market value over time",
        "The cost of routine maintenance and repairs",
        "The tax discounts available for eco-friendly cars",
      ],
      1,
      "Spot on! Depreciation means your asset drops in value over time. It's why new cars lose money the second you drive them off the lot.",
      "Keep trying! Depreciation is all about how much the physical car is actually worth on the market as it gets older and gets driven more.",
    ),
    q(
      3,
      "Total Cost of Ownership",
      'Your monthly loan payment is only a fraction of the cost. Total Cost of Ownership (TCO) includes insurance, fuel, maintenance, registration, and parking. Skipping these in your math leads to being "car poor."',
      "Which of the following is considered a predictable, ongoing part of a car's Total Cost of Ownership (TCO)?",
      [
        "The initial dealership documentation fee",
        "Regular auto insurance premiums",
        "A one-time custom paint job",
        "Regular car service",
      ],
      1,
      "Great job! Insurance is a recurring, mandatory expense that directly impacts your monthly wallet alongside fuel and routine servicing.",
      "Look for an expense that is continuous and necessary to keep driving legally and safely every month.",
    ),
    q(
      4,
      "The True Cost of Fuel",
      "A cheap car with terrible fuel economy can cost more in the long run than a slightly pricier, fuel-efficient vehicle. Always calculate your estimated annual fuel cost based on your average weekly mileage before buying.",
      "If Car A costs less to buy but gets poor mileage, and Car B is KSh 150,000 more expensive but is highly fuel-efficient, what should you do to find the better deal?",
      [
        "Buy Car A because a lower initial price always wins",
        "Calculate the break-even point based on your yearly driving distance",
        "Choose Car B purely because it looks more modern",
        "Ignore fuel costs, as pump prices fluctuate too much to track",
      ],
      1,
      "Exactly! If you drive long distances daily, the fuel savings from Car B can quickly offset its higher upfront sticker price.",
      "Think about how your daily commute impacts your wallet over 3 to 5 years. A simple calculation helps clear this up!",
    ),
    q(
      5,
      "Needs vs. Wants",
      'Separate your needs like reliability, safety features, fuel efficiency from your wants such as premium sound systems, sunroofs, leather seats. Upgrading your "wants" can inflate a car loan by thousands.',
      'Which of the following features should be categorized strictly as a "need" for a daily commuter who travels over rough roads?',
      [
        "Heated steering wheel and seats",
        "High ground clearance and sturdy suspension",
        "Premium metallic exterior paint",
        "An upgraded panoramic glass roof",
      ],
      1,
      "Correct! Ground clearance dictates whether the car can safely handle your actual driving conditions without breaking down. The rest are luxury extras.",
      "Focus on utility. Which feature directly impacts the car's ability to safely complete its core task of getting you to work across bad roads?",
    ),
    q(
      6,
      "New vs. Certified Pre-Owned (CPO)",
      "Certified Pre-Owned vehicles are used cars that have been inspected, refurbished, and backed by a manufacturer warranty. They offer the peace of mind of a new car without the steep first-year depreciation.",
      "What is the primary benefit of buying a Certified Pre-Owned (CPO) car over a standard, non-certified used car from a private seller?",
      [
        "It is always cheaper than a private sale",
        "It comes with zero mileage on the odometer",
        "It includes a manufacturer-backed inspection and extended warranty",
        "It never requires future oil changes or maintenance",
      ],
      2,
      "Correct! CPO cars bridge the gap between new and used, giving you reduced risk through rigorous dealer inspections and extended warranties.",
      "Private sellers rarely offer guarantees. Look for the option that highlights institutional verification and protective coverage.",
    ),
    q(
      7,
      "Vehicle History Reports",
      "Never buy a used car blindly. Use the vehicle's chassis or registration number to pull a Vehicle History Report like local logbook verifications. This flags hidden accident damage, odometer fraud, or active salvage titles.",
      'You are looking at a sleek used Toyota, but the vehicle history report reveals a "salvage title." What does this mean?',
      [
        "The car was custom-built for racing",
        "The car has been declared a total loss by an insurance company due to severe damage",
        "The car was previously damaged by has since been repaired accordingly",
      ],
      1,
      "Correct! A salvage title warns you that the car suffered massive damage or flooding. It can be incredibly unsafe and difficult to insure or resell.",
      '"Salvage" implies recovery from destruction. Avoid vehicles with this status unless you are a professional mechanic looking for a major project.',
    ),
    q(
      8,
      "Checking Insurance Brackets",
      "Before buying a particular, call your insurance provider for a quote. Cars with high theft rates, powerful engines, or expensive spare parts sit in higher insurance brackets, drastically raising your monthly premium.",
      "Why might a modest sports car cost significantly more to insure than a mid-sized SUV of the exact same market value?",
      [
        "Sports cars always have larger boots",
        "Insurance companies view sports cars as higher risk for accidents and speeding",
        "SUVs are legally exempt from premium calculations",
        "Sports cars require diesel fuel",
      ],
      1,
      "Spot on! Actuarial data dictates insurance costs. High-performance vehicles correlate with riskier driving behaviors and costlier body work repairs.",
      "Insurance is all about risk management. Which type of vehicle does an insurance company statistically expect to be involved in high-speed incidents?",
    ),
    q(
      9,
      "Interest Rates and Annual Percentage Rate (APR)",
      "The Annual Percentage Rate (APR) reflects the true cost of borrowing money. It includes both the base interest rate and any extra lender fees. Even a 2% difference in APR can save or cost you tens of thousands over a 48-month loan.",
      "When shopping around for an auto loan, which factor gives you the most accurate picture of the total yearly borrowing cost?",
      [
        "The baseline principal amount",
        "The Annual Percentage Rate (APR)",
        "The dealership's monthly processing fee",
        "The vehicle's estimated resale value",
      ],
      1,
      "You got it! The APR bundles interest and fees together, giving you an apples-to-apples baseline to compare different bank offers.",
      "Base interest rates can sometimes hide extra administrative fees. Look for the all-inclusive percentage rate used across the financial industry.",
    ),
    q(
      10,
      "Loan Terms vs. Total Interest Paid",
      "Long loan terms (like 72 or 84 months) lower your monthly payment, but they trap you into paying vastly more in total interest. Aim for shorter terms to minimize debt costs and avoid paying more on your loan.",
      "What is the financial catch of choosing a 72-month car loan instead of a 48-month car loan for the exact same vehicle purchase price?",
      [
        "Your monthly payment will be much higher",
        "You will pay significantly more total interest over the life of the loan",
        "You are legally barred from selling the car before 72 months pass",
      ],
      1,
      "Bingo! Dragging out a loan keeps you in debt longer and compounds the interest charges, heavily inflating the ultimate price tag of the car.",
      "While a longer loan stretches out payments to make them smaller each month, think about what happens when you pay interest for an extra two whole years.",
    ),
    q(
      11,
      "The Power of a Down Payment",
      "A large down payment cuts down the amount of money you need to borrow. This instantly shrinks your monthly bill, lowers your interest charges, and prevents you from owing more than the car is worth as it depreciates.",
      "How does making a 20% down payment instead of a 0% down payment protect you from becoming paying more interest on your auto loan?",
      [
        "It lowers the car loan amount you need to sign up for in order to buy a car",
        "It builds immediate equity, ensuring your loan balance stays below the car's dropping market value",
        "It drops the monthly amount you are required to pay to service the car loan",
      ],
      1,
      'Brilliant! "Upside down" means owing more than the car\'s worth. A solid down payment acts as a financial cushion against rapid early depreciation.',
      "Remember that a car drops in value immediately. If you borrow 100% of the cost, your loan stays high while the car's value plummets.",
    ),
    q(
      12,
      "Getting a Pre-Approved Letter from the Bank",
      'When you walk into a car dealership with a bank or Sacco pre-approval letter in hand, it transforms you into a "cash buyer" in the eyes of the dealer, preventing them from marking up financing rates to make an extra profit off you.',
      "Why is it wise to secure a loan pre-approval from an independent bank before visiting a car dealership showroom?",
      [
        "To secure financing before going shopping for a car",
        "It gives you a benchmark interest rate leverage point to negotiate against dealer financing",
        "It enables you to compare loans terms with that of the dealership therefore enabling the favourable option",
      ],
      1,
      "Spot on! Pre-approval sets a hard ceiling on interest. If the dealer wants you to use their financing, they have to beat your bank's rate.",
      "Think of pre-approval as your shield. It gives you a firm, competitive alternative so the dealer can't overcharge you on interest.",
    ),
    q(
      13,
      "Out-the-Door Price",
      'Salespeople love to ask, "What monthly payment can you afford?" This allows them to stretch loan terms to hide a high sales price. Always negotiate the Out-the-Door (OTD) price, which represents the total cost including all fees and taxes.',
      'If a salesperson insists on focus negotiating strictly around your "monthly target payment," how should you redirect the conversation?',
      [
        "Agree and mention the highest possible number you can afford",
        "Insist on negotiating the total price of the vehicle first",
        "Walk away and purchase a vehicle from another dealership instead",
        "Ask for a discount on accessories like floor mats instead",
      ],
      1,
      "Perfect! The Out-the-Door price keeps hidden dealer add-ons out of the math and ensures you aren't tricked by long-term loan stretching.",
      "Monthly figures are easy to manipulate through creative loan lengths. Look for the term that locks down the total amount written on the final check.",
    ),
    q(
      14,
      "Spotting Unnecessary Dealer Fees",
      "Review your final invoice line-by-line. Standard fees like legitimate sales tax and registration are non-negotiable. However, inflated charges like VIN etching, fabric protection, and nitrogen-filled tires are high-profit dealer markups you can decline.",
      "Which of the following fees on a dealership invoice is typically a non-negotiable, legally mandated item?",
      [
        "KSh 15,000 for paint protection spray",
        "Government vehicle registration and title fees",
        "KSh 8,000 for premium interior detailing",
      ],
      1,
      "Correct! You must pay local registration and tax fees to legally own the vehicle. Everything else is open for pushback.",
      "Separate official government obligations from optional add-ons the dealer applied to the vehicle on their own lot.",
    ),
    q(
      15,
      "Trading in a Car",
      "If you already own a car and would like to trade it in for another one, keep your current car's trade-in value completely separate from the new car negotiation. If you mix them together early, dealers can muddy the numbers by making a discount on one side while underpaying you on the other.",
      "When is the best time to bring up that you have an old car you intend to trade in?",
      [
        "The very first second you walk onto the lot",
        "After you have locked down a firm, agreed-upon purchase price for the new car",
        "Right after signing the final financing contract documents",
        "During your initial phone call to schedule a test drive",
      ],
      1,
      "Awesome work! Locking down the purchase price first ensures you get a clean deal on the new purchase before evaluating your old vehicle's true worth.",
      "Mixing transactions allows dealers to play a shell game with numbers. Keep the two deals isolated until one is firmly set in writing.",
    ),
    q(
      16,
      "The Power to Walk Away",
      "Your absolute strongest negotiation tool is your feet. If a dealer uses high-pressure tactics, alters agreed terms in the back office, or refuses to remove junk fees, simply walk away. There are always other vehicles available.",
      "You spend three hours negotiating, but the manager suddenly adds an unexpected KSh 50,000 fee right before signing. What is your most powerful move?",
      [
        "Sign the deal anyway to avoid losing the time you invested",
        "Politely state that you are leaving, and walk out of the dealership",
        "Argue loudly with the finance manager in front of other clients",
        "Accept the fee but demand a complimentary key chain",
      ],
      1,
      "Spot on! Walking away completely shifts the leverage back to you. Dealers hate losing a sale that is 90% complete over an exposed junk fee.",
      "Don't fall for the sunk-cost fallacy. If the terms shift dishonestly at the final hour, you hold the ultimate veto power by leaving.",
    ),
    q(
      17,
      "The Pre-Purchase Inspection (PPI)",
      "For used vehicles, never take the seller's word that everything works. Spend a small fee to have an independent mechanic perform a Pre-Purchase Inspection. They will catch hidden oil leaks, frame damage, or worn brakes if there are any.",
      "Who should conduct a Pre-Purchase Inspection (PPI) before you finalize buying a used vehicle from an independent party?",
      [
        "The seller's personal mechanic friend",
        "An independent, certified mechanic of your own choosing",
        "The dealership salesperson handling the paperwork",
        "A trusted family member who enjoys watching car racing",
      ],
      1,
      "Correct! An independent professional owes allegiance only to you. Their unbiased report can save you from a massive financial mistake or serve as negotiation leverage.",
      "You need an objective, expert opinion with no stake in whether the car actually sells or not. Look for an independent provider.",
    ),
    q(
      18,
      "The Mastery Test Drive",
      "Don't just drive around the block with the radio playing. Test the car under real conditions: accelerate up hills, try highway merging speeds, slam the brakes in a safe area, and check for alignment pulling. Turn off the music to listen for rattles and knocks.",
      "What is a vital action to take during your test drive of a potential used car purchase?",
      [
        "Crank up the sound system to check the bass response immediately",
        "Keep the radio off entirely to listen for unusual engine or suspension noises",
        "Ensure you drive as fast as possible to push the car to its limits",
        "Stay strictly within the dealer's flat parking lot area",
      ],
      1,
      "Great choice! Silence is your best diagnostic tool. Clunks, squeaks, or whining sounds during turns tell you exactly what repairs are looming.",
      "Music can mask warning signs from the engine or transmission. Keep the interior quiet so you can evaluate the car's mechanical health accurately.",
    ),
    q(
      19,
      "Extended Warranties",
      "In the finance office, you will be pitched third-party extended warranties. Statistically, most buyers spend more on these premiums than they ever recover in repairs. Instead, self-insure by building an emergency car maintenance fund.",
      "What is often a more cost-effective alternative to purchasing an expensive, high-markup extended warranty on a highly reliable used car model?",
      [
        "Ignoring repairs entirely and driving until the vehicle breaks down",
        "Putting that same money into a dedicated personal savings account for emergency repairs",
        "Buying duplicate basic auto insurance policies to pay for any future repairs",
      ],
      1,
      "Perfect! Building an emergency maintenance fund keeps your money in your control. If the car doesn't break, you keep the cash!",
      "Extended warranties are structured to make a profit for the provider. Think of a way to protect yourself while keeping your money if repairs aren't needed.",
    ),
    q(
      20,
      "Logbook & Title Transfer",
      "The deal isn't done when you hand over the cash. Ensure the seller signs over the logbook/title correctly and file the transfer with the National Transport and Safety Authority (NTSA) ASAP. Unregistered transfers leave you liable for the previous owner's tickets or tow fees.",
      "Why is it critical to officially register a vehicle's title or logbook transfer immediately after buying a car from a private individual?",
      [
        "It helps the buyer sign up for the vehicle auto insurance right away",
        "It legally establishes your ownership and stops you from being liable for the previous owner's fines or actions",
        "It transfers all the responsibilities of the vehicle to the new owner as the logbook has been transferred accordingly",
      ],
      1,
      "Processing that official transfer protects you legally and cements your rights as the true owner of your new ride. Happy driving!",
      "Paperwork connects the car's legal responsibilities to an individual identity. Think about what happens if a speed camera flags the car before the system updates.",
    ),
  ],
);
