/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ChallengeIndexRouteImport } from './routes/challenge.index'
import { Route as ChallengeWeekRouteImport } from './routes/challenge.$week'
import { Route as JourneyGameIdRouteImport } from './routes/journey.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeIndexRoute = ChallengeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChallengeRoute,
} as any)
const ChallengeWeekRoute = ChallengeWeekRouteImport.update({
  id: '/$week',
  path: '/$week',
  getParentRoute: () => ChallengeRoute,
} as any)
const JourneyGameIdRoute = JourneyGameIdRouteImport.update({
  id: '/journey/$gameId',
  path: '/journey/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/challenge/$week': typeof ChallengeWeekRoute
  '/journey/$gameId': typeof JourneyGameIdRoute
  '/challenge/': typeof ChallengeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/challenge/$week': typeof ChallengeWeekRoute
  '/journey/$gameId': typeof JourneyGameIdRoute
  '/challenge': typeof ChallengeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/signup': typeof SignupRoute
  '/challenge/$week': typeof ChallengeWeekRoute
  '/journey/$gameId': typeof JourneyGameIdRoute
  '/challenge/': typeof ChallengeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenge'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/rewards'
    | '/signup'
    | '/challenge/$week'
    | '/journey/$gameId'
    | '/challenge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/rewards'
    | '/signup'
    | '/challenge/$week'
    | '/journey/$gameId'
    | '/challenge'
  id:
    | '__root__'
    | '/'
    | '/challenge'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/rewards'
    | '/signup'
    | '/challenge/$week'
    | '/journey/$gameId'
    | '/challenge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengeRoute: typeof ChallengeRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  SignupRoute: typeof SignupRoute
  JourneyGameIdRoute: typeof JourneyGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/': {
      id: '/challenge/'
      path: '/'
      fullPath: '/challenge/'
      preLoaderRoute: typeof ChallengeIndexRouteImport
      parentRoute: typeof ChallengeRoute
    }
    '/challenge/$week': {
      id: '/challenge/$week'
      path: '/$week'
      fullPath: '/challenge/$week'
      preLoaderRoute: typeof ChallengeWeekRouteImport
      parentRoute: typeof ChallengeRoute
    }
    '/journey/$gameId': {
      id: '/journey/$gameId'
      path: '/journey/$gameId'
      fullPath: '/journey/$gameId'
      preLoaderRoute: typeof JourneyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChallengeRouteChildren {
  ChallengeWeekRoute: typeof ChallengeWeekRoute
  ChallengeIndexRoute: typeof ChallengeIndexRoute
}

const ChallengeRouteChildren: ChallengeRouteChildren = {
  ChallengeWeekRoute: ChallengeWeekRoute,
  ChallengeIndexRoute: ChallengeIndexRoute,
}

const ChallengeRouteWithChildren = ChallengeRoute._addFileChildren(
  ChallengeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengeRoute: ChallengeRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  SignupRoute: SignupRoute,
  JourneyGameIdRoute: JourneyGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
