import { WordSearchPuzzle, CrosswordPuzzle, QuizPuzzle } from "../types";

export const mpesaWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-mpesa-ws1",
  title: "Characteristics of M-Pesa: Word Search",
  topic: "Money Basics",
  theme: "Mobile Money & Cashless Ecosystem",
  instruction: "Find the 10 core terms describing M-Pesa operations and safety.",
  size: 14,
  words: [
    "Cashless",
    "Consent",
    "Oversight",
    "Deposit",
    "Float",
    "Withdraw",
    "Reversal",
    "Literacy",
    "Agent",
    "Limit",
  ],
  grid: [
    ["L", "C", "W", "E", "T", "O", "C", "L", "Y", "C", "N", "S", "A", "L"],
    ["L", "L", "I", "T", "E", "R", "A", "C", "Y", "E", "O", "H", "T", "A"],
    ["I", "L", "A", "S", "R", "E", "V", "E", "R", "E", "R", "O", "I", "N"],
    ["S", "W", "I", "D", "S", "T", "I", "E", "T", "C", "V", "G", "M", "S"],
    ["T", "W", "I", "T", "H", "D", "R", "A", "W", "E", "S", "R", "I", "R"],
    ["C", "A", "S", "H", "L", "E", "S", "S", "R", "G", "S", "L", "L", "C"],
    ["M", "S", "E", "W", "V", "R", "L", "S", "T", "A", "O", "L", "F", "O"],
    ["D", "E", "T", "L", "L", "C", "I", "S", "L", "S", "M", "O", "A", "N"],
    ["L", "C", "O", "I", "I", "G", "R", "F", "I", "O", "L", "A", "O", "S"],
    ["T", "T", "A", "P", "H", "W", "A", "E", "H", "I", "S", "A", "L", "E"],
    ["A", "S", "T", "T", "S", "E", "A", "G", "A", "H", "A", "E", "O", "N"],
    ["O", "H", "T", "N", "W", "T", "L", "O", "E", "R", "A", "Y", "I", "T"],
    ["C", "A", "D", "E", "P", "O", "S", "I", "T", "N", "M", "E", "S", "F"],
    ["W", "R", "S", "W", "W", "H", "F", "C", "A", "O", "T", "H", "A", "E"],
  ],
};

export const mpesaQuiz: QuizPuzzle = {
  type: "quiz",
  id: "mb-mpesa-quiz1",
  title: "Characteristics of M-Pesa: Quiz",
  topic: "Money Basics",
  instruction: "Test your understanding of Kenya's premier mobile money platform.",
  questions: [
    {
      id: 1,
      question: "When you go to a shop to put physical cash into your M-PESA account, you are making a?",
      options: ["Limit", "Deposit", "Reversal", "Float"],
      correctIndex: 1,
      explanation: "A cash deposit is when you hand physical cash to an agent to credit your mobile wallet balance.",
    },
    {
      id: 2,
      question: "If you accidentally send money to the wrong person, you can quickly ask for a ___ to try and get it back.",
      options: ["Float", "Withdraw", "Reversal", "Consent"],
      correctIndex: 2,
      explanation: "Sending an SMS of the transaction message to 234 or 199 initiates an instant M-Pesa reversal request.",
    },
    {
      id: 3,
      question: "To keep the system safe, the Central Bank of Kenya provides ___ to make sure M-PESA follows the law.",
      options: ["Cashless", "Literacy", "Limit", "Oversight"],
      correctIndex: 3,
      explanation: "Regulatory oversight by CBK guarantees consumer protection, reserve backing, and financial compliance.",
    },
    {
      id: 4,
      question: "M-PESA helps Kenya become a ___ society because we can pay for things without using physical notes and coins.",
      options: ["Cashless", "Withdraw", "Literacy", "Float"],
      correctIndex: 0,
      explanation: "A cashless economy streamlines commerce, reduces robbery risk, and boosts financial inclusion.",
    },
    {
      id: 5,
      question: "Every person has a maximum amount of money they can hold or send in a single day using Mpesa. This is called a?",
      options: ["Consent", "Limit", "Deposit", "Agent"],
      correctIndex: 1,
      explanation: "Daily and per-transaction limits safeguard users against unauthorized transfers and fraud.",
    },
  ],
};

export const mpesaGoQuiz: QuizPuzzle = {
  type: "quiz",
  id: "mb-mpesa-go-quiz",
  title: "M-Pesa GO & Youth Security Quiz",
  topic: "Money Basics",
  instruction: "Explore junior accounts, biometric logins, and digital safety.",
  questions: [
    {
      id: 1,
      question: "On the Mpesa Go App, your parent/guardian is able to see your mini-statements to help you stay on track and avoid overspending. This characteristic is called?",
      options: ["Hiding", "Omoka", "Visibility", "Deleting"],
      correctIndex: 2,
      explanation: "Parental visibility allows guardians to guide tweens in building healthy spending habits.",
    },
    {
      id: 2,
      question: "To register for an account on the Mpesa Go App, what is the primary document your parent/guardian must upload to verify your age?",
      options: ["Passport Photo", "School ID", "Library Card", "Birth Certificate"],
      correctIndex: 3,
      explanation: "A valid birth certificate verifies the junior user's legal age and parental link under KYC laws.",
    },
    {
      id: 3,
      question: "If you want to log into the M-PESA Super App using your face or fingerprint instead of typing a pin, you are using?",
      options: ["Biometrics", "Analogue", "STK", "USSD"],
      correctIndex: 0,
      explanation: "Biometric authentication (fingerprint / FaceID) provides high security against screen-peeking.",
    },
    {
      id: 4,
      question: "Your daily or weekly 'Spending Cap' set by your parent/guardian on the Mpesa Go App is officially known as a?",
      options: ["Debt", "Limit", "Bonus", "Salary"],
      correctIndex: 1,
      explanation: "A spending limit ensures junior users do not deplete savings impulsively.",
    },
    {
      id: 5,
      question: "What happens to your M-PESA GO account when you finally turn 18?",
      options: [
        "You lose all your balance",
        "It stays exactly the same forever",
        "It automatically converts to a full adult account",
        "It is deleted permanently",
      ],
      correctIndex: 2,
      explanation: "Upon turning 18, junior accounts graduate seamlessly into full-featured adult M-PESA wallets.",
    },
  ],
};

export const mpesaCrossword1: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-mpesa-cw1",
  title: "Characteristics of M-Pesa: Puzzle 1",
  topic: "Money Basics",
  instruction: "Solve the crossword on M-Pesa parent consent, financial literacy, and KYC.",
  rows: 8,
  cols: 10,
  wordBank: ["Consent", "Literacy", "Cashless", "Oversight", "KYC"],
  acrossClues: [
    {
      number: 2,
      clue: "What your parent must give before you can perform tasks like spend over your limit on your Mpesa App.",
      answer: "CONSENT",
      row: 1,
      col: 0,
      direction: "across",
    },
    {
      number: 4,
      clue: "The type of knowledge M-PESA GO aims to improve for young Kenyans. Also known as 'financial knowledge'.",
      answer: "LITERACY",
      row: 4,
      col: 1,
      direction: "across",
    },
    {
      number: 5,
      clue: "A key benefit of M-PESA GO is providing users with an alternative way of payment without physical cash.",
      answer: "CASHLESS",
      row: 6,
      col: 0,
      direction: "across",
    },
  ],
  downClues: [
    {
      number: 1,
      clue: "When a parent or guardian monitors and guides their child's spending habits on the Mpesa app.",
      answer: "OVERSIGHT",
      row: 0,
      col: 4,
      direction: "down",
    },
    {
      number: 3,
      clue: "Short for 'Know Your Customer', the mandatory identity verification process.",
      answer: "KYC",
      row: 4,
      col: 0,
      direction: "down",
    },
  ],
};

export const mpesaCrossword2: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-mpesa-cw2",
  title: "Characteristics of M-Pesa: Puzzle 2",
  topic: "Money Basics",
  instruction: "Solve the crossword on reversals, agent float, limits, and STK.",
  rows: 8,
  cols: 10,
  wordBank: ["Reversal", "Float", "Limit", "STK", "Visibility", "Agent"],
  acrossClues: [
    {
      number: 2,
      clue: "The process of getting your money back after accidentally sending it to the wrong person.",
      answer: "REVERSAL",
      row: 1,
      col: 0,
      direction: "across",
    },
    {
      number: 3,
      clue: "The cash or money balance that an agent must maintain to facilitate transactions.",
      answer: "FLOAT",
      row: 4,
      col: 1,
      direction: "across",
    },
    {
      number: 5,
      clue: "A daily or weekly spending cap set by a guardian to help you manage your funds.",
      answer: "LIMIT",
      row: 6,
      col: 0,
      direction: "across",
    },
    {
      number: 6,
      clue: "The original way to access M-pesa via the SIM Tool Kit if you don't have data or the App.",
      answer: "STK",
      row: 7,
      col: 4,
      direction: "across",
    },
  ],
  downClues: [
    {
      number: 1,
      clue: "The feature that allows parents to see your mini-statements and spending habits.",
      answer: "VISIBILITY",
      row: 0,
      col: 5,
      direction: "down",
    },
    {
      number: 4,
      clue: "A person or business authorized to provide M-PESA services like deposits & withdrawals.",
      answer: "AGENT",
      row: 4,
      col: 6,
      direction: "down",
    },
  ],
};
