import { WordSearchPuzzle, QuizPuzzle, CryptogramPuzzle } from "../types";

export const currenciesKenyaWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currencies-ws1",
  title: "Currencies of Kenya: Puzzle 1",
  topic: "Money Basics",
  theme: "Traditional & Tribal Currency Names",
  instruction: "Find the 10 historical terms used across Kenya's communities for money.",
  size: 14,
  words: [
    "Ngaropiyae",
    "Chirupa",
    "Kilovia",
    "Tsirupia",
    "Rupiani",
    "Mbeca",
    "Kodi",
    "Silinkini",
    "Mbia",
    "Rofia",
  ],
  grid: [
    ["H", "C", "I", "P", "A", "K", "M", "B", "I", "A", "I", "N", "I", "I"],
    ["K", "I", "N", "A", "I", "P", "U", "R", "I", "K", "O", "B", "H", "K"],
    ["M", "K", "I", "L", "R", "R", "P", "A", "L", "G", "U", "A", "I", "R"],
    ["K", "E", "A", "P", "S", "Q", "I", "K", "I", "I", "K", "C", "U", "R"],
    ["K", "I", "L", "O", "V", "I", "A", "I", "M", "B", "E", "C", "A", "A"],
    ["B", "B", "K", "O", "D", "I", "A", "P", "G", "I", "H", "R", "H", "E"],
    ["I", "L", "N", "G", "A", "R", "O", "P", "I", "Y", "A", "E", "E", "N"],
    ["I", "I", "L", "A", "P", "A", "I", "F", "O", "R", "C", "K", "L", "L"],
    ["R", "R", "O", "A", "R", "A", "B", "A", "A", "K", "H", "I", "I", "A"],
    ["A", "I", "P", "A", "N", "I", "S", "A", "E", "A", "I", "I", "A", "O"],
    ["L", "P", "A", "R", "O", "A", "I", "O", "U", "A", "R", "C", "Q", "A"],
    ["D", "S", "I", "L", "I", "N", "K", "I", "N", "I", "U", "A", "A", "R"],
    ["T", "S", "I", "R", "U", "P", "I", "A", "B", "I", "P", "I", "L", "N"],
    ["I", "P", "N", "R", "L", "A", "I", "I", "I", "B", "A", "A", "I", "P"],
  ],
};

export const currenciesKenyaWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currencies-ws2",
  title: "Currencies of Kenya: Puzzle 2",
  topic: "Money Basics",
  theme: "Regional & Dialect Terms for Money",
  instruction: "Find the 10 dialect and tribal currency terms.",
  size: 14,
  words: [
    "Mbesha",
    "Ropyen",
    "Iropiyani",
    "Robia",
    "Zirupia",
    "Ilovia",
    "Chirupi",
    "Rubia",
    "Besa",
    "Luvia",
  ],
  grid: [
    ["U", "P", "S", "E", "I", "E", "C", "R", "P", "L", "Z", "R", "I", "I"],
    ["E", "P", "I", "A", "P", "Z", "A", "Z", "P", "A", "U", "A", "A", "R"],
    ["S", "O", "S", "O", "B", "E", "I", "H", "P", "I", "C", "V", "A", "P"],
    ["E", "I", "I", "I", "A", "A", "R", "E", "I", "R", "H", "H", "I", "H"],
    ["R", "O", "P", "Y", "E", "N", "O", "M", "N", "U", "I", "Z", "R", "A"],
    ["P", "U", "A", "I", "O", "I", "B", "P", "A", "I", "R", "A", "E", "S"],
    ["P", "O", "I", "I", "I", "A", "I", "A", "Y", "A", "U", "U", "L", "I"],
    ["L", "I", "E", "A", "L", "S", "A", "A", "I", "I", "P", "O", "U", "B"],
    ["I", "O", "P", "C", "O", "E", "I", "B", "P", "I", "I", "E", "A", "E"],
    ["R", "R", "R", "I", "V", "P", "I", "Y", "O", "R", "U", "B", "I", "A"],
    ["E", "Y", "A", "U", "I", "I", "B", "A", "R", "P", "E", "U", "U", "Y"],
    ["A", "B", "E", "S", "A", "P", "A", "A", "I", "A", "O", "P", "R", "B"],
    ["O", "Z", "N", "L", "I", "S", "U", "M", "B", "E", "S", "H", "A", "S"],
    ["E", "A", "I", "P", "U", "R", "I", "Z", "A", "R", "I", "A", "I", "H"],
  ],
};

export const currenciesKenyaQuiz: QuizPuzzle = {
  type: "quiz",
  id: "mb-currencies-quiz",
  title: "Currencies of Kenya: Quiz",
  topic: "Money Basics",
  instruction: "Answer questions on Kenyan currency history and linguistic origins.",
  questions: [
    {
      id: 1,
      question: "Before the Shilling, the Indian Rupee was the main currency. Which of these is the most direct local spelling used for it?",
      options: ["Rupia", "Kilovia", "Besa", "Mbia"],
      correctIndex: 0,
      explanation: "Rupia is the direct Swahili and local adaptation of the Indian Silver Rupee introduced during railway construction.",
      hint: "Think of the Indian silver coin that came with the railway — not a Kikuyu or pastoralist cash word.",
    },
    {
      id: 2,
      question: "When the British Shilling was introduced, many communities struggled to say 'shilling.' Which word in the list shows a local adaptation of it?",
      options: ["Silinkini", "Rupiani", "Mbesha", "Ilovia"],
      correctIndex: 0,
      explanation: "Silinkini was adopted in northern and pastoralist communities like the Rendille to represent the shilling.",
      hint: "Listen for a word that still sounds like “shilling”, used by Rendille and other northern groups.",
    },
    {
      id: 3,
      question: "Which word from the list sounds most like the modern 'Rupee' but is used in plural forms in several local dialects?",
      options: ["Rupiani", "Kilovia", "Mbesha", "Kodi"],
      correctIndex: 0,
      explanation: "Rupiani was commonly used across several ethnic groups to denote plural units of rupees.",
      hint: "Look for the rupee root with a plural-style ending, not tax (kodi) or Kamba cash words.",
    },
    {
      id: 4,
      question: "In the past, 'tax' or 'money for the government' was often referred to by this specific term:",
      options: ["Kodi", "Mbica", "Robia", "Besa"],
      correctIndex: 0,
      explanation: "Kodi originated from early poll/hut taxes and remains the standard Swahili word for tax and rent.",
      hint: "This is still the Swahili word for tax and house rent today.",
    },
  ],
};

export const currenciesKenyaCryptogram: CryptogramPuzzle = {
  type: "cryptogram",
  id: "mb-currencies-crypto",
  title: "Currencies of Kenya: A1Z26 Cryptogram",
  topic: "Money Basics",
  instruction: "Using the A1Z26 cipher (A=1, B=2 ... Z=26), decode the indigenous Kenyan currency terms.",
  cipherType: "A1Z26",
  items: [
    {
      number: 1,
      prompt: "The succinct Somali term for money.",
      cipherSequence: [12, 1, 17],
      solution: "LAQ",
      hint: "A 3-letter Somali cash word. Decode A=1, L=12, Q=17 — do not guess English “money”.",
    },
    {
      number: 2,
      prompt: "A long Luhya variation derived from the colonial rupee.",
      cipherSequence: [20, 19, 9, 18, 21, 16, 9, 1],
      solution: "TSIRUPIA",
      hint: "Luhya kept the rupee sound but starts with TS, not R or CH.",
    },
    {
      number: 3,
      prompt: "A melodic Kamba name for cash.",
      cipherSequence: [11, 9, 12, 15, 22, 9, 1],
      solution: "KILOVIA",
      hint: "Kamba family of words related to Luvia / Ilovia; this longer form starts with KI.",
    },
    {
      number: 4,
      prompt: "The specific spelling used by the Teso; also similar to the Luo word for money.",
      cipherSequence: [9, 18, 21, 16, 9, 1],
      solution: "IRUPIA",
      hint: "Same rupee root as Luo “Rupia”, but this Teso form begins with I.",
    },
    {
      number: 5,
      prompt: "The money name shared by the Kikuyu, Meru, and Embu tribes.",
      cipherSequence: [13, 2, 5, 3, 1],
      solution: "MBECA",
      hint: "Central Kenya cash word that sounds like “mbeca”, not the Swahili “pesa”.",
    },
    {
      number: 6,
      prompt: "A short Luhya term for money.",
      cipherSequence: [3, 8, 9, 18, 21, 16, 1],
      solution: "CHIRUPA",
      hint: "Luhya rupee-word beginning with CHI (like “chirupa”), shorter than Tsirupia.",
    },
    {
      number: 7,
      prompt: "A Maasai term, similar to Iropiyani, for currency.",
      cipherSequence: [18, 21, 16, 9, 1, 14, 9],
      solution: "RUPIYANI",
      hint: "Maasai rupee form that starts with R, close to Iropiyani but without the leading I.",
    },
    {
      number: 8,
      prompt: "Used by the Kikuyu and Embu; it sounds like 'deer' but means money.",
      cipherSequence: [13, 2, 9, 1],
      solution: "MBIA",
      hint: "Four letters. Kikuyu/Embu cash word that rhymes with the English word “deer”.",
    },
    {
      number: 9,
      prompt: "Another Kikuyu name for money with a phonetic twist on Indian 'rupee'.",
      cipherSequence: [18, 15, 6, 9, 1],
      solution: "ROFIA",
      hint: "Kikuyu rupee cousin that uses an F sound instead of P or B.",
    },
    {
      number: 10,
      prompt: "A Mijikenda and Swahili word for tax or rent paid to government or a landlord.",
      cipherSequence: [11, 15, 4, 9],
      solution: "KODI",
      hint: "Same everyday Swahili word used for tax and house rent — four letters.",
    },
    {
      number: 11,
      prompt: "The lengthy, traditional Turkana name for money.",
      cipherSequence: [14, 7, 1, 18, 15, 16, 9, 25, 1, 5],
      solution: "NGAROPIYAE",
      hint: "Turkana’s long rupee-based name (10 letters) starting with NGA.",
    },
    {
      number: 12,
      prompt: "The Rendille name that clearly mimics the word 'shilling'.",
      cipherSequence: [19, 9, 12, 9, 14, 11, 9, 14, 9],
      solution: "SILINKINI",
      hint: "Northern pastoralist take on the British “shilling” — listen for SILIN…",
    },
    {
      number: 13,
      prompt: "The Maasai name for money starting with an 'I'.",
      cipherSequence: [9, 18, 15, 16, 9, 25, 1, 14, 9],
      solution: "IROPIYANI",
      hint: "Maasai rupee word that begins with I and ends like “-yani”.",
    },
    {
      number: 14,
      prompt: "Another Luhya variation for money, starting with the last letter of the alphabet.",
      cipherSequence: [26, 9, 18, 21, 16, 9, 1],
      solution: "ZIRUPIA",
      hint: "Luhya rupee spelling that really does start with Z.",
    },
    {
      number: 15,
      prompt: "The specific name for currency used by the Kisii/Gusii people of Kenya.",
      cipherSequence: [3, 8, 9, 18, 21, 16, 9],
      solution: "CHIRUPI",
      hint: "Gusii form of rupee, close to Luhya Chirupa but ends with I.",
    },
    {
      number: 16,
      prompt: "A Kamba term that is a shorter version of Kilovia.",
      cipherSequence: [12, 21, 22, 9, 1],
      solution: "LUVIA",
      hint: "Drop the KI from Kilovia and you get this 5-letter Kamba word.",
    },
    {
      number: 17,
      prompt: "How a Meru speaker might pronounce another common word for money.",
      cipherSequence: [13, 2, 5, 19, 8, 1],
      solution: "MBESHA",
      hint: "Meru cousin of Kikuyu “mbeca”, with a SH sound in the middle.",
    },
    {
      number: 18,
      prompt: "A Kalenjin, Kipsigis and Pokot name for notes and coins.",
      cipherSequence: [18, 15, 16, 25, 5, 14],
      solution: "ROPYEN",
      hint: "Highland Kalenjin cash word — starts with RO and ends with YEN.",
    },
    {
      number: 19,
      prompt: "The primary name used by the Luo people when talking about money.",
      cipherSequence: [18, 21, 16, 9, 1],
      solution: "RUPIA",
      hint: "Luo kept the classic Indian rupee spelling, five letters starting with R.",
    },
    {
      number: 20,
      prompt: "Another Kalenjin term that sounds very close to 'rubia'.",
      cipherSequence: [18, 15, 2, 9, 1],
      solution: "ROBIA",
      hint: "Kalenjin form next to Kikuyu Rubia — O in the second letter, not U.",
    },
    {
      number: 21,
      prompt: "Yet another Kamba variation, similar to Luvia.",
      cipherSequence: [9, 12, 15, 22, 9, 1],
      solution: "ILOVIA",
      hint: "Kamba variant of Kilovia that starts with I instead of K.",
    },
    {
      number: 22,
      prompt: "A classic Kikuyu term for 'rupee'.",
      cipherSequence: [18, 21, 2, 9, 1],
      solution: "RUBIA",
      hint: "Kikuyu rupee word with a B, not an F (that one is Rofia).",
    },
    {
      number: 23,
      prompt: "The word used by the Turkana, Samburu, and Rendille communities of Kenya to describe money.",
      cipherSequence: [2, 5, 19, 1],
      solution: "BESA",
      hint: "Short pastoralist cash word (4 letters) used from Turkana to Rendille.",
    },
    {
      number: 24,
      prompt: "The most common Swahili word for money, used also by the Taita and Mijikenda communities.",
      cipherSequence: [16, 5, 19, 1],
      solution: "PESA",
      hint: "The everyday Coastal / national Swahili word for cash — four letters.",
    },
  ],
};
