import { WordSearchPuzzle, CrosswordPuzzle, QuizPuzzle } from "../types";

export const kenyanCurrencyWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currency-ws1",
  title: "Features of Kenyan Currency: Puzzle 1",
  topic: "Money Basics",
  theme: "Symbols & Themes of Kenyan Banknotes",
  instruction: "Find the key security features, wildlife symbols, and landmarks on Kenyan currency.",
  size: 14,
  words: [
    "BUFFALO",
    "CBK",
    "COAT OF ARMS",
    "ELEPHANT",
    "GOVERNOR",
    "KICC",
    "LEOPARD",
    "LION",
    "RHINO",
    "SHILLING",
    "WATERMARK",
    "KENYATTA",
    "MICROPRINTING",
  ],
  grid: [
    ["C", "O", "A", "T", "O", "F", "A", "R", "M", "S", "K", "I", "C", "C"],
    ["E", "L", "E", "P", "H", "A", "N", "T", "B", "C", "B", "K", "Q", "B"],
    ["L", "E", "O", "P", "A", "R", "D", "X", "U", "Y", "Z", "E", "W", "U"],
    ["W", "A", "T", "E", "R", "M", "A", "R", "K", "F", "F", "N", "A", "F"],
    ["S", "H", "I", "L", "L", "I", "N", "G", "F", "F", "A", "Y", "T", "F"],
    ["G", "O", "V", "E", "R", "N", "O", "R", "A", "A", "L", "A", "E", "A"],
    ["M", "I", "C", "R", "O", "P", "R", "I", "N", "T", "I", "N", "G", "L"],
    ["K", "E", "N", "Y", "A", "T", "T", "A", "L", "I", "O", "N", "M", "O"],
    ["R", "H", "I", "N", "O", "S", "H", "I", "L", "L", "I", "N", "G", "S"],
    ["C", "E", "N", "T", "R", "A", "L", "B", "A", "N", "K", "S", "A", "E"],
    ["S", "E", "C", "U", "R", "I", "T", "Y", "T", "H", "R", "E", "A", "D"],
    ["M", "A", "A", "S", "A", "I", "M", "A", "R", "A", "B", "C", "D", "E"],
    ["A", "G", "R", "I", "C", "U", "L", "T", "U", "R", "E", "X", "Y", "Z"],
    ["G", "O", "L", "D", "E", "N", "J", "U", "B", "I", "L", "E", "E", "S"],
  ],
};

export const kenyanCurrencyWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currency-ws2",
  title: "Features of Kenyan Currency: Puzzle 2",
  topic: "Money Basics",
  theme: "Economic Activities on New Banknotes",
  instruction: "Search for economic pillars represented on Kenya's new generation currency.",
  size: 14,
  words: [
    "AGRICULTURE",
    "EDUCATION",
    "ENERGY",
    "GOVERNANCE",
    "GREEN ENERGY",
    "HEALTH",
    "INFRASTRUCTURE",
    "MANUFACTURING",
    "MARITIME",
    "MINING",
    "RENEWABLE",
    "SECURITY",
    "SERVICES",
    "TOURISM",
  ],
  grid: [
    ["A", "G", "R", "I", "C", "U", "L", "T", "U", "R", "E", "A", "B", "C"],
    ["E", "D", "U", "C", "A", "T", "I", "O", "N", "D", "E", "F", "G", "H"],
    ["G", "R", "E", "E", "N", "E", "N", "E", "R", "G", "Y", "I", "J", "K"],
    ["G", "O", "V", "E", "R", "N", "A", "N", "C", "E", "L", "M", "N", "O"],
    ["I", "N", "F", "R", "A", "S", "T", "R", "U", "C", "T", "U", "R", "E"],
    ["M", "A", "N", "U", "F", "A", "C", "T", "U", "R", "I", "N", "G", "S"],
    ["M", "A", "R", "I", "T", "I", "M", "E", "T", "O", "U", "R", "I", "S"],
    ["S", "E", "C", "U", "R", "I", "T", "Y", "H", "E", "A", "L", "T", "H"],
    ["R", "E", "N", "E", "W", "A", "B", "L", "E", "E", "N", "E", "R", "G"],
    ["T", "O", "U", "R", "I", "S", "M", "S", "E", "R", "V", "I", "C", "E"],
    ["S", "E", "R", "V", "I", "C", "E", "S", "B", "A", "N", "K", "I", "N"],
    ["M", "I", "N", "I", "N", "G", "F", "I", "N", "A", "N", "C", "E", "S"],
    ["P", "U", "B", "L", "I", "C", "W", "O", "R", "K", "S", "L", "A", "W"],
    ["T", "R", "A", "N", "S", "P", "O", "R", "T", "H", "U", "B", "K", "E"],
  ],
};

export const kenyanCurrencyWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currency-ws3",
  title: "Features of Kenyan Currency: Puzzle 3",
  topic: "Money Basics",
  theme: "Security Features & Tactile Elements",
  instruction: "Find anti-counterfeiting features embedded into Kenyan banknotes.",
  size: 14,
  words: [
    "COLOUR CHANGE",
    "CORNER LINE",
    "EDGE MARKS",
    "EMBOSSED",
    "FEEL",
    "FLUORESCENCE",
    "INTAGLIO",
    "LOOK",
    "MICROTEXT",
    "RAISED PRINT",
    "SEE THROUGH",
    "THREAD",
    "TILT",
    "UV LIGHT",
  ],
  grid: [
    ["C", "O", "L", "O", "U", "R", "C", "H", "A", "N", "G", "E", "A", "B"],
    ["F", "E", "E", "L", "L", "O", "O", "K", "T", "I", "L", "T", "C", "D"],
    ["C", "O", "R", "N", "E", "R", "L", "I", "N", "E", "S", "E", "F", "G"],
    ["E", "D", "G", "E", "M", "A", "R", "K", "S", "H", "I", "J", "K", "L"],
    ["I", "N", "T", "A", "G", "L", "I", "O", "P", "R", "I", "N", "T", "M"],
    ["R", "A", "I", "S", "E", "D", "P", "R", "I", "N", "T", "N", "O", "P"],
    ["S", "E", "E", "T", "H", "R", "O", "U", "G", "H", "Q", "R", "S", "T"],
    ["M", "I", "C", "R", "O", "T", "E", "X", "T", "U", "V", "W", "X", "Y"],
    ["F", "L", "U", "O", "R", "E", "S", "C", "E", "N", "C", "E", "Z", "A"],
    ["U", "V", "L", "I", "G", "H", "T", "T", "H", "R", "E", "A", "D", "B"],
    ["S", "E", "C", "U", "R", "I", "T", "Y", "F", "E", "A", "T", "U", "R"],
    ["B", "A", "N", "K", "N", "O", "T", "E", "S", "C", "A", "N", "N", "E"],
    ["C", "O", "U", "N", "T", "E", "R", "F", "E", "I", "T", "C", "H", "K"],
    ["T", "A", "C", "T", "I", "L", "E", "B", "R", "A", "I", "L", "L", "E"],
  ],
};

export const kenyanCurrencyCrossword1: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-currency-cw1",
  title: "Kenyan Currency Security Crossword",
  topic: "Money Basics",
  instruction: "Complete the crossword puzzle using security features of Kenyan banknotes.",
  rows: 8,
  cols: 10,
  wordBank: ["WATERMARK", "THREAD", "LION", "KICC", "SHILLING", "GOVERNOR", "RHINO", "INTAGLIO"],
  acrossClues: [
    {
      number: 1,
      clue: "The national monetary unit of Kenya.",
      answer: "SHILLING",
      row: 1,
      col: 1,
      direction: "across",
    },
    {
      number: 3,
      clue: "Famous tower in Nairobi appearing on all new banknotes.",
      answer: "KICC",
      row: 3,
      col: 2,
      direction: "across",
    },
    {
      number: 5,
      clue: "King of the jungle featured on the KSh 200 note.",
      answer: "LION",
      row: 5,
      col: 3,
      direction: "across",
    },
    {
      number: 7,
      clue: "Security strip embedded vertically inside the paper.",
      answer: "THREAD",
      row: 7,
      col: 2,
      direction: "across",
    },
  ],
  downClues: [
    {
      number: 1,
      clue: "Translucent watermark image of a lion visible when held to light.",
      answer: "WATERMARK",
      row: 0,
      col: 1,
      direction: "down",
    },
    {
      number: 2,
      clue: "Raised printing method used for tactile recognition.",
      answer: "INTAGLIO",
      row: 0,
      col: 4,
      direction: "down",
    },
    {
      number: 4,
      clue: "Senior official whose signature authenticates each legal banknote.",
      answer: "GOVERNOR",
      row: 0,
      col: 6,
      direction: "down",
    },
    {
      number: 6,
      clue: "Endangered horned animal featured on the KSh 1000 note.",
      answer: "RHINO",
      row: 2,
      col: 8,
      direction: "down",
    },
  ],
};

export const kenyanCurrencyQuiz1: QuizPuzzle = {
  type: "quiz",
  id: "mb-currency-quiz1",
  title: "Kenyan Currency Master Quiz",
  topic: "Money Basics",
  instruction: "Demonstrate your mastery of Kenyan banknotes, coins, and security verification.",
  questions: [
    {
      id: 1,
      question: "Which landmark building appears on the front of all new generation Kenyan banknotes?",
      options: [
        "State House Nairobi",
        "Kenyatta International Convention Centre (KICC)",
        "Parliament Buildings",
        "National Museum of Kenya",
      ],
      correctIndex: 1,
      explanation:
        "The KICC and the statue of Founding Father Mzee Jomo Kenyatta appear on the front face of every banknote.",
    },
    {
      id: 2,
      question: "Which animal of the Big Five is featured on the 1,000 Kenyan Shilling note?",
      options: ["Lion", "Elephant", "Rhino (and Peace / Governance theme)", "Leopard"],
      correctIndex: 2,
      explanation:
        "The KSh 1,000 banknote highlights the rhinoceros along with the theme of Governance.",
    },
    {
      id: 3,
      question: "What is the three-step CBK motto for checking whether a banknote is genuine?",
      options: [
        "Smell, Taste, Listen",
        "Feel, Look, Tilt",
        "Fold, Cut, Wash",
        "Scan, Burn, Weigh",
      ],
      correctIndex: 1,
      explanation:
        "Central Bank of Kenya recommends 'Feel' (raised print), 'Look' (watermark to light), and 'Tilt' (security thread color shift).",
    },
    {
      id: 4,
      question: "Which institution is constitutionally responsible for issuing currency in Kenya?",
      options: [
        "Kenya Revenue Authority (KRA)",
        "Central Bank of Kenya (CBK)",
        "Nairobi Securities Exchange (NSE)",
        "Ministry of Finance only",
      ],
      correctIndex: 1,
      explanation:
        "The Central Bank of Kenya (CBK) holds the sole constitutional mandate to design, issue, and manage Kenyan currency.",
    },
    {
      id: 5,
      question: "What animal is depicted on the KSh 50 banknote?",
      options: ["Buffalo", "Lion", "Leopard", "Elephant"],
      correctIndex: 0,
      explanation:
        "The KSh 50 banknote depicts the Cape Buffalo along with Kenya's Green Energy theme.",
    },
    {
      id: 6,
      question: "How can visually impaired individuals distinguish between different banknote denominations?",
      options: [
        "Banknotes have different tactile raised edge bars (1 bar for 50, 2 for 100, up to 5 for 1000)",
        "By smelling different scented inks",
        "By listening to audio chips in notes",
        "All notes are identical shapes and flat",
      ],
      correctIndex: 0,
      explanation:
        "Kenyan banknotes feature distinct raised tactile lines on the corners so people with visual impairment can identify denominations.",
    },
    {
      id: 7,
      question: "What theme is celebrated on the KSh 100 banknote?",
      options: [
        "Agriculture and Farming (along with the Leopard)",
        "Mining and Oil",
        "Space Exploration",
        "Aerospace Engineering",
      ],
      correctIndex: 0,
      explanation:
        "The KSh 100 banknote highlights Agriculture & Food Security paired with the Leopard.",
    },
    {
      id: 8,
      question: "What theme and animal are featured on the KSh 500 banknote?",
      options: [
        "Tourism & Wildlife with the Lion",
        "Tourism & Wildlife with the Lion (KSh 200 has Social Services & Rhino/Leopard, KSh 500 has Tourism & Lion)",
        "Tourism with the Lion",
        "Tourism & Wildlife with the Elephant",
      ],
      correctIndex: 0,
      explanation:
        "The KSh 500 banknote features the majestic Lion and highlights Tourism & Wildlife.",
    },
    {
      id: 9,
      question: "What occurs when you tilt the security thread on genuine new generation notes?",
      options: [
        "The thread changes color smoothly from red to green and shows the denomination number",
        "The note plays a ringing sound",
        "The paper becomes completely transparent",
        "The note disappears",
      ],
      correctIndex: 0,
      explanation:
        "The security thread features an optical variable effect that shifts color when viewed from different angles.",
    },
    {
      id: 10,
      question: "What are the two official signatures found on all valid Kenyan banknotes?",
      options: [
        "The Governor of the Central Bank of Kenya and the Member / Board Secretary",
        "The President and Prime Minister",
        "The Mayor and Chief Justice",
        "The Chief of Police and Army General",
      ],
      correctIndex: 0,
      explanation:
        "Every banknote is signed by the Governor of the CBK and the Member of the Board to authenticate its legal validity.",
    },
  ],
};
