import { WordSearchPuzzle, CrosswordPuzzle, QuizPuzzle, ActivityPuzzle } from "../types";

export const kenyanCurrencyWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currency-ws1",
  title: "Features of Kenyan Currency: Puzzle 1",
  topic: "Money Basics",
  theme: "Symbols & Wildlife of Kenyan Notes",
  instruction: "Find the 12 hidden currency features and Kenyan symbols in the grid.",
  size: 14,
  words: [
    "Elephant",
    "Red",
    "Buffalo",
    "Leopard",
    "Rhino",
    "Bars",
    "Giraffe",
    "KICC",
    "Watermark",
    "Dove",
    "Blue",
    "Governance",
  ],
  grid: [
    ["N", "F", "W", "A", "T", "E", "R", "M", "A", "R", "K", "I", "A", "N"],
    ["E", "A", "O", "K", "E", "C", "L", "L", "E", "A", "D", "L", "E", "G"],
    ["R", "I", "O", "R", "C", "P", "B", "E", "P", "I", "E", "O", "E", "A"],
    ["L", "L", "F", "L", "N", "R", "A", "E", "P", "O", "B", "O", "E", "F"],
    ["F", "E", "S", "R", "A", "B", "F", "O", "P", "H", "D", "E", "R", "R"],
    ["B", "L", "U", "E", "N", "O", "C", "A", "V", "U", "A", "F", "R", "E"],
    ["R", "E", "E", "F", "R", "R", "R", "E", "V", "H", "O", "N", "R", "E"],
    ["F", "C", "A", "C", "E", "D", "S", "H", "E", "L", "N", "P", "T", "N"],
    ["N", "E", "E", "E", "V", "S", "O", "C", "A", "E", "F", "A", "P", "F"],
    ["P", "I", "E", "E", "O", "E", "D", "F", "B", "C", "C", "I", "K", "A"],
    ["I", "D", "O", "E", "G", "R", "F", "E", "N", "H", "D", "O", "V", "E"],
    ["U", "I", "F", "A", "O", "U", "N", "R", "R", "H", "R", "E", "T", "I"],
    ["P", "E", "F", "A", "B", "F", "R", "H", "O", "N", "I", "H", "R", "A"],
    ["G", "I", "R", "A", "F", "F", "E", "E", "H", "E", "R", "H", "O", "R"],
  ],
};

export const kenyanCurrencyWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currency-ws2",
  title: "Features of Kenyan Currency: Puzzle 2",
  topic: "Money Basics",
  theme: "Security Features & Modern Banking",
  instruction: "Search for security marks, denominations, and mobile money services.",
  size: 14,
  words: [
    "Coat of Arms",
    "Visa",
    "Bimetallic",
    "Pesalink",
    "Lion",
    "Purple",
    "Airtel",
    "Green",
    "Notes",
    "Security Thread",
    "Twenty Four",
    "Mpesa",
  ],
  grid: [
    ["S", "E", "C", "U", "T", "I", "R", "Y", "T", "H", "R", "E", "A", "D"],
    ["L", "E", "G", "O", "B", "I", "M", "E", "T", "A", "L", "L", "I", "C"],
    ["O", "D", "O", "R", "I", "A", "O", "L", "M", "R", "L", "P", "K", "R"],
    ["N", "O", "F", "I", "R", "T", "F", "K", "E", "C", "F", "U", "N", "U"],
    ["L", "N", "O", "T", "E", "S", "T", "H", "I", "O", "A", "R", "I", "O"],
    ["N", "E", "E", "R", "G", "M", "L", "Y", "N", "A", "O", "P", "L", "F"],
    ["A", "N", "V", "Y", "Y", "R", "O", "T", "T", "T", "P", "L", "A", "Y"],
    ["T", "I", "I", "O", "R", "R", "M", "L", "I", "O", "U", "E", "S", "T"],
    ["A", "E", "A", "D", "L", "S", "K", "E", "P", "F", "T", "U", "E", "N"],
    ["P", "M", "P", "E", "S", "A", "T", "T", "A", "A", "U", "T", "P", "E"],
    ["T", "U", "S", "P", "N", "B", "L", "R", "S", "R", "W", "M", "A", "W"],
    ["R", "A", "M", "E", "D", "P", "I", "I", "T", "M", "R", "I", "S", "T"],
    ["A", "V", "A", "P", "T", "S", "O", "A", "O", "S", "C", "R", "I", "E"],
    ["E", "I", "A", "O", "P", "Y", "N", "I", "L", "S", "F", "I", "V", "T"],
  ],
};

export const kenyanCurrencyWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currency-ws3",
  title: "Features of Kenyan Currency: Puzzle 3",
  topic: "Money Basics",
  theme: "Tactile Features, Cash & Signatures",
  instruction: "Find the 14 words describing Kenyan cash materials, values, and security.",
  size: 14,
  words: [
    "Symbols",
    "Wildlife",
    "Agriculture",
    "Cash",
    "Cotton Paper",
    "Thousand",
    "Bars",
    "Hundred",
    "Wallet",
    "Shilling",
    "Coins",
    "Signature",
    "Microprint",
    "Tourism",
  ],
  grid: [
    ["U", "D", "M", "I", "C", "R", "O", "P", "R", "I", "N", "T", "D", "N"],
    ["R", "E", "P", "A", "P", "N", "O", "T", "T", "O", "C", "O", "R", "S"],
    ["W", "A", "L", "L", "E", "T", "D", "R", "R", "E", "G", "U", "E", "C"],
    ["A", "G", "R", "I", "C", "U", "L", "T", "U", "R", "E", "R", "R", "S"],
    ["O", "S", "R", "T", "H", "O", "A", "T", "N", "S", "Y", "I", "U", "R"],
    ["O", "R", "S", "H", "W", "N", "I", "A", "C", "Y", "I", "S", "T", "G"],
    ["B", "A", "U", "O", "I", "O", "S", "N", "D", "M", "E", "M", "A", "G"],
    ["A", "B", "S", "U", "L", "I", "H", "H", "S", "B", "L", "I", "N", "C"],
    ["S", "T", "T", "S", "D", "L", "U", "N", "I", "O", "R", "D", "G", "A"],
    ["E", "P", "C", "A", "L", "T", "N", "I", "C", "L", "R", "L", "I", "B"],
    ["U", "O", "C", "N", "I", "L", "D", "T", "T", "S", "L", "I", "S", "C"],
    ["A", "E", "A", "D", "F", "T", "R", "N", "R", "S", "A", "I", "M", "N"],
    ["T", "I", "S", "R", "E", "N", "E", "A", "O", "T", "L", "G", "N", "A"],
    ["C", "L", "H", "I", "I", "R", "D", "D", "D", "D", "R", "S", "U", "G"],
  ],
};

export const kenyanCurrencyWordSearch4: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-currency-ws4",
  title: "Features of Kenyan Currency: Puzzle 4",
  topic: "Money Basics",
  theme: "National Pillars & Green Energy on Notes",
  instruction: "Find the 14 national themes illustrated on Kenyan banknotes.",
  size: 14,
  words: [
    "Parks",
    "Education",
    "Green Energy",
    "Solar Power",
    "Livestock",
    "Windmills",
    "Parliament",
    "Athletics",
    "Tea",
    "Denomination",
    "Value",
    "Geothermal",
    "Beach",
    "Maize",
  ],
  grid: [
    ["Y", "O", "I", "L", "N", "O", "I", "T", "A", "C", "U", "D", "E", "G"],
    ["G", "K", "H", "P", "A", "R", "L", "I", "A", "M", "E", "N", "T", "N"],
    ["R", "P", "L", "I", "N", "A", "P", "A", "R", "K", "S", "E", "E", "R"],
    ["E", "O", "R", "I", "I", "T", "I", "K", "R", "B", "L", "D", "O", "A"],
    ["N", "W", "O", "C", "V", "U", "E", "M", "T", "N", "M", "D", "K", "T"],
    ["E", "E", "S", "A", "S", "E", "T", "L", "E", "U", "A", "E", "E", "H"],
    ["N", "R", "N", "O", "M", "N", "S", "R", "A", "L", "O", "S", "S", "L"],
    ["E", "O", "I", "R", "A", "A", "E", "T", "T", "I", "T", "E", "E", "E"],
    ["E", "I", "L", "O", "T", "N", "I", "N", "O", "R", "R", "I", "I", "T"],
    ["R", "T", "M", "A", "E", "A", "L", "Z", "H", "C", "A", "E", "B", "I"],
    ["G", "O", "R", "U", "V", "A", "L", "U", "E", "E", "K", "C", "O", "C"],
    ["I", "U", "K", "L", "A", "M", "R", "E", "H", "T", "O", "E", "G", "S"],
    ["I", "S", "D", "E", "N", "O", "M", "I", "N", "A", "T", "I", "O", "N"],
    ["T", "L", "W", "I", "N", "D", "M", "I", "L", "L", "S", "E", "E", "A"],
  ],
};

export const kenyanCurrencyQuiz1: QuizPuzzle = {
  type: "quiz",
  id: "mb-currency-quiz1",
  title: "Features of Kenyan Currency: Quiz",
  topic: "Money Basics",
  instruction: "Answer all 10 questions based on Kenya's new generation currency.",
  questions: [
    {
      id: 1,
      question: "What is the official name of the money we use in Kenya?",
      options: ["Dollar", "Shilling", "PesaLink", "Euro"],
      correctIndex: 1,
      explanation: "The official national currency unit of Kenya is the Kenya Shilling (KES / KSh).",
    },
    {
      id: 2,
      question: "Which iconic building is featured on the front of all new generation Kenyan banknotes?",
      options: ["KICC", "Parliament", "Central Bank", "National Museum"],
      correctIndex: 0,
      explanation: "The Kenyatta International Convention Centre (KICC) in Nairobi appears on the front of all notes.",
    },
    {
      id: 3,
      question: "Our banknotes are not made of regular paper; they are printed on special, durable?",
      options: ["Plastic film", "Cotton paper", "Recycled wood", "Silk fibers"],
      correctIndex: 1,
      explanation: "Kenyan banknotes are printed on durable 100% cotton substrate paper with high tear resistance.",
    },
    {
      id: 4,
      question: "To help people with visual impairments identify notes, they feature a series of raised?",
      options: ["Bars", "Circles", "Squares", "Stars"],
      correctIndex: 0,
      explanation: "Tactile raised bars (1 to 5 bars) on the edges allow blind and visually impaired citizens to feel the denomination.",
    },
    {
      id: 5,
      question: "Which 'Big Five' animal is prominently featured on the 1,000 Shilling note?",
      options: ["Rhino", "Leopard", "Lion", "Elephant"],
      correctIndex: 3,
      explanation: "The 1,000 shilling note features the majestic Elephant alongside the theme of Governance.",
    },
    {
      id: 6,
      question: "If you hold a note up to the light, you will see a hidden image of a lion's head. This is called a?",
      options: ["Microprint", "Watermark", "Signature", "Security thread"],
      correctIndex: 1,
      explanation: "The watermark shows the lion's head and the letters 'CBK' with high and low tonal shades.",
    },
    {
      id: 7,
      question: "On the back of the 50 shilling note, which sector of our economy is represented by images of green energy like windmills and geothermal power?",
      options: ["Energy", "Tourism", "Athletics", "Agriculture"],
      correctIndex: 0,
      explanation: "The 50 shilling note showcases Green Energy, featuring Olkaria geothermal power and wind turbines.",
    },
    {
      id: 8,
      question: "What type of physical money is bimetallic i.e. made of two different metals?",
      options: ["The 1,000 note", "The 20 shilling coin", "The security thread", "All banknotes"],
      correctIndex: 1,
      explanation: "The 20 shilling coin has an outer brass ring and an inner nickel centre (bimetallic construction).",
    },
    {
      id: 9,
      question: "Every valid banknote must have the ___ of the Governor of the Central Bank of Kenya.",
      options: ["Signature", "Photo", "Fingerprint", "Stamp"],
      correctIndex: 0,
      explanation: "Each note is legally signed by the Governor of the Central Bank of Kenya and the Member of the Board.",
    },
    {
      id: 10,
      question: "On the back of the 200 shilling note, which part of Kenyan life is shown through images of maize and livestock?",
      options: ["Education", "Agriculture", "Athletics", "Governance"],
      correctIndex: 1,
      explanation: "The 200 shilling note is themed around Agriculture and Social Services, depicting maize, cattle, and farming.",
    },
  ],
};

export const kenyanCurrencyCrossword1: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-currency-cw1",
  title: "Features of Kenyan Currency: Crossword 1",
  topic: "Money Basics",
  instruction: "Fill in the white squares with the correct financial terms from Kenyan currency.",
  rows: 10,
  cols: 10,
  wordBank: [
    "Watermark",
    "Dove",
    "Elephant",
    "Buffalo",
    "Bars",
    "Governance",
    "KICC",
    "Leopard",
    "Giraffe",
  ],
  acrossClues: [
    {
      number: 5,
      clue: "The iconic Nairobi city landmark featured on the front of all banknotes.",
      answer: "KICC",
      row: 1,
      col: 6,
      direction: "across",
    },
    {
      number: 6,
      clue: "The animal found on the 1,000 shilling note and the 20 shilling coin.",
      answer: "ELEPHANT",
      row: 3,
      col: 0,
      direction: "across",
    },
    {
      number: 8,
      clue: "A member of the 'Big Five' animals found on the 100 shilling note, themed around agriculture.",
      answer: "LEOPARD",
      row: 6,
      col: 1,
      direction: "across",
    },
    {
      number: 9,
      clue: "The specific theme illustrated on the back of the 1,000 shilling note, featuring the Parliament building.",
      answer: "GOVERNANCE",
      row: 8,
      col: 0,
      direction: "across",
    },
  ],
  downClues: [
    {
      number: 1,
      clue: "A small bird shown on the front of banknotes to symbolize a peaceful Kenya.",
      answer: "DOVE",
      row: 0,
      col: 0,
      direction: "down",
    },
    {
      number: 2,
      clue: "The animal depicted on the 50 bob note which also represents 'Green Energy' sector of the economy.",
      answer: "BUFFALO",
      row: 0,
      col: 3,
      direction: "down",
    },
    {
      number: 3,
      clue: "A security feature that reveals a lion's head and the letters 'CBK' when held up to the light.",
      answer: "WATERMARK",
      row: 0,
      col: 5,
      direction: "down",
    },
    {
      number: 4,
      clue: "The animal featured on the 1 bob coin, the smallest denomination in Kenyan currency.",
      answer: "GIRAFFE",
      row: 0,
      col: 7,
      direction: "down",
    },
    {
      number: 8,
      clue: "Tactile features on the edges of banknotes ranging from 1 to 5 that help visually impaired people identify value.",
      answer: "BARS",
      row: 4,
      col: 4,
      direction: "down",
    },
  ],
};

export const kenyanCurrencyCrossword2: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-currency-cw2",
  title: "Features of Kenyan Currency: Crossword 2",
  topic: "Money Basics",
  instruction: "Solve the crossword on security threads, coins, and official symbols.",
  rows: 10,
  cols: 10,
  wordBank: [
    "Bimetallic",
    "Security Thread",
    "Rhino",
    "Red",
    "Twenty Four",
    "Thousand",
    "Coat of Arms",
    "Microprint",
    "Lion",
  ],
  acrossClues: [
    {
      number: 1,
      clue: "The main characteristic of the 5, 10, and 20 shilling coins, which are made of two different metals.",
      answer: "BIMETALLIC",
      row: 0,
      col: 0,
      direction: "across",
    },
    {
      number: 6,
      clue: "The micro fibres embedded in banknotes to prevent counterfeiting.",
      answer: "SECURITYTHREAD",
      row: 3,
      col: 0,
      direction: "across",
    },
    {
      number: 7,
      clue: "The animal depicted on the 200 shilling note and the 5 shilling coin.",
      answer: "RHINO",
      row: 6,
      col: 0,
      direction: "across",
    },
    {
      number: 8,
      clue: "The specific color the security thread shifts to when the 500 bob note is tilted.",
      answer: "RED",
      row: 6,
      col: 6,
      direction: "across",
    },
    {
      number: 9,
      clue: "The year of print i.e. 2024 now clearly marked on all updated denominations.",
      answer: "TWENTYFOUR",
      row: 9,
      col: 0,
      direction: "across",
    },
  ],
  downClues: [
    {
      number: 2,
      clue: "Value of the highest banknote in Kenya shilling.",
      answer: "THOUSAND",
      row: 0,
      col: 2,
      direction: "down",
    },
    {
      number: 3,
      clue: "The national symbol found on the front of all Kenyan coins and banknotes.",
      answer: "COATOFARMS",
      row: 0,
      col: 5,
      direction: "down",
    },
    {
      number: 4,
      clue: "The tiny letters printed on banknotes for security.",
      answer: "MICROPRINT",
      row: 0,
      col: 7,
      direction: "down",
    },
    {
      number: 5,
      clue: "The animal printed on the 500 shilling note and the 10 shilling coin.",
      answer: "LION",
      row: 2,
      col: 3,
      direction: "down",
    },
  ],
};

export const tactileSecurityActivity: ActivityPuzzle = {
  type: "activity",
  id: "mb-tactile-bars-activity",
  title: "Banknote Tactile Bars Inspection",
  topic: "Money Basics",
  subtype: "home_treasure_hunt",
  instruction: "Take a real or sample Kenyan banknote and identify the tactile security bars on the edges.",
  config: {
    steps: [
      {
        step: 1,
        title: "Locate the Edge Bars",
        description: "Close your eyes and run your fingers along the left and right edges of a Kenyan banknote to feel the raised embossed lines.",
      },
      {
        step: 2,
        title: "Bar Count vs Value Match",
        description: "1 bar = 50 KSh (Green), 2 bars = 100 KSh (Violet), 3 bars = 200 KSh (Blue), 4 bars = 500 KSh (Green/Gold), 5 bars = 1,000 KSh (Brown).",
      },
      {
        step: 3,
        title: "Watermark & Security Thread Check",
        description: "Hold the note up to any bright light to see the lion's head watermark and tilt it to see the colour-shifting ribbon thread.",
      },
    ],
  },
};
