import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const foundationsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-foundations-ws1",
  title: "Foundations of Money: Puzzle 1",
  topic: "Money Basics",
  theme: "What is Money & Early Trade",
  instruction: "Find the 12 hidden words from the word bank in the letter grid.",
  size: 14,
  words: [
    "Budget",
    "Balance",
    "Loss",
    "Coins",
    "Wealth",
    "Salary",
    "Allowance",
    "Profit",
    "Pocket Money",
    "Expense",
    "Wages",
    "Backpay",
  ],
  grid: [
    ["X", "C", "O", "I", "N", "S", "A", "A", "O", "V", "E", "W", "P", "N"],
    ["A", "R", "E", "D", "T", "L", "E", "L", "N", "U", "L", "S", "R", "Y"],
    ["S", "W", "O", "A", "O", "O", "C", "L", "L", "E", "B", "S", "R", "E"],
    ["C", "G", "A", "E", "C", "S", "C", "O", "Y", "N", "C", "A", "T", "I"],
    ["Y", "S", "N", "G", "T", "S", "S", "W", "B", "E", "L", "C", "I", "C"],
    ["A", "E", "E", "I", "E", "A", "Y", "A", "C", "A", "O", "W", "M", "S"],
    ["P", "A", "X", "X", "V", "S", "K", "N", "S", "A", "O", "L", "T", "N"],
    ["K", "W", "P", "A", "I", "A", "A", "C", "A", "P", "A", "P", "A", "A"],
    ["C", "E", "E", "L", "D", "L", "S", "E", "A", "C", "O", "E", "A", "S"],
    ["A", "A", "N", "Y", "A", "I", "I", "S", "A", "O", "L", "E", "G", "P"],
    ["B", "L", "S", "B", "E", "F", "P", "R", "O", "F", "I", "T", "G", "G"],
    ["E", "T", "E", "P", "O", "C", "K", "E", "T", "M", "O", "N", "E", "Y"],
    ["O", "H", "O", "C", "K", "O", "E", "B", "U", "D", "G", "E", "T", "N"],
    ["L", "I", "T", "B", "L", "O", "S", "B", "A", "E", "B", "P", "W", "N"],
  ],
};

export const foundationsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-foundations-ws2",
  title: "Foundations of Money: Puzzle 2",
  topic: "Money Basics",
  theme: "Value, Exchange & Markets",
  instruction: "Find the 14 words hidden in the puzzle grid.",
  size: 14,
  words: [
    "Trade",
    "Earn",
    "Price",
    "Sale",
    "Revenue",
    "Notes",
    "Income",
    "Markets",
    "Products",
    "Buy",
    "Invest",
    "Sell",
    "Acquire",
    "Cash",
  ],
  grid: [
    ["I", "S", "T", "H", "P", "E", "P", "R", "O", "D", "U", "C", "T", "S"],
    ["N", "N", "E", "M", "A", "R", "K", "E", "T", "S", "E", "E", "P", "L"],
    ["U", "S", "A", "S", "E", "L", "L", "A", "D", "N", "O", "T", "E", "S"],
    ["A", "L", "S", "N", "L", "D", "R", "A", "M", "R", "L", "E", "R", "I"],
    ["C", "T", "A", "R", "T", "N", "R", "A", "S", "V", "R", "E", "C", "N"],
    ["Q", "R", "I", "D", "P", "T", "A", "T", "U", "E", "E", "T", "A", "L"],
    ["U", "E", "U", "N", "S", "T", "E", "S", "E", "C", "E", "P", "I", "P"],
    ["I", "T", "L", "V", "C", "A", "L", "E", "V", "I", "E", "P", "A", "R"],
    ["R", "I", "O", "E", "D", "O", "U", "E", "O", "R", "E", "B", "A", "T"],
    ["E", "N", "S", "R", "L", "N", "M", "T", "S", "P", "P", "U", "O", "O"],
    ["H", "N", "R", "A", "E", "A", "U", "E", "R", "E", "R", "Y", "D", "P"],
    ["S", "E", "C", "V", "R", "A", "S", "Y", "P", "N", "I", "K", "N", "Y"],
    ["A", "M", "E", "H", "N", "R", "V", "U", "T", "S", "E", "V", "N", "I"],
    ["C", "R", "R", "T", "R", "A", "D", "E", "C", "S", "A", "T", "E", "T"],
  ],
};

export const foundationsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "mb-foundations-quiz",
  title: "Foundations of Money: Quiz",
  topic: "Money Basics",
  instruction: "Test your money fundamentals with questions from the official workbook.",
  questions: [
    {
      id: 1,
      question: "When you get money from your parents to spend on small things for yourself, it is called?",
      options: ["Salary", "Pocket Money", "Profit", "Revenue"],
      correctIndex: 1,
      explanation: "Pocket money is a small regular amount given by parents to children for their personal expenses.",
    },
    {
      id: 2,
      question: "A plan that helps you decide how much money you will spend and how much you will save is a?",
      options: ["Budget", "Market", "Sale", "Backpay"],
      correctIndex: 0,
      explanation: "A budget is a personal financial plan that tracks income, spending, and savings goals.",
    },
    {
      id: 3,
      question: "Money that you put aside for the future instead of spending it immediately is known as?",
      options: ["Expense", "Savings", "Loss", "Trade"],
      correctIndex: 1,
      explanation: "Savings represent money set aside for emergencies, future purchases, and long-term security.",
    },
    {
      id: 4,
      question: "When a shopkeeper sells an item for more than they bought it for, the extra money they make is?",
      options: ["Profit", "Loss", "Price", "Allowance"],
      correctIndex: 0,
      explanation: "Profit is the financial gain made when sales revenue exceeds total business costs.",
    },
    {
      id: 5,
      question: "Any money that you spend on things like bus fare, snacks, or airtime is considered an?",
      options: ["Expense", "Income", "Asset", "Investment"],
      correctIndex: 0,
      explanation: "An expense is money paid out to purchase goods, everyday services, or cover running costs.",
    },
    {
      id: 6,
      question: "All the money that a person or a business receives from working or selling products is their?",
      options: ["Income", "Balance", "Wealth", "Debt"],
      correctIndex: 0,
      explanation: "Income encompasses all money earned through wages, sales, investments, or business activities.",
    },
    {
      id: 7,
      question: "If a business spends more money than it earns, it is facing a?",
      options: ["Profit", "Loss", "Gain", "Revenue"],
      correctIndex: 1,
      explanation: "A loss occurs when total expenses are greater than the revenue brought in.",
    },
    {
      id: 8,
      question: "Physical money made of metal is called ___, while physical money made of paper is called ___.",
      options: ["Coins / Notes", "Gold / Silver", "Shillings / Cents", "Tokens / Vouchers"],
      correctIndex: 0,
      explanation: "Coins are minted from metal alloys and notes are printed on durable paper/polymer.",
    },
    {
      id: 9,
      question: "To get money in exchange for your hard work or a service you provide is to:",
      options: ["Spend", "Earn", "Lose", "Give"],
      correctIndex: 1,
      explanation: "Earning means receiving financial compensation in exchange for labor, skills, or goods provided.",
    },
    {
      id: 10,
      question: "The total amount of money left in your bank account or M-PESA after a transaction is your?",
      options: ["Balance", "Price", "Revenue", "Salary"],
      correctIndex: 0,
      explanation: "Your account balance represents the remaining available funds after deposits and withdrawals.",
    },
  ],
};
