import { WordSearchPuzzle, QuizPuzzle, CrosswordPuzzle } from "../types";

export const foundationsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-foundations-ws1",
  title: "Foundations of Money: Puzzle 1",
  topic: "Money Basics",
  theme: "What is Money & Early Trade",
  instruction: "Find the 12 hidden words from the word bank in the letter grid.",
  size: 14,
  words: [
    "Budget",
    "Balance",
    "Loss",
    "Coins",
    "Wealth",
    "Salary",
    "Allowance",
    "Profit",
    "Pocket Money",
    "Expense",
    "Wages",
    "Backpay",
  ],
  grid: [
    ["X", "C", "O", "I", "N", "S", "A", "A", "O", "V", "E", "W", "P", "N"],
    ["A", "R", "E", "D", "T", "L", "E", "L", "N", "U", "L", "S", "R", "Y"],
    ["S", "W", "O", "A", "O", "O", "C", "L", "L", "E", "B", "S", "R", "E"],
    ["C", "G", "A", "E", "C", "S", "C", "O", "Y", "N", "C", "A", "T", "I"],
    ["Y", "S", "N", "G", "T", "S", "S", "W", "B", "E", "L", "C", "I", "C"],
    ["A", "E", "E", "I", "E", "A", "Y", "A", "C", "A", "O", "W", "M", "S"],
    ["P", "A", "X", "X", "V", "S", "K", "N", "S", "A", "O", "L", "T", "N"],
    ["K", "W", "P", "A", "I", "A", "A", "C", "A", "P", "A", "P", "A", "A"],
    ["C", "E", "E", "L", "D", "L", "S", "E", "A", "C", "O", "E", "A", "S"],
    ["A", "A", "N", "Y", "A", "I", "I", "S", "A", "O", "L", "E", "G", "P"],
    ["B", "L", "S", "B", "E", "F", "P", "R", "O", "F", "I", "T", "G", "G"],
    ["E", "T", "E", "P", "O", "C", "K", "E", "T", "M", "O", "N", "E", "Y"],
    ["O", "H", "O", "C", "K", "O", "E", "B", "U", "D", "G", "E", "T", "N"],
    ["L", "I", "T", "B", "L", "O", "S", "B", "A", "E", "B", "P", "W", "N"],
  ],
};

export const foundationsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-foundations-ws2",
  title: "Foundations of Money: Puzzle 2",
  topic: "Money Basics",
  theme: "Value, Exchange & Markets",
  instruction: "Find the 14 words hidden in the puzzle grid.",
  size: 14,
  words: [
    "Trade",
    "Earn",
    "Price",
    "Sale",
    "Revenue",
    "Notes",
    "Income",
    "Markets",
    "Products",
    "Buy",
    "Invest",
    "Sell",
    "Acquire",
    "Cash",
  ],
  grid: [
    ["I", "S", "T", "H", "P", "E", "P", "R", "O", "D", "U", "C", "T", "S"],
    ["N", "N", "E", "M", "A", "R", "K", "E", "T", "S", "E", "E", "P", "L"],
    ["U", "S", "A", "S", "E", "L", "L", "A", "D", "N", "O", "T", "E", "S"],
    ["A", "L", "S", "N", "L", "D", "R", "A", "M", "R", "L", "E", "R", "I"],
    ["C", "T", "A", "R", "T", "N", "R", "A", "S", "V", "R", "E", "C", "N"],
    ["Q", "R", "I", "D", "P", "T", "A", "T", "U", "E", "E", "T", "A", "L"],
    ["U", "E", "U", "N", "S", "T", "E", "S", "E", "C", "E", "P", "I", "P"],
    ["I", "T", "L", "V", "C", "A", "L", "E", "V", "I", "E", "P", "A", "R"],
    ["R", "I", "O", "E", "D", "O", "U", "E", "O", "R", "E", "B", "A", "T"],
    ["E", "N", "S", "R", "L", "N", "M", "T", "S", "P", "P", "U", "O", "O"],
    ["H", "N", "R", "A", "E", "A", "U", "E", "R", "E", "R", "Y", "D", "P"],
    ["S", "E", "C", "V", "R", "A", "S", "Y", "P", "N", "I", "K", "N", "Y"],
    ["A", "M", "E", "H", "N", "R", "V", "U", "T", "S", "E", "V", "N", "I"],
    ["C", "R", "R", "T", "R", "A", "D", "E", "C", "S", "A", "T", "E", "T"],
  ],
};

export const foundationsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "mb-foundations-quiz",
  title: "Foundations of Money: Quiz",
  topic: "Money Basics",
  instruction: "Test your money fundamentals with questions from the official workbook.",
  questions: [
    {
      id: 1,
      question: "When you get money from your parents to spend on small things for yourself, it is called?",
      options: ["Salary", "Pocket Money", "Profit", "Revenue"],
      correctIndex: 1,
      explanation: "Pocket money is a small regular amount given by parents to children for their personal expenses.",
    },
    {
      id: 2,
      question: "A plan that helps you decide how much money you will spend and how much you will save is a?",
      options: ["Backpay", "Market", "Budget", "Sale"],
      correctIndex: 2,
      explanation: "A budget is a personal financial plan that tracks income, spending, and savings goals.",
    },
    {
      id: 3,
      question: "Money that you put aside for the future instead of spending it immediately is known as?",
      options: ["Loss", "Trade", "Expense", "Savings"],
      correctIndex: 3,
      explanation: "Savings represent money set aside for emergencies, future purchases, and long-term security.",
    },
    {
      id: 4,
      question: "When a shopkeeper sells an item for more than they bought it for, the extra money they make is?",
      options: ["Profit", "Allowance", "Price", "Loss"],
      correctIndex: 0,
      explanation: "Profit is the financial gain made when sales revenue exceeds total business costs.",
    },
    {
      id: 5,
      question: "Any money that you spend on things like bus fare, snacks, or airtime is considered an?",
      options: ["Income", "Expense", "Investment", "Asset"],
      correctIndex: 1,
      explanation: "An expense is money paid out to purchase goods, everyday services, or cover running costs.",
    },
    {
      id: 6,
      question: "All the money that a person or a business receives from working or selling products is their?",
      options: ["Balance", "Wealth", "Income", "Debt"],
      correctIndex: 2,
      explanation: "Income encompasses all money earned through wages, sales, investments, or business activities.",
    },
    {
      id: 7,
      question: "If a business spends more money than it earns, it is facing a?",
      options: ["Profit", "Gain", "Revenue", "Loss"],
      correctIndex: 3,
      explanation: "A loss occurs when total expenses are greater than the revenue brought in.",
    },
    {
      id: 8,
      question: "Physical money made of metal is called ___, while physical money made of paper is called ___.",
      options: ["Coins / Notes", "Gold / Silver", "Shillings / Cents", "Tokens / Vouchers"],
      correctIndex: 0,
      explanation: "Coins are minted from metal alloys and notes are printed on durable paper/polymer.",
    },
    {
      id: 9,
      question: "To get money in exchange for your hard work or a service you provide is to:",
      options: ["Lose", "Earn", "Give", "Spend"],
      correctIndex: 1,
      explanation: "Earning means receiving financial compensation in exchange for labor, skills, or goods provided.",
    },
    {
      id: 10,
      question: "The total amount of money left in your bank account or M-PESA after a transaction is your?",
      options: ["Price", "Revenue", "Balance", "Salary"],
      correctIndex: 2,
      explanation: "Your account balance represents the remaining available funds after deposits and withdrawals.",
    },
  ],
};

export const foundationsCrossword1: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-foundations-cw1",
  title: "Foundations of Money: Puzzle 1",
  topic: "Money Basics",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 8,
  cols: 13,
  wordBank: ["Profit", "Wages", "Budget", "Invoice", "Bribe", "Pocket Money", "Savings", "Track"],
  acrossClues: [
    { number: 3, clue: "The small amount of cash parents/guardians sometimes give their kids for snacks or personal use.", answer: "POCKETMONEY", row: 4, col: 2, direction: "across" },
    { number: 4, clue: "A financial plan where you decide how much to spend and save weekly or monthly.", answer: "BUDGET", row: 6, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 1, clue: "The money you put aside in a piggy bank, glass jar or M-Shwari account, for future use.", answer: "SAVINGS", row: 0, col: 10, direction: "down" },
    { number: 2, clue: "Money paid daily or weekly for someone’s casual labour or work.", answer: "WAGES", row: 1, col: 6, direction: "down" },
    { number: 3, clue: "What you make when you sell something for more than the price you paid for it.", answer: "PROFIT", row: 2, col: 9, direction: "down" },
  ],
};

export const foundationsCrossword2: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-foundations-cw2",
  title: "Foundations of Money: Puzzle 2",
  topic: "Money Basics",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 11,
  cols: 8,
  wordBank: ["Payoff", "Backpay", "Expense", "Loss", "Ledger", "Wealth", "Allowance"],
  acrossClues: [
    { number: 3, clue: "The total value of everything you own, including cash and property.", answer: "WEALTH", row: 3, col: 2, direction: "across" },
    { number: 4, clue: "The result of spending more money on a business than you actually make.", answer: "LOSS", row: 5, col: 0, direction: "across" },
    { number: 5, clue: "Money owed to you for work done in the past that wasn't paid on time.", answer: "BACKPAY", row: 7, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 1, clue: "Anything you spend money on, like airtime, bus fare, or snacks.", answer: "EXPENSE", row: 0, col: 3, direction: "down" },
    { number: 2, clue: "A set amount of money given to you regularly, like a monthly stipend by a parent/guardian.", answer: "ALLOWANCE", row: 2, col: 5, direction: "down" },
  ],
};

export const foundationsCrossword3: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-foundations-cw3",
  title: "Foundations of Money: Puzzle 3",
  topic: "Money Basics",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 7,
  cols: 10,
  wordBank: ["Accounts", "Track", "Balance", "Coins", "Books", "Priority", "Record", "Security"],
  acrossClues: [
    { number: 1, clue: "The feeling of safety you have when your money is protected and steady.", answer: "SECURITY", row: 2, col: 2, direction: "across" },
    { number: 3, clue: "The amount of money remaining in your account or wallet right now.", answer: "BALANCE", row: 4, col: 0, direction: "across" },
    { number: 5, clue: "Choosing to buy what you need like school supplies before what you want, like a packet of crisps.", answer: "PRIORITY", row: 6, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 2, clue: "To follow and record every shilling you spend so you don't go broke.", answer: "TRACK", row: 2, col: 8, direction: "down" },
    { number: 4, clue: "Metallic currency, like the 1, 5, 10, or 20 shilling pieces.", answer: "COINS", row: 0, col: 7, direction: "down" },
  ],
};

export const foundationsCrossword4: CrosswordPuzzle = {
  type: "crossword",
  id: "mb-foundations-cw4",
  title: "Foundations of Money: Puzzle 4",
  topic: "Money Basics",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 8,
  cols: 8,
  wordBank: ["Receipt", "Income", "Notes", "Salary", "Cash", "Price", "Pay", "Plan"],
  acrossClues: [
    { number: 1, clue: "The money you earn from working a job or from your business activities.", answer: "INCOME", row: 3, col: 2, direction: "across" },
    { number: 4, clue: "Fixed monthly pay, usually for an individual’s professional work.", answer: "SALARY", row: 5, col: 0, direction: "across" },
    { number: 5, clue: "Physical money in the form of notes and coins.", answer: "CASH", row: 7, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 2, clue: "Paper money; in Kenya, these range from 50 to 1,000 shillings.", answer: "NOTES", row: 0, col: 7, direction: "down" },
    { number: 3, clue: "The amount you verify before buying something like a smokie pasua, a soda or boarding a matatu.", answer: "PRICE", row: 0, col: 4, direction: "down" },
  ],
};
