import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const kenyanImportsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-imports-ws1",
  title: "Kenyan Imports: Puzzle 1",
  topic: "Money Basics",
  theme: "Fuel, Heavy Machinery & Transport",
  instruction: "Find the 14 heavy industrial, energy, and vehicle imports in the grid.",
  size: 14,
  words: [
    "Petrol",
    "Steel",
    "Lubricants",
    "Machinery",
    "Plastics",
    "Gas",
    "Paper",
    "Boda Boda",
    "Aircrafts",
    "Vehicles",
    "Pumps",
    "Tyres",
    "Engines",
    "Iron",
  ],
  grid: [
    ["T", "O", "L", "P", "E", "T", "E", "S", "E", "I", "E", "L", "L", "E"],
    ["S", "S", "A", "S", "T", "S", "D", "P", "N", "A", "L", "A", "P", "B"],
    ["I", "R", "E", "D", "R", "L", "E", "O", "G", "C", "U", "I", "P", "O"],
    ["R", "S", "U", "P", "A", "O", "R", "C", "I", "M", "B", "R", "P", "D"],
    ["O", "T", "L", "O", "R", "T", "E", "P", "N", "R", "R", "C", "P", "A"],
    ["N", "O", "E", "R", "R", "P", "P", "I", "E", "N", "I", "R", "Y", "B"],
    ["S", "E", "C", "E", "I", "E", "L", "E", "S", "V", "C", "A", "R", "O"],
    ["I", "S", "P", "V", "C", "T", "A", "I", "P", "E", "A", "F", "E", "D"],
    ["L", "A", "T", "E", "T", "Y", "S", "U", "M", "H", "N", "T", "N", "A"],
    ["P", "T", "A", "E", "V", "D", "T", "A", "U", "I", "T", "S", "I", "E"],
    ["G", "C", "Y", "R", "E", "S", "I", "U", "P", "C", "S", "N", "H", "S"],
    ["A", "A", "P", "R", "S", "L", "C", "I", "R", "L", "L", "E", "C", "O"],
    ["T", "A", "S", "S", "E", "P", "S", "L", "T", "E", "O", "U", "A", "R"],
    ["P", "P", "A", "R", "C", "S", "S", "L", "S", "S", "R", "I", "M", "A"],
  ],
};

export const kenyanImportsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-imports-ws2",
  title: "Kenyan Imports: Puzzle 2",
  topic: "Money Basics",
  theme: "Consumer Goods, Food & Medicines",
  instruction: "Find the 14 food commodities, electronics, and medical imports.",
  size: 14,
  words: [
    "Furniture",
    "Electronics",
    "Aluminium",
    "Rice",
    "Milk Powder",
    "Confectionery",
    "Fertilizers",
    "Sugars",
    "Wheat",
    "Household Goods",
    "Clothes",
    "Vaccines",
    "Palm Oil",
    "Medicines",
  ],
  grid: [
    ["E", "U", "W", "U", "M", "C", "E", "O", "R", "M", "L", "W", "S", "A"],
    ["E", "E", "C", "F", "I", "L", "L", "I", "T", "S", "K", "H", "D", "N"],
    ["C", "W", "O", "E", "L", "S", "E", "O", "F", "U", "M", "E", "O", "T"],
    ["L", "H", "N", "R", "K", "N", "C", "N", "U", "G", "E", "A", "O", "S"],
    ["O", "A", "F", "T", "P", "M", "T", "M", "R", "A", "D", "T", "G", "A"],
    ["T", "L", "E", "I", "O", "P", "R", "L", "N", "R", "I", "M", "D", "O"],
    ["H", "U", "C", "L", "W", "A", "O", "E", "I", "S", "C", "Z", "L", "V"],
    ["E", "M", "T", "I", "D", "L", "N", "L", "T", "M", "I", "R", "O", "A"],
    ["S", "I", "I", "Z", "E", "M", "I", "S", "U", "E", "N", "I", "H", "C"],
    ["E", "N", "O", "E", "R", "O", "C", "E", "R", "C", "E", "O", "E", "C"],
    ["E", "I", "N", "R", "A", "I", "S", "C", "E", "O", "S", "G", "S", "I"],
    ["R", "U", "E", "S", "S", "L", "M", "I", "E", "A", "N", "Z", "U", "N"],
    ["E", "M", "R", "E", "C", "E", "L", "R", "R", "O", "R", "N", "O", "E"],
    ["A", "C", "Y", "C", "A", "C", "M", "E", "N", "U", "I", "G", "H", "S"],
  ],
};

export const kenyanImportsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "mb-imports-quiz",
  title: "Kenyan Imports: Quiz",
  topic: "Money Basics",
  instruction: "Test your understanding of Kenya's major trade partners, commodities, and ports.",
  questions: [
    {
      id: 1,
      question: "What is Kenya's single most expensive import, used to power cars, buses, and factories?",
      options: ["Solar Panels", "Refined Petroleum", "Bottled Water", "Wood"],
      correctIndex: 1,
      explanation: "Petroleum fuel (petrol, diesel, jet fuel) accounts for the largest share of Kenya's national import bill.",
    },
    {
      id: 2,
      question: "Which country is currently Kenya's top trading partner for imports, providing many of our electronics and clothes?",
      options: ["Brazil", "China", "Australia", "Canada"],
      correctIndex: 1,
      explanation: "China is Kenya's leading source of imported manufactured goods, machinery, smartphones, and infrastructure materials.",
    },
    {
      id: 3,
      question: "Kenya imports a lot of this golden oil, used for cooking and found in many snacks, mainly from Malaysia and Indonesia.",
      options: ["Olive Oil", "Palm Oil", "Coconut Oil", "Engine Oil"],
      correctIndex: 1,
      explanation: "Crude and refined palm oil is imported in bulk to make cooking oils, margarine, and household soaps.",
    },
    {
      id: 4,
      question: "Which essential food grain does Kenya import in large quantities to make flour for bread and mandazi?",
      options: ["Rice", "Wheat", "Barley", "Oats"],
      correctIndex: 1,
      explanation: "Kenya imports over 70% of its national wheat requirements from countries like Russia, Ukraine, and Canada.",
    },
    {
      id: 5,
      question: "To help farmers grow healthy crops like maize and tea, Kenya imports large amounts of what?",
      options: ["Seeds", "Fertilizers", "Tractors", "Rainwater"],
      correctIndex: 1,
      explanation: "Chemical fertilizers (like DAP and CAN) are vital inputs imported to boost crop yields.",
    },
    {
      id: 6,
      question: "When a country like Kenya buys more goods from abroad than it sells to other countries, it has a trade?",
      options: ["Profit", "Deficit", "Surplus", "Discount"],
      correctIndex: 1,
      explanation: "A trade deficit means total spending on imports exceeds export earnings.",
    },
    {
      id: 7,
      question: "Kenya's construction sector relies on importing large quantities of this strong metal for building skyscrapers and bridges.",
      options: ["Gold", "Aluminum", "Iron and Steel", "Copper"],
      correctIndex: 2,
      explanation: "Iron rods, steel coils, and heavy construction beams are key industrial imports.",
    },
    {
      id: 8,
      question: "Which of these is a capital good i.e. machinery used to make other things that Kenya imports to grow its industry?",
      options: ["Chocolate", "Industrial Machinery", "Video Games", "Flowers"],
      correctIndex: 1,
      explanation: "Capital goods are tools and factory equipment used to produce consumer goods locally.",
    },
    {
      id: 9,
      question: "Most of Kenya's heavy imports arrive by sea. Which major Kenyan port handles the majority of these goods?",
      options: ["Kisumu", "Mombasa", "Nakuru", "Nairobi"],
      correctIndex: 1,
      explanation: "The Port of Mombasa is East Africa's largest gateway for containerized shipping and bulk cargo.",
    },
    {
      id: 10,
      question: "Besides China, which other Asian neighbor is a major source of Kenya's pharmaceutical medicine and industrial imports?",
      options: ["India", "Russia", "Mexico", "Egypt"],
      correctIndex: 0,
      explanation: "India produces a large percentage of affordable generic pharmaceuticals and medical supplies imported by Kenya.",
    },
  ],
};
