import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const kenyanExportsWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "mb-exports-ws1",
  title: "Kenyan Exports: Puzzle",
  topic: "Money Basics",
  theme: "Agricultural & Manufactured Exports",
  instruction: "Find the 17 major goods that Kenya exports to global markets.",
  size: 14,
  words: [
    "Snow Peas",
    "Beads",
    "Macadamia Nuts",
    "Coffee",
    "Mutton",
    "Sisal",
    "Carnations",
    "French Beans",
    "Roses",
    "Pineapple",
    "Tobacco",
    "Goat",
    "Mangoes",
    "Leather",
    "Avocados",
    "Beef",
    "Tea",
  ],
  grid: [
    ["E", "F", "B", "E", "O", "S", "P", "O", "E", "S", "B", "E", "E", "F"],
    ["G", "R", "M", "S", "B", "E", "A", "A", "A", "I", "L", "A", "N", "S"],
    ["F", "E", "A", "S", "C", "F", "N", "E", "E", "P", "E", "R", "T", "I"],
    ["S", "N", "M", "A", "E", "I", "P", "M", "P", "S", "B", "U", "O", "I"],
    ["N", "C", "T", "O", "O", "W", "M", "A", "O", "A", "N", "T", "T", "F"],
    ["O", "H", "E", "T", "O", "C", "E", "D", "E", "A", "S", "O", "A", "O"],
    ["I", "B", "A", "N", "S", "N", "A", "R", "I", "S", "E", "B", "G", "O"],
    ["T", "E", "S", "N", "I", "C", "E", "M", "T", "S", "O", "A", "L", "M"],
    ["A", "A", "I", "P", "O", "E", "A", "T", "S", "E", "G", "C", "B", "U"],
    ["N", "N", "S", "V", "D", "D", "A", "D", "H", "S", "N", "C", "A", "T"],
    ["R", "S", "A", "E", "A", "O", "A", "O", "A", "O", "A", "O", "S", "T"],
    ["A", "O", "L", "C", "G", "E", "C", "A", "A", "R", "M", "C", "O", "O"],
    ["C", "T", "A", "T", "B", "M", "R", "E", "H", "T", "A", "E", "L", "N"],
    ["T", "M", "C", "O", "F", "F", "E", "E", "E", "E", "S", "F", "F", "S"],
  ],
};

export const kenyanExportsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "mb-exports-quiz",
  title: "Kenyan Exports: Quiz",
  topic: "Money Basics",
  instruction: "Explore Kenya's foreign trade, tea, cut flowers, and horticultural exports.",
  questions: [
    {
      id: 1,
      question: "Kenya is one of the world's leading exporters of which refreshing drink, mostly grown in places like Kericho and Limuru?",
      options: ["Pineapple juice", "Tea", "Coffee", "Mangoes"],
      correctIndex: 1,
      explanation: "Kenyan black tea is famous worldwide and is the country's leading agricultural export earner.",
    },
    {
      id: 2,
      question: "Which beautiful flower is a major export for Kenya, often sent to Europe for Valentine's Day?",
      options: ["Lilies", "Sunflowers", "Roses", "Daisies"],
      correctIndex: 2,
      explanation: "Lake Naivasha and Mount Kenya region produce world-class cut roses exported daily to Europe.",
    },
    {
      id: 3,
      question: "Many people around the world start their morning with a cup of high-quality Kenyan ___ known for its rich aroma.",
      options: ["Milk", "Tea", "Cocoa", "Coffee"],
      correctIndex: 3,
      explanation: "Kenyan Arabica coffee (AA grade) is prized globally by baristas for its intense berry flavor.",
    },
    {
      id: 4,
      question: "Which creamy green fruit has become a massive export for Kenya lately, often called 'Green Gold'?",
      options: ["Avocados", "Mangoes", "Pineapples", "Apples"],
      correctIndex: 0,
      explanation: "Hass avocados are a booming export crop earning millions of dollars for Kenyan farmers.",
    },
    {
      id: 5,
      question: "Kenya exports a lot of crunchy nuts that are often found in expensive chocolates. These are?",
      options: ["Groundnuts", "Macadamia Nuts", "Walnuts", "Cashew nuts"],
      correctIndex: 1,
      explanation: "Kenya is one of the top global producers and exporters of high-grade macadamia nuts.",
    },
    {
      id: 6,
      question: "Which of these is a popular 'French' vegetable that Kenyan farmers grow and export in large quantities?",
      options: ["Cabbage", "French Fries", "French Beans", "Carrots"],
      correctIndex: 2,
      explanation: "Extra-fine French green beans are harvested daily and flown directly to supermarkets abroad.",
    },
    {
      id: 7,
      question: "Thika is very famous in Kenya for the large-scale growth and export of which prickly fruit?",
      options: ["Snow Peas", "Avocados", "Mangoes", "Pineapples"],
      correctIndex: 3,
      explanation: "Del Monte's vast plantations in Thika produce pineapples and canned juices for export worldwide.",
    },
    {
      id: 8,
      question: "Which of these is a strong fibre used to make ropes and baskets, famously grown in large estates in Taita Taveta?",
      options: ["Sisal", "Cotton", "Tobacco", "Wool"],
      correctIndex: 0,
      explanation: "Sisal fibre is processed and exported for making industrial ropes, mats, and traditional kiondos.",
    },
    {
      id: 9,
      question: "When Kenya exports animal skins to be made into shoes, belts, and bags, the product is called:",
      options: ["Sisal", "Leather", "Beef", "Silk"],
      correctIndex: 1,
      explanation: "Tanned hides and finished leather products are a key manufactured export.",
    },
    {
      id: 10,
      question: "Maasai culture contributes to exports through beautiful, colourful handmade jewellery made of?",
      options: ["Silver", "Gold", "Beads", "Diamonds"],
      correctIndex: 2,
      explanation: "Traditional Maasai beadwork and jewellery are sold as cultural exports and tourist merchandise.",
    },
  ],
};
