import { WordSearchPuzzle } from "../types";

export const africaExportsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-africa-exports-ws1",
  title: "Africa’s Exports: Puzzle 1",
  topic: "Global Money & Trade",
  theme: "Africa’s Natural Resources & Critical Minerals",
  instruction: "Find the 10 mineral and metal exports hidden in the grid.",
  size: 14,
  words: [
    "Copper",
    "Manganese",
    "Platinum",
    "Chromium",
    "Diamonds",
    "Gold",
    "Bauxite",
    "Cobalt",
    "Tantalum",
    "Iron Ore",
  ],
  grid: [
    ["V", "D", "I", "A", "M", "O", "N", "D", "S", "I", "L", "A", "I", "R"],
    ["N", "V", "R", "B", "E", "M", "H", "M", "A", "X", "A", "Z", "X", "C"],
    ["Q", "V", "K", "L", "R", "U", "X", "A", "A", "Q", "T", "N", "E", "O"],
    ["A", "E", "U", "T", "N", "L", "H", "N", "F", "N", "J", "J", "T", "B"],
    ["H", "R", "Y", "G", "D", "A", "I", "G", "V", "Z", "O", "O", "I", "A"],
    ["M", "O", "F", "V", "L", "T", "C", "A", "D", "R", "G", "R", "X", "L"],
    ["U", "N", "L", "M", "W", "N", "O", "N", "G", "T", "N", "G", "U", "T"],
    ["I", "O", "N", "U", "D", "A", "P", "E", "C", "D", "V", "O", "A", "J"],
    ["M", "R", "E", "N", "E", "T", "P", "S", "M", "W", "Y", "L", "B", "M"],
    ["O", "I", "P", "I", "D", "T", "E", "E", "X", "P", "E", "D", "B", "U"],
    ["R", "C", "M", "T", "S", "U", "R", "X", "W", "U", "R", "H", "O", "E"],
    ["H", "A", "E", "A", "H", "K", "N", "P", "B", "Q", "U", "D", "B", "B"],
    ["C", "M", "E", "L", "C", "R", "C", "Y", "A", "L", "B", "C", "T", "L"],
    ["R", "F", "V", "P", "R", "C", "I", "F", "O", "B", "O", "K", "X", "I"],
  ],
};

export const africaExportsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-africa-exports-ws2",
  title: "Africa’s Exports: Puzzle 2",
  topic: "Global Money & Trade",
  theme: "Energy, Cotton & Cash Crops",
  instruction: "Find the 10 energy and crop exports hidden in the grid.",
  size: 14,
  words: [
    "Coal",
    "Coffee",
    "Natural Gas",
    "Crude Oil",
    "Uranium",
    "Cotton",
    "Tea",
    "Cashew Nuts",
    "Coltan",
    "Cocoa",
  ],
  grid: [
    ["V", "U", "R", "A", "N", "I", "U", "M", "C", "I", "L", "A", "I", "R"],
    ["C", "N", "V", "R", "B", "E", "H", "N", "A", "O", "X", "A", "Z", "X"],
    ["O", "Q", "V", "K", "L", "R", "X", "A", "A", "Q", "T", "T", "N", "A"],
    ["A", "U", "T", "N", "H", "E", "F", "T", "N", "J", "J", "T", "H", "Y"],
    ["L", "N", "G", "S", "D", "E", "I", "U", "V", "Z", "O", "O", "O", "F"],
    ["L", "A", "V", "T", "L", "F", "C", "R", "D", "R", "G", "R", "L", "N"],
    ["I", "T", "W", "U", "G", "F", "O", "A", "T", "N", "N", "T", "D", "C"],
    ["O", "L", "D", "N", "V", "O", "C", "L", "J", "E", "E", "E", "M", "W"],
    ["E", "O", "Y", "W", "M", "C", "O", "G", "P", "D", "T", "A", "X", "P"],
    ["D", "C", "E", "E", "B", "U", "A", "A", "C", "M", "S", "U", "X", "W"],
    ["U", "U", "R", "H", "H", "O", "E", "S", "A", "E", "H", "K", "N", "P"],
    ["R", "B", "Q", "S", "U", "D", "B", "B", "M", "E", "C", "R", "C", "Y"],
    ["C", "A", "L", "A", "B", "C", "T", "L", "R", "F", "V", "R", "C", "I"],
    ["F", "O", "B", "C", "O", "K", "X", "I", "T", "W", "F", "K", "B", "J"],
  ],
};

export const africaExportsWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-africa-exports-ws3",
  title: "Africa’s Exports: Puzzle 3",
  topic: "Global Money & Trade",
  theme: "Food, Flowers, Timber & Tourism",
  instruction: "Find the 11 agricultural and tourism exports hidden in the grid.",
  size: 14,
  words: [
    "Spices",
    "Fish",
    "Vanilla",
    "Shea Butter",
    "Flowers",
    "Tanzanite",
    "Grapes",
    "Citrus Fruits",
    "Timber",
    "Tourism",
    "Avocados",
  ],
  grid: [
    ["H", "A", "V", "O", "C", "A", "D", "O", "S", "J", "Z", "N", "K", "E"],
    ["X", "Z", "S", "Z", "O", "A", "K", "C", "F", "E", "G", "P", "W", "G"],
    ["J", "P", "D", "A", "U", "A", "O", "I", "I", "D", "P", "J", "S", "R"],
    ["P", "M", "H", "J", "Z", "L", "X", "T", "S", "B", "R", "D", "R", "A"],
    ["E", "S", "O", "R", "V", "L", "G", "R", "H", "E", "H", "D", "E", "P"],
    ["T", "I", "O", "E", "W", "I", "S", "U", "P", "X", "X", "S", "W", "E"],
    ["I", "R", "H", "T", "W", "N", "P", "S", "L", "O", "N", "T", "O", "S"],
    ["N", "U", "D", "T", "J", "A", "I", "F", "B", "I", "L", "I", "L", "P"],
    ["A", "O", "R", "U", "N", "V", "C", "R", "P", "I", "Z", "M", "F", "T"],
    ["Z", "T", "U", "B", "F", "I", "E", "U", "Z", "T", "G", "B", "R", "H"],
    ["N", "A", "H", "A", "Z", "J", "S", "I", "S", "Z", "W", "E", "A", "X"],
    ["A", "H", "T", "E", "T", "B", "M", "T", "G", "N", "E", "R", "B", "Y"],
    ["T", "T", "Z", "H", "N", "P", "S", "S", "N", "W", "G", "O", "W", "Z"],
    ["F", "Z", "C", "S", "M", "M", "E", "I", "I", "O", "S", "F", "E", "R"],
  ],
};
