import { CryptogramPuzzle, QuizPuzzle, ActivityPuzzle, WordSearchPuzzle } from "../types";
import { cryptoItem } from "../crypto";

export const currenciesAfricaCryptogram: CryptogramPuzzle = {
  type: "cryptogram",
  id: "gm-africa-crypto",
  title: "Currencies of Africa: A1Z26 Cryptogram",
  topic: "Global Money & Trade",
  instruction: "Decode African currency names with the A1Z26 cipher (A=1 … Z=26).",
  cipherType: "A1Z26",
  items: [
    cryptoItem(1, "Used in Kenya, Uganda, and Tanzania, this currency shares its name with an old British coin.", "SHILLING"),
    cryptoItem(2, "In Botswana, the name of this currency also means rain, a precious resource in the Kalahari Desert.", "PULA"),
    cryptoItem(3, "Its name comes from the Ghanaian word for cowrie shell, used as money in West Africa for centuries.", "CEDI"),
    cryptoItem(4, "Meaning dawn in the local language, this currency symbolizes a New Dawn of Freedom for Zambia and Malawi.", "KWACHA"),
    cryptoItem(5, "The official currency of Ethiopia; its name literally means silver in Amharic.", "BIRR"),
    cryptoItem(6, "This colonial-legacy currency is still used by 14 African nations in the CFA zone.", "FRANC"),
    cryptoItem(7, "Used in Morocco, this currency gets its name from the ancient Greek drachma.", "DIRHAM"),
    cryptoItem(8, "The unique currency of Madagascar, one of the few non-decimal currencies in the world.", "ARIARY"),
    cryptoItem(9, "Used in Mozambique, its name comes from an Arabic unit of weight, mithqal, once used for gold.", "METICAL"),
    cryptoItem(10, "The currency of The Gambia, the smallest country on mainland Africa.", "DALASI"),
    cryptoItem(11, "The official currency of the Kingdom of Eswatini, often used with the South African Rand.", "LILANGENI"),
    cryptoItem(12, "Derived from the Witwatersrand gold mines, this 4-letter currency is used in South Africa.", "RAND"),
    cryptoItem(13, "The official currency of Africa’s most populous country, Nigeria.", "NAIRA"),
    cryptoItem(14, "A common name for money in Tunisia and Libya, tracing back to the Roman denarius.", "DINAR"),
    cryptoItem(15, "Named after a major river in Angola; the name also means first in Swahili.", "KWANZA"),
    cryptoItem(16, "Named after a town that was a key site during Eritrea’s war of independence.", "NAKFA"),
    cryptoItem(17, "Directly named after the Lion Mountains that give Sierra Leone its name.", "LEONE"),
    cryptoItem(18, "Short for Zimbabwe Gold, one of Africa’s newest currency names.", "ZIG"),
    cryptoItem(19, "Used in Mauritania; the name comes from an Arabic word meaning ounce.", "OUGUIYA"),
    cryptoItem(20, "The currency of São Tomé and Príncipe; its name is Portuguese for fold.", "DOBRA"),
  ],
};

export const currenciesAfricaCryptoQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-africa-crypto-quiz",
  title: "Currencies of Africa: Cryptogram Quiz",
  topic: "Global Money & Trade",
  instruction: "Match African currency names to their meanings and countries.",
  questions: [
    { id: 1, question: "Which currency’s name literally translates to rain, reflecting its status as a precious resource in the Kalahari Desert?", options: ["Rand", "Pula", "Birr", "Kwacha"], correctIndex: 1, explanation: "Pula means rain in Setswana and is Botswana’s currency." },
    { id: 2, question: "The Cedi used in Ghana gets its name from an Akan word meaning what?", options: ["Gold nugget", "Silver coin", "Small shell", "Rising sun"], correctIndex: 2, explanation: "Cedi comes from a cowrie-shell word used as money in West Africa." },
    { id: 3, question: "If you are using the Kwacha to buy snacks, which two countries might you be visiting?", options: ["Kenya and Uganda", "Morocco and Tunisia", "Nigeria and Ghana", "Zambia and Malawi"], correctIndex: 3, explanation: "Both Zambia and Malawi use the kwacha." },
    { id: 4, question: "Which currency is named after the gold-rich ridge near Johannesburg, South Africa?", options: ["Rand", "Naira", "Leone", "Metical"], correctIndex: 0, explanation: "Rand comes from the Witwatersrand gold reef." },
    { id: 5, question: "How many African countries still use a version of the CFA Franc as their official currency?", options: ["21", "14", "6", "10"], correctIndex: 1, explanation: "Fourteen African nations still use the CFA franc." },
    { id: 6, question: "Which of these currencies is used in North African countries like Tunisia and Libya, with roots tracing back to a Roman coin?", options: ["Dobra", "Dirham", "Dinar", "Ouguiya"], correctIndex: 2, explanation: "Dinar comes from the Roman denarius." },
    { id: 7, question: "The Birr is the official currency of which East African nation?", options: ["Somalia", "Djibouti", "Eritrea", "Ethiopia"], correctIndex: 3, explanation: "Ethiopia uses the birr, which means silver in Amharic." },
    { id: 8, question: "Which currency is named after a major river and also means first in Swahili?", options: ["Kwanza", "Dalasi", "Nakfa", "Shilling"], correctIndex: 0, explanation: "Angola’s kwanza is named after the Kwanza River." },
    { id: 9, question: "In 2024, Zimbabwe introduced a new gold-backed currency. What is its name?", options: ["Rhino", "ZiG", "Gold-Birr", "Zim-Dollar"], correctIndex: 1, explanation: "ZiG stands for Zimbabwe Gold." },
    { id: 10, question: "Which island nation uses the Ariary, one of the only non-decimal currencies in the world?", options: ["Seychelles", "Mauritius", "Madagascar", "Comoros"], correctIndex: 2, explanation: "Madagascar uses the ariary." },
  ],
};

export const afroNoteActivity: ActivityPuzzle = {
  type: "activity",
  id: "gm-afro-note-activity",
  title: "Design a 100 Afro Note",
  topic: "Global Money & Trade",
  subtype: "home_treasure_hunt",
  instruction: "The African Union has discussed a continent-wide currency, sometimes nicknamed the Afro. Design a 100 Afro note.",
  config: {
    steps: [
      { step: 1, title: "Pick a Pan-African symbol", description: "Include one Pan-African symbol such as the African Union logo or a unity emblem." },
      { step: 2, title: "Add a famous landmark", description: "Feature one famous African landmark such as Mt. Kilimanjaro or the Pyramids of Giza." },
      { step: 3, title: "Add a security feature", description: "Include one security feature such as a hologram, watermark, or tactile bars so the note is hard to copy." },
    ],
  },
};

export const currenciesAmericaCryptogram: CryptogramPuzzle = {
  type: "cryptogram",
  id: "gm-america-crypto",
  title: "Currencies of the Americas: A1Z26 Cryptogram",
  topic: "Global Money & Trade",
  instruction: "Decode North, Central, and South American currencies with A1Z26.",
  cipherType: "A1Z26",
  items: [
    cryptoItem(1, "Which sunny currency will Liam need to buy a souvenir llama at Machu Picchu in Peru?", "SOL"),
    cryptoItem(2, "Which currency would George use to buy a steak dinner in Buenos Aires or a taco in Mexico City?", "PESO"),
    cryptoItem(3, "Which currency would Sophia carry while visiting Angel Falls in Venezuela?", "BOLIVAR"),
    cryptoItem(4, "What currency would Noah use to pay for tereré in Asunción, Paraguay?", "GUARANI"),
    cryptoItem(5, "What currency would Isabella use on the way to the Uyuni Salt Flats in Bolivia?", "BOLIVIANO"),
    cryptoItem(6, "Which European currency would Charlotte need to buy a baguette in Cayenne, French Guiana?", "EURO"),
    cryptoItem(7, "What currency would Oliver need for a coxinha from a street vendor in Brazil?", "REAL"),
    cryptoItem(8, "What currency would Mia need to buy Canelazo in Ecuador?", "DOLLAR"),
    cryptoItem(9, "What currency would Harry need while watching the Northern Lights in Greenland?", "KRONE"),
    cryptoItem(10, "Which currency would Emily spend on fish and chips in the Falkland Islands?", "POUND"),
    cryptoItem(11, "What currency would Jack hand over for a hot dog at a Yankees game or maple syrup in Toronto?", "DOLLAR"),
    cryptoItem(12, "Which bird-brained currency would Thomas use at Mayan ruins in Guatemala?", "QUETZAL"),
    cryptoItem(13, "What currency would Chloe spend on a surf lesson in Costa Rica?", "COLON"),
    cryptoItem(14, "What currency would Oliver use for a boat ride to the Bay Islands in Honduras?", "LEMPIRA"),
    cryptoItem(15, "What currency would Sarah use near the craters of Nicaragua?", "CORDOBA"),
    cryptoItem(16, "Which coin would Harry use while watching ships pass through the Panama Canal?", "BALBOA"),
    cryptoItem(17, "What currency would Lily spend on griot in Port-au-Prince, Haiti?", "GOURDE"),
    cryptoItem(18, "Which currency would Jack need for a Dutch-style snack in Aruba?", "FLORIN"),
  ],
};

export const currenciesAmericaQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-america-quiz",
  title: "Currencies of the Americas: Quiz",
  topic: "Global Money & Trade",
  instruction: "Test South and Central American currency facts from the puzzle book.",
  questions: [
    { id: 1, question: "If you are in Peru and taking photos near the high Andes, what currency are you likely carrying?", options: ["Peso", "Boliviano", "Real", "Sol"], correctIndex: 3, explanation: "Peru uses the sol, which means sun in Spanish." },
    { id: 2, question: "Which currency shares its name with a vibrant, long-tailed tropical bird found in Guatemala?", options: ["Quetzal", "Balboa", "Lempira", "Gourde"], correctIndex: 0, explanation: "Guatemala’s quetzal is named after the bird." },
    { id: 3, question: "In which South American territory would you surprisingly need euros to buy a baguette?", options: ["Argentina", "French Guiana", "Suriname", "Brazil"], correctIndex: 1, explanation: "French Guiana is part of France and uses the euro." },
    { id: 4, question: "Which currency’s name literally translates to sun in Spanish and is used in Peru?", options: ["Cordoba", "Colon", "Sol", "Real"], correctIndex: 2, explanation: "Sol means sun." },
    { id: 5, question: "While watching a soccer match in Rio de Janeiro, you would use this royal-sounding currency.", options: ["Euro", "Dollar", "Peso", "Real"], correctIndex: 3, explanation: "Brazil uses the real." },
  ],
};

export const worldCupTicketActivity: ActivityPuzzle = {
  type: "activity",
  id: "gm-world-cup-ticket-activity",
  title: "The Three-Nation Ticket Budget",
  topic: "Global Money & Trade",
  subtype: "home_treasure_hunt",
  instruction: "The 2026 World Cup is hosted across Mexico, the USA, and Canada. Plan Category 3 tickets in US dollars.",
  config: {
    steps: [
      { step: 1, title: "Pick three matches", description: "Choose one match you would want to see in Mexico, one in the USA, and one in Canada." },
      { step: 2, title: "Add the ticket prices", description: "Use the book’s sample: Mexico City opening match $1,020 USD. Add two more Category 3 prices and total them." },
      { step: 3, title: "Convert to Kenya shillings", description: "Convert the USD total into KSh and decide whether the trip still fits a family travel budget." },
    ],
  },
};

export const currenciesEuropeCryptogram: CryptogramPuzzle = {
  type: "cryptogram",
  id: "gm-europe-crypto",
  title: "Currencies of Europe: A1Z26 Cryptogram",
  topic: "Global Money & Trade",
  instruction: "Decode European and nearby currencies with A1Z26.",
  cipherType: "A1Z26",
  items: [
    cryptoItem(1, "Amina counts coins for a croissant in Paris or a pretzel in Berlin. What currency is she holding?", "EURO"),
    cryptoItem(2, "What local currency will Jason need for a red double-decker bus in London?", "POUNDSTERLING"),
    cryptoItem(3, "When visiting Switzerland, what local currency will Nia need to buy a luxury watch in Zurich?", "FRANC"),
    cryptoItem(4, "What local currency will James need for Legoland in Denmark or fjords in Norway?", "KRONE"),
    cryptoItem(5, "What local currency will Akeyo need for the ABBA Museum in Sweden or the Blue Lagoon in Iceland?", "KRONA"),
    cryptoItem(6, "What local currency will Richard need for a pierogi dinner in Warsaw, Poland?", "ZLOTY"),
    cryptoItem(7, "What currency will Mary need for a Trdelník pastry in Prague?", "KORUNA"),
    cryptoItem(8, "What currency will Micah need for spicy goulash in Budapest?", "FORINT"),
    cryptoItem(9, "What currency will Oluchi need for a tour of Dracula’s Castle in Romania?", "LEU"),
    cryptoItem(10, "What currency will Joyce need to buy borscht in Kyiv, Ukraine?", "HRYVNIA"),
    cryptoItem(11, "What local currency will Zola need in Russia or Belarus?", "RUBLE"),
    cryptoItem(12, "What local currency will Khadija need for baklava in Istanbul?", "LIRA"),
    cryptoItem(13, "What currency will Josh need at a market in Belgrade, Serbia?", "DINAR"),
    cryptoItem(14, "What currency will Emmanuel need for a beach day in Durrës, Albania?", "LEK"),
    cryptoItem(15, "What currency will Asha need for coffee in the streets of Sarajevo?", "MARK"),
    cryptoItem(16, "What currency will Charles need in Skopje, North Macedonia?", "DENAR"),
    cryptoItem(17, "What currency will Rashid need for khachapuri in Tbilisi, Georgia?", "LARI"),
    cryptoItem(18, "What local currency will Linda need for a view of Mount Ararat in Yerevan, Armenia?", "DRAM"),
    cryptoItem(19, "What local currency will Joseph need in Baku, Azerbaijan?", "MANAT"),
    cryptoItem(20, "What currency will Max need to visit the towers of Astana, Kazakhstan?", "TENGE"),
    cryptoItem(21, "What currency will John need for a photo with the monkeys on the Rock of Gibraltar?", "POUND"),
    cryptoItem(22, "What currency will Clara need to pay for a motorcycle ride on the Isle of Man?", "MANXPOUND"),
  ],
};

export const currenciesEuropeQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-europe-quiz",
  title: "Currencies of Europe: Quiz",
  topic: "Global Money & Trade",
  instruction: "Answer European currency questions from the puzzle book.",
  questions: [
    { id: 1, question: "If you're grabbing spicy goulash in Budapest, what are you paying with?", options: ["Forint", "Leu", "Koruna", "Złoty"], correctIndex: 0, explanation: "Hungary uses the forint." },
    { id: 2, question: "You’re headed to the ABBA Museum in Stockholm. Which crown do you need?", options: ["Króna", "Krona", "Krone", "Koruna"], correctIndex: 1, explanation: "Sweden uses the krona." },
    { id: 3, question: "To see the futuristic towers of Astana, Kazakhstan, you'll need?", options: ["Manat", "Dram", "Tenge", "Lari"], correctIndex: 2, explanation: "Kazakhstan uses the tenge." },
    { id: 4, question: "You're visiting Dracula's Castle in Romania. What is the local currency called?", options: ["Lev", "Dinar", "Lek", "Leu"], correctIndex: 3, explanation: "Romania uses the leu." },
    { id: 5, question: "If you're taking a selfie with the famous monkeys on the Rock of Gibraltar, you'll specifically use the?", options: ["Gibraltar Pound", "Euro", "Moroccan Dirham", "Spanish Peseta"], correctIndex: 0, explanation: "Gibraltar uses the Gibraltar pound." },
    { id: 6, question: "Which currency would you use to buy khachapuri in Tbilisi, Georgia?", options: ["Ruble", "Lari", "Manat", "Dram"], correctIndex: 1, explanation: "Georgia uses the lari." },
    { id: 7, question: "You want to visit the home of LEGO in Billund, Denmark. You should bring?", options: ["Euros", "Swiss Francs", "Danish Krone", "Swedish Krona"], correctIndex: 2, explanation: "Denmark uses the krone." },
    { id: 8, question: "Which of these is the currency used in the historic streets of Sarajevo?", options: ["Denar", "Lek", "Dinar", "Mark"], correctIndex: 3, explanation: "Bosnia and Herzegovina uses the convertible mark." },
  ],
};

export const europeDailyCapActivity: ActivityPuzzle = {
  type: "activity",
  id: "gm-europe-daily-cap",
  title: "The Daily Cap Calculation",
  topic: "Global Money & Trade",
  subtype: "home_treasure_hunt",
  instruction: "Plan a 10-day tour of Madrid, Lisbon, Berlin, and Paris with a daily spending cap.",
  config: {
    steps: [
      { step: 1, title: "Set a daily cap", description: "Choose a daily limit for food and museum entries, for example €50." },
      { step: 2, title: "Multiply for 10 days", description: "Multiply the daily cap by 10, then add rough transport and accommodation." },
      { step: 3, title: "Convert to KSh", description: "Convert the euro total into Kenya shillings so you can see the real family cost." },
    ],
  },
};

export const currenciesMiddleEastCryptogram: CryptogramPuzzle = {
  type: "cryptogram",
  id: "gm-middle-east-crypto",
  title: "Currencies of the Middle East: A1Z26 Cryptogram",
  topic: "Global Money & Trade",
  instruction: "Decode Middle Eastern currencies with A1Z26.",
  cipherType: "A1Z26",
  items: [
    cryptoItem(1, "Kuwait’s version of this currency is often the highest-valued in the world. A version is also used in Bahrain, Iraq, and Jordan.", "DINAR"),
    cryptoItem(2, "What you’ll need to buy a soda in Saudi Arabia or Qatar.", "RIYAL"),
    cryptoItem(3, "Just one letter different from its neighbour’s currency; also used in Oman, Yemen, and Iran.", "RIAL"),
    cryptoItem(4, "What you’ll spend visiting the pyramids in Cairo or the markets of Beirut and Damascus.", "POUND"),
    cryptoItem(5, "The currency used to buy snacks in Jerusalem and Ramallah.", "SHEKEL"),
    cryptoItem(6, "If you're headed to Turkey, you’ll need plenty of these in Istanbul or Ankara.", "LIRA"),
    cryptoItem(7, "The official currency for a shopping spree in Dubai or Abu Dhabi.", "DIRHAM"),
    cryptoItem(8, "Even though it is in the Middle East region, Cyprus uses this major European currency.", "EURO"),
  ],
};

export const currenciesMiddleEastQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-middle-east-quiz",
  title: "Currencies of the Middle East: Quiz",
  topic: "Global Money & Trade",
  instruction: "Answer Middle East currency questions from the puzzle book.",
  questions: [
    { id: 1, question: "If you are on a shopping spree in Dubai, which currency are you using?", options: ["Dirham", "Dinar", "Rial", "Shekel"], correctIndex: 0, explanation: "The UAE uses the dirham." },
    { id: 2, question: "Which currency is a heavy hitter because its Kuwaiti version is often the highest-valued in the world?", options: ["Pound", "Dinar", "Riyal", "Lira"], correctIndex: 1, explanation: "The Kuwaiti dinar is among the world’s strongest currencies." },
    { id: 3, question: "In which of these cities would you spend the New Shekel?", options: ["Doha", "Muscat", "Jerusalem", "Baghdad"], correctIndex: 2, explanation: "Israel and Palestine use the new shekel." },
    { id: 4, question: "Which two countries use the riyal spelled with a y?", options: ["Syria and Lebanon", "Iran and Oman", "Yemen and Egypt", "Saudi Arabia and Qatar"], correctIndex: 3, explanation: "Saudi Arabia and Qatar use the riyal." },
    { id: 5, question: "Which currency would you use if you were visiting a bazaar in Ankara, Turkey?", options: ["Lira", "Dinar", "Rial", "Euro"], correctIndex: 0, explanation: "Turkey uses the lira." },
  ],
};

export const currenciesAsiaCryptogram: CryptogramPuzzle = {
  type: "cryptogram",
  id: "gm-asia-crypto",
  title: "Currencies of Asia: A1Z26 Cryptogram",
  topic: "Global Money & Trade",
  instruction: "Decode Asian currencies with A1Z26.",
  cipherType: "A1Z26",
  items: [
    cryptoItem(1, "What local currency will Naomi need for ramen and a Pikachu plushie in Tokyo, Japan?", "YEN"),
    cryptoItem(2, "What currency will Michael use for tteokbokki in Seoul, South Korea?", "WON"),
    cryptoItem(3, "What local currency will Lavin need for Pad Thai in Bangkok, Thailand?", "BAHT"),
    cryptoItem(4, "What currency will Joe need for egg coffee in Hanoi, Vietnam?", "DONG"),
    cryptoItem(5, "What is the local currency Faith will need in Laos, the land of a million elephants?", "KIP"),
    cryptoItem(6, "What local currency does a tourist need in a Kyrgyzstan yurt?", "SOM"),
    cryptoItem(7, "What currency does Tom need for Hilsa curry in Dhaka, Bangladesh?", "TAKA"),
    cryptoItem(8, "Esther is visiting the Great Wall of China. What currency will she need?", "YUAN"),
    cryptoItem(9, "James is exploring Angkor Wat in Cambodia. What local currency will he need?", "RIEL"),
    cryptoItem(10, "What is the local currency Bella will need in Myanmar?", "KYAT"),
    cryptoItem(11, "What local currency will Marie need while island hopping in the Philippines?", "PESO"),
    cryptoItem(12, "While on the way to the Taj Mahal, what currency does Darren use for samosas?", "RUPEE"),
    cryptoItem(13, "Joy is heading to the Petronas Towers in Malaysia. What local currency should they have ready?", "RINGGIT"),
    cryptoItem(14, "Peter pays AFN for a provincial permit in Afghanistan. What is the currency called?", "AFGHANI"),
    cryptoItem(15, "Zuri buys butter tea in Bhutan. What currency is her money in?", "NGULTRUM"),
    cryptoItem(16, "Jabari pays for a yurt in Kazakhstan using the local currency known as?", "TENGE"),
    cryptoItem(17, "Makena pays for a horse trek in Mongolia using?", "TOGROG"),
    cryptoItem(18, "Liam buys a t-shirt in Namche Bazaar, Nepal. What currency does he use?", "RUPEE"),
    cryptoItem(19, "Irina exchanges cash in Pyongyang, North Korea. What currency is she given?", "WON"),
    cryptoItem(20, "Yusuf buys apricots in Hunza Valley, Pakistan. In what currency does he pay?", "RUPEE"),
    cryptoItem(21, "Alexia pays a guesthouse on the Pamir Highway in Tajikistan. In what currency?", "SOMONI"),
    cryptoItem(22, "A surfer in Bali scans a QR code for lunch. In what currency?", "RUPIAH"),
    cryptoItem(23, "Ochieng pays for a milkshake at Gardens by the Bay in Singapore. What currency?", "DOLLAR"),
    cryptoItem(24, "Neema pays a boat driver in Brunei. What does she use?", "DOLLAR"),
    cryptoItem(25, "John pays for scuba lessons in Timor-Leste. What currency is used there?", "DOLLAR"),
    cryptoItem(26, "A history enthusiast pays the Sigiriya Rock fee in Sri Lanka. What currency?", "RUPEE"),
    cryptoItem(27, "Wafula uses the local currency in the Maldives. In what currency does he pay?", "RUFIYAA"),
    cryptoItem(28, "Antonietta buys a ceramic plate in Samarkand, Uzbekistan. What currency?", "SOM"),
    cryptoItem(29, "A traveller at the Darvaza Gas Crater in Turkmenistan pays their guide in?", "MANAT"),
  ],
};

export const currenciesAsiaQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-asia-quiz",
  title: "Currencies of Asia: Quiz",
  topic: "Global Money & Trade",
  instruction: "Answer Asian currency questions from the puzzle book.",
  questions: [
    { id: 1, question: "Paul is in Tokyo and wants a boat ride under cherry blossom trees. What currency does he need?", options: ["Won", "Yen", "Riel", "Baht"], correctIndex: 1, explanation: "Japan uses the yen." },
    { id: 2, question: "If Amelia is in a nomadic yurt in Kyrgyzstan, which currency is she taking out of her wallet?", options: ["Tenge", "Dram", "Som", "Dinar"], correctIndex: 2, explanation: "Kyrgyzstan uses the som." },
    { id: 3, question: "Harry has touched down in South Korea. Which currency does he need?", options: ["Dong", "Kyat", "Peso", "Won"], correctIndex: 3, explanation: "South Korea uses the won." },
    { id: 4, question: "Isla is at a street food stall in Bangkok. How is she paying?", options: ["Baht", "Rupee", "Ringgit", "Taka"], correctIndex: 0, explanation: "Thailand uses the baht." },
    { id: 5, question: "Jack is visiting Petra in Jordan. What is the local cash called?", options: ["Lira", "Dinar", "Shekel", "Riyal"], correctIndex: 1, explanation: "Jordan uses the dinar." },
    { id: 6, question: "Charlotte is eating fish curry in Dhaka, Bangladesh. Which currency does she use?", options: ["Yuan", "Rupee", "Taka", "Kip"], correctIndex: 2, explanation: "Bangladesh uses the taka." },
    { id: 7, question: "Thomas wants to see the Taj Mahal. Which currency does he need?", options: ["Rupiah", "Rufiyaa", "Ringgit", "Rupee"], correctIndex: 3, explanation: "India uses the rupee." },
  ],
};

export const africanCitiesWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-african-cities-ws",
  title: "Notable Cities of Africa: Word Search",
  topic: "Global Money & Trade",
  theme: "15 Notable Cities in Africa",
  instruction: "Find capital and notable African cities from the puzzle book list.",
  size: 14,
  words: ["Cairo", "Dakar", "Nairobi", "Harare", "Algiers", "Lusaka", "Kampala", "Accra", "Tunis", "Rabat", "Abuja", "Kigali", "Pretoria", "Dodoma", "Luanda"],
  grid: [
    ["M", "Y", "B", "I", "T", "H", "T", "E", "R", "U", "Q", "L", "P", "V"],
    ["D", "U", "O", "S", "A", "S", "A", "A", "C", "G", "X", "U", "C", "U"],
    ["S", "H", "G", "R", "I", "I", "I", "A", "B", "K", "T", "S", "A", "L"],
    ["B", "W", "A", "N", "Y", "B", "R", "C", "D", "A", "T", "A", "I", "U"],
    ["U", "R", "U", "J", "X", "O", "O", "C", "Z", "D", "R", "K", "R", "A"],
    ["E", "T", "D", "U", "X", "R", "T", "R", "I", "M", "F", "A", "O", "N"],
    ["W", "I", "F", "K", "Z", "I", "E", "A", "R", "A", "K", "I", "B", "D"],
    ["D", "X", "U", "A", "P", "A", "R", "M", "S", "B", "I", "L", "W", "A"],
    ["O", "C", "R", "M", "G", "N", "P", "W", "R", "B", "C", "A", "N", "J"],
    ["D", "W", "Z", "P", "A", "L", "G", "I", "E", "R", "S", "G", "X", "U"],
    ["O", "D", "F", "A", "Y", "P", "M", "J", "A", "U", "I", "I", "D", "B"],
    ["M", "U", "P", "L", "A", "R", "R", "R", "J", "F", "H", "K", "I", "A"],
    ["A", "J", "U", "A", "H", "I", "D", "A", "K", "A", "R", "M", "F", "X"],
    ["G", "I", "B", "E", "B", "Q", "M", "L", "R", "H", "V", "Z", "R", "A"],
  ],
};
