import { WordSearchPuzzle } from "../types";

export const currenciesAmericaWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-america-ws",
  title: "Currencies of America: Puzzle",
  topic: "Global Money & Trade",
  theme: "Currencies of North, Central & South America",
  instruction: "Find the 17 American currencies in the puzzle grid.",
  size: 14,
  words: [
    "Peso",
    "Krone",
    "Boliviano",
    "Gourde",
    "Pound",
    "Bolivar",
    "Florin",
    "Balboa",
    "Guarani",
    "Dollar",
    "Real",
    "Cordoba",
    "Lempira",
    "Quetzal",
    "Sol",
    "Colon",
    "Euro",
  ],
  grid: [
    ["O", "O", "O", "U", "S", "A", "L", "O", "N", "B", "V", "V", "R", "U"],
    ["U", "Q", "C", "I", "B", "S", "R", "I", "N", "A", "R", "A", "U", "G"],
    ["B", "U", "O", "U", "O", "U", "S", "C", "R", "E", "A", "L", "V", "Z"],
    ["O", "A", "R", "P", "L", "E", "A", "F", "O", "I", "R", "A", "O", "L"],
    ["L", "A", "D", "I", "I", "D", "O", "L", "A", "L", "O", "O", "A", "L"],
    ["I", "F", "O", "L", "V", "R", "B", "O", "A", "U", "O", "Z", "A", "R"],
    ["V", "O", "B", "E", "I", "U", "L", "R", "L", "P", "T", "N", "L", "A"],
    ["A", "R", "A", "M", "A", "O", "A", "I", "P", "E", "Z", "I", "L", "L"],
    ["R", "S", "O", "P", "N", "G", "B", "N", "U", "O", "R", "I", "L", "L"],
    ["O", "K", "A", "I", "O", "D", "K", "Q", "O", "U", "U", "E", "O", "O"],
    ["O", "L", "R", "R", "O", "N", "R", "R", "R", "L", "N", "N", "S", "D"],
    ["U", "L", "O", "A", "E", "B", "A", "O", "O", "O", "A", "S", "D", "A"],
    ["Q", "L", "E", "U", "R", "O", "D", "N", "I", "N", "E", "B", "N", "A"],
    ["O", "N", "K", "O", "S", "E", "R", "A", "O", "S", "E", "P", "A", "B"],
  ],
};

export const currenciesEuropeWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-europe-ws",
  title: "Currencies of Europe: Puzzle",
  topic: "Global Money & Trade",
  theme: "European Union & Continental Currencies",
  instruction: "Find the 20 European currency names in the grid.",
  size: 14,
  words: [
    "Franc",
    "Forint",
    "Dinar",
    "Zloty",
    "Lari",
    "Krone",
    "Dram",
    "Mark",
    "Pound Sterling",
    "Lira",
    "Krona",
    "Denar",
    "Hyrivnia",
    "Ruble",
    "Manat",
    "Tenge",
    "Koruna",
    "Lek",
    "Leu",
    "Euro",
  ],
  grid: [
    ["T", "A", "R", "G", "T", "T", "O", "K", "D", "D", "T", "R", "A", "S"],
    ["M", "R", "R", "U", "E", "L", "N", "E", "R", "R", "Z", "R", "E", "K"],
    ["D", "O", "R", "U", "E", "D", "U", "R", "U", "O", "A", "N", "T", "R"],
    ["T", "I", "R", "R", "R", "D", "E", "N", "A", "R", "N", "M", "E", "O"],
    ["G", "R", "K", "G", "E", "S", "E", "R", "T", "O", "H", "E", "T", "N"],
    ["F", "Y", "I", "K", "A", "N", "U", "R", "O", "K", "E", "A", "N", "A"],
    ["R", "Y", "R", "O", "L", "E", "S", "R", "N", "A", "N", "I", "V", "E"],
    ["A", "D", "I", "N", "A", "R", "N", "R", "U", "A", "R", "L", "D", "U"],
    ["N", "A", "A", "Z", "L", "O", "T", "Y", "M", "B", "G", "A", "T", "T"],
    ["C", "P", "O", "U", "N", "D", "S", "T", "E", "R", "L", "I", "N", "G"],
    ["M", "A", "I", "L", "T", "N", "I", "R", "O", "F", "T", "E", "A", "V"],
    ["E", "G", "N", "E", "T", "H", "Y", "R", "I", "V", "N", "I", "A", "I"],
    ["I", "E", "L", "R", "D", "K", "R", "K", "R", "A", "M", "E", "U", "C"],
    ["L", "L", "I", "R", "A", "A", "I", "B", "K", "E", "L", "A", "R", "I"],
  ],
};

export const currenciesMiddleEastWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-middle-east-ws",
  title: "Currencies of Middle East: Puzzle",
  topic: "Global Money & Trade",
  theme: "Middle Eastern & Gulf Currencies",
  instruction: "Find the 10 Middle Eastern currencies in the grid.",
  size: 14,
  words: [
    "Euro",
    "Dinar",
    "Dollar",
    "Dirham",
    "Pound",
    "Lira",
    "Crypto",
    "Shekel",
    "Rial",
    "Riyal",
  ],
  grid: [
    ["D", "I", "N", "A", "R", "L", "S", "H", "E", "K", "E", "L", "O", "D"],
    ["L", "H", "E", "E", "K", "D", "E", "A", "I", "A", "L", "L", "K", "L"],
    ["L", "R", "R", "R", "O", "Y", "I", "A", "A", "U", "N", "R", "I", "A"],
    ["R", "I", "D", "H", "N", "A", "L", "M", "A", "N", "L", "P", "E", "A"],
    ["C", "M", "H", "D", "R", "R", "Y", "L", "U", "R", "R", "L", "R", "M"],
    ["R", "A", "A", "L", "A", "O", "S", "L", "M", "U", "R", "I", "A", "L"],
    ["L", "I", "E", "N", "U", "L", "L", "K", "L", "H", "L", "K", "R", "D"],
    ["O", "R", "U", "E", "D", "R", "A", "I", "H", "I", "Y", "E", "R", "O"],
    ["T", "I", "R", "H", "L", "D", "D", "U", "D", "R", "O", "I", "O", "L"],
    ["P", "U", "R", "N", "I", "I", "C", "O", "O", "Y", "D", "H", "U", "L"],
    ["Y", "R", "R", "E", "K", "R", "D", "E", "P", "O", "U", "N", "D", "A"],
    ["R", "I", "U", "E", "Y", "H", "R", "L", "R", "I", "Y", "A", "L", "R"],
    ["C", "U", "S", "L", "O", "A", "I", "S", "A", "D", "A", "L", "R", "A"],
    ["A", "H", "O", "L", "N", "M", "P", "R", "O", "E", "A", "A", "I", "R"],
  ],
};

export const currenciesAsiaWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-asia-ws1",
  title: "Currencies of Asia: Puzzle 1",
  topic: "Global Money & Trade",
  theme: "East & Southeast Asian Currencies",
  instruction: "Find the 11 Asian currencies in the puzzle.",
  size: 14,
  words: [
    "Kip",
    "Peso",
    "Ringgit",
    "Yen",
    "Som",
    "Dong",
    "Baht",
    "Taka",
    "Yuan",
    "Kyat",
    "Riel",
  ],
  grid: [
    ["G", "A", "I", "L", "T", "P", "E", "S", "O", "A", "T", "G", "E", "E"],
    ["A", "I", "S", "A", "E", "O", "M", "U", "E", "D", "K", "N", "Y", "L"],
    ["K", "Y", "P", "O", "T", "A", "N", "A", "Y", "E", "L", "O", "B", "A"],
    ["O", "G", "S", "T", "M", "A", "S", "I", "Y", "O", "T", "D", "A", "B"],
    ["O", "T", "I", "G", "G", "N", "I", "R", "N", "T", "S", "T", "I", "A"],
    ["E", "Y", "G", "L", "E", "T", "I", "L", "E", "I", "R", "H", "K", "H"],
    ["D", "R", "P", "R", "U", "K", "U", "Y", "E", "G", "A", "G", "Y", "T"],
    ["Y", "O", "N", "N", "O", "Y", "K", "N", "T", "A", "S", "K", "P", "H"],
    ["K", "A", "E", "E", "P", "K", "R", "O", "H", "O", "K", "A", "I", "K"],
    ["A", "N", "K", "Y", "A", "T", "I", "L", "N", "N", "Y", "T", "K", "T"],
    ["A", "I", "S", "S", "A", "Y", "M", "R", "G", "D", "U", "N", "N", "M"],
    ["T", "U", "A", "K", "A", "T", "O", "T", "E", "M", "A", "U", "E", "A"],
    ["O", "E", "O", "K", "Y", "T", "A", "A", "N", "I", "N", "E", "Y", "U"],
    ["K", "T", "G", "B", "H", "B", "I", "Y", "Y", "B", "S", "O", "N", "T"],
  ],
};

export const currenciesAsiaWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-asia-ws2",
  title: "Currencies of Asia: Puzzle 2",
  topic: "Global Money & Trade",
  theme: "Central & South Asian Currencies",
  instruction: "Find the 10 Central and South Asian currencies.",
  size: 14,
  words: [
    "Rupee",
    "Dollar",
    "Togrog",
    "Afghani",
    "Won",
    "Rufiyaa",
    "Tenge",
    "Somoni",
    "Manat",
    "Ngultrum",
  ],
  grid: [
    ["O", "L", "O", "A", "A", "E", "R", "S", "A", "G", "M", "F", "N", "L"],
    ["U", "G", "O", "O", "R", "D", "E", "R", "U", "F", "I", "Y", "A", "A"],
    ["O", "G", "N", "R", "I", "L", "O", "N", "M", "A", "N", "A", "T", "E"],
    ["L", "A", "G", "A", "G", "U", "G", "L", "L", "P", "Y", "N", "U", "T"],
    ["U", "E", "P", "N", "N", "L", "N", "O", "L", "M", "O", "T", "W", "E"],
    ["A", "F", "G", "H", "A", "N", "I", "L", "R", "A", "L", "N", "P", "N"],
    ["W", "D", "N", "W", "N", "O", "N", "E", "T", "G", "R", "T", "M", "G"],
    ["G", "F", "N", "G", "U", "L", "T", "R", "U", "M", "O", "E", "U", "E"],
    ["I", "N", "E", "U", "N", "G", "G", "O", "W", "M", "L", "T", "A", "M"],
    ["U", "U", "E", "E", "F", "H", "M", "M", "E", "O", "M", "W", "D", "G"],
    ["A", "A", "P", "G", "S", "O", "M", "O", "N", "I", "N", "R", "G", "L"],
    ["S", "N", "U", "N", "N", "Y", "F", "N", "N", "A", "W", "F", "O", "E"],
    ["A", "F", "R", "O", "T", "N", "R", "G", "U", "E", "G", "O", "I", "A"],
    ["T", "N", "O", "H", "F", "A", "I", "N", "U", "O", "O", "O", "U", "N"],
  ],
};
