import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const currenciesAfricaWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-africa-ws1",
  title: "Currencies of Africa: Puzzle 1",
  topic: "Global Money & Trade",
  theme: "Eastern, Southern & Western African Currencies",
  instruction: "Find the 10 African currencies hidden in the puzzle.",
  size: 14,
  words: [
    "Dirham",
    "Franc",
    "Cedi",
    "Shilling",
    "Pula",
    "Dalasi",
    "Ariary",
    "Kwacha",
    "Birr",
    "Metical",
  ],
  grid: [
    ["C", "A", "L", "C", "U", "W", "I", "S", "E", "I", "A", "D", "A", "A"],
    ["E", "I", "H", "L", "E", "R", "A", "I", "A", "R", "D", "A", "A", "I"],
    ["D", "I", "C", "I", "I", "H", "N", "D", "I", "R", "H", "A", "M", "G"],
    ["I", "S", "S", "A", "A", "D", "T", "W", "A", "L", "D", "I", "R", "I"],
    ["I", "A", "H", "I", "I", "L", "I", "W", "A", "Y", "K", "C", "D", "Y"],
    ["R", "L", "I", "E", "L", "T", "I", "S", "I", "F", "A", "A", "H", "D"],
    ["D", "A", "L", "R", "A", "D", "A", "D", "R", "B", "I", "R", "R", "L"],
    ["L", "D", "L", "N", "W", "R", "P", "A", "A", "R", "I", "A", "R", "Y"],
    ["L", "I", "I", "E", "I", "D", "N", "A", "N", "U", "N", "L", "U", "F"],
    ["U", "W", "N", "T", "R", "C", "H", "I", "I", "P", "H", "D", "I", "I"],
    ["K", "R", "G", "A", "A", "C", "W", "M", "A", "I", "R", "P", "I", "D"],
    ["A", "L", "D", "H", "A", "I", "R", "A", "U", "E", "I", "U", "R", "G"],
    ["R", "W", "A", "W", "D", "H", "A", "H", "R", "I", "A", "L", "R", "A"],
    ["A", "L", "K", "M", "E", "T", "I", "C", "A", "L", "I", "A", "I", "S"],
  ],
};

export const currenciesAfricaWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-africa-ws2",
  title: "Currencies of Africa: Puzzle 2",
  topic: "Global Money & Trade",
  theme: "Central, Northern & Island African Currencies",
  instruction: "Find the 10 African currencies hidden across the grid.",
  size: 14,
  words: [
    "Dinar",
    "Nakfa",
    "Rand",
    "Dobra",
    "Kwanza",
    "Ouguiya",
    "Naira",
    "Lilangeni",
    "Zig",
    "Leone",
  ],
  grid: [
    ["G", "Z", "I", "A", "G", "Z", "D", "I", "N", "A", "R", "L", "N", "A"],
    ["A", "R", "N", "F", "L", "O", "A", "Z", "Y", "D", "O", "I", "Z", "A"],
    ["I", "I", "A", "D", "Z", "E", "A", "F", "K", "A", "N", "L", "O", "O"],
    ["N", "Z", "D", "A", "O", "I", "O", "E", "U", "E", "K", "A", "B", "B"],
    ["O", "A", "A", "N", "R", "O", "L", "N", "A", "O", "F", "N", "I", "I"],
    ["O", "Z", "G", "I", "G", "E", "R", "E", "E", "E", "A", "G", "A", "D"],
    ["U", "G", "G", "N", "A", "D", "Y", "A", "L", "N", "A", "E", "I", "A"],
    ["G", "I", "D", "E", "O", "O", "D", "R", "A", "G", "A", "N", "U", "D"],
    ["U", "Z", "A", "I", "D", "B", "Y", "I", "U", "A", "N", "I", "Z", "D"],
    ["I", "N", "N", "Z", "I", "R", "A", "A", "D", "K", "N", "L", "R", "A"],
    ["Y", "I", "A", "E", "N", "A", "N", "N", "B", "R", "A", "G", "L", "G"],
    ["A", "D", "A", "A", "Z", "A", "A", "G", "R", "Y", "Z", "N", "N", "A"],
    ["D", "O", "A", "Y", "I", "Z", "W", "G", "N", "A", "G", "F", "N", "E"],
    ["Z", "Y", "I", "R", "R", "R", "I", "K", "A", "N", "R", "A", "N", "D"],
  ],
};

export const currenciesAfricaQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-africa-quiz",
  title: "Currencies of Africa: Quiz",
  topic: "Global Money & Trade",
  instruction: "Test your knowledge on African national currencies.",
  questions: [
    {
      id: 1,
      question: "Kenya, Uganda, and Tanzania all use different versions of this currency. What is it called?",
      options: ["Shilling", "Pula", "Franc", "Kwacha"],
      correctIndex: 0,
      explanation: "The East African region shares the Shilling denomination name (KES, UGX, TZS).",
    },
    {
      id: 2,
      question: "Which currency is used by South Africa and also by some of its neighbours like Namibia and Lesotho?",
      options: ["Naira", "Rand", "Lilangeni", "Cedi"],
      correctIndex: 1,
      explanation: "The South African Rand (ZAR) is used within the Common Monetary Area.",
    },
    {
      id: 3,
      question: "In Botswana, the name of the money literally means 'rain' because rain is so rare and valuable there. What is it?",
      options: ["Pula", "Birr", "Nakfa", "Ariary"],
      correctIndex: 0,
      explanation: "Pula means 'rain' in Setswana, representing blessings and precious value.",
    },
    {
      id: 4,
      question: "Nigeria, Africa's most populous country, uses which currency?",
      options: ["Naira", "Cedi", "Dinar", "Dalasi"],
      correctIndex: 0,
      explanation: "The Nigerian Naira (NGN) is issued by the Central Bank of Nigeria.",
    },
    {
      id: 5,
      question: "Ghana's currency is named after the cowrie shells that were used as money in the past. What is its name?",
      options: ["Cedi", "Naira", "Leone", "Ouguiya"],
      correctIndex: 0,
      explanation: "Sedie was the Akan language term for the cowrie shell, giving birth to the Ghanaian Cedi.",
    },
  ],
};
