import { WordSearchPuzzle } from "../types";

export const americanCurrenciesWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-american-ws1",
  title: "Currencies of the Americas: Word Search",
  topic: "Global Money & Trade",
  theme: "Currencies of North, Central, and South America",
  instruction: "Find currencies used across North and South America.",
  size: 14,
  words: [
    "BOLIVIANO",
    "CANADIAN DOLLAR",
    "COLON",
    "CORDOBA",
    "DOLLAR",
    "GUARANI",
    "LEMPIRA",
    "PESO",
    "QUETZAL",
    "REAL",
    "SOL",
    "SURINAME",
    "URUGUAY",
    "VENEZUELA",
  ],
  grid: [
    ["C", "A", "N", "A", "D", "I", "A", "N", "D", "O", "L", "L", "A", "R"],
    ["B", "O", "L", "I", "V", "I", "A", "N", "O", "C", "O", "L", "O", "N"],
    ["C", "O", "R", "D", "O", "B", "A", "G", "U", "A", "R", "A", "N", "I"],
    ["D", "O", "L", "L", "A", "R", "L", "E", "M", "P", "I", "R", "A", "P"],
    ["Q", "U", "E", "T", "Z", "A", "L", "P", "E", "S", "O", "R", "E", "A"],
    ["R", "E", "A", "L", "S", "O", "L", "S", "U", "R", "I", "N", "A", "M"],
    ["S", "U", "R", "I", "N", "A", "M", "E", "U", "R", "U", "G", "U", "E"],
    ["V", "E", "N", "E", "Z", "U", "E", "L", "A", "Y", "P", "E", "S", "O"],
    ["A", "M", "E", "R", "I", "C", "A", "N", "T", "R", "A", "D", "E", "S"],
    ["G", "L", "O", "B", "A", "L", "M", "A", "R", "K", "E", "T", "S", "A"],
    ["F", "O", "R", "E", "X", "R", "E", "S", "E", "R", "V", "E", "S", "S"],
    ["W", "O", "R", "L", "D", "B", "A", "N", "K", "I", "N", "G", "S", "S"],
    ["C", "E", "N", "T", "R", "A", "L", "A", "M", "E", "R", "I", "C", "A"],
    ["S", "O", "U", "T", "H", "A", "M", "E", "R", "I", "C", "A", "N", "S"],
  ],
};

export const europeanCurrenciesWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-european-ws1",
  title: "Currencies of Europe: Word Search",
  topic: "Global Money & Trade",
  theme: "Euros, Pounds, Kroner, and Francs",
  instruction: "Search for the national and continental currencies across Europe.",
  size: 14,
  words: [
    "DINAR",
    "EURO",
    "FORINT",
    "FRANC",
    "KRONA",
    "KRONE",
    "LEK",
    "LEV",
    "MARK",
    "POUND STERLING",
    "RUBLE",
    "ZLOTY",
    "SWISS",
    "NORWAY",
  ],
  grid: [
    ["P", "O", "U", "N", "D", "S", "T", "E", "R", "L", "I", "N", "G", "A"],
    ["E", "U", "R", "O", "F", "O", "R", "I", "N", "T", "F", "R", "A", "N"],
    ["K", "R", "O", "N", "A", "K", "R", "O", "N", "E", "L", "E", "K", "C"],
    ["Z", "L", "O", "T", "Y", "R", "U", "B", "L", "E", "L", "E", "V", "S"],
    ["S", "W", "I", "S", "S", "F", "R", "A", "N", "C", "M", "A", "R", "K"],
    ["N", "O", "R", "W", "A", "Y", "K", "R", "O", "N", "E", "S", "E", "A"],
    ["E", "U", "R", "O", "Z", "O", "N", "E", "B", "A", "N", "K", "I", "N"],
    ["L", "O", "N", "D", "O", "N", "F", "I", "N", "A", "N", "C", "E", "S"],
    ["F", "R", "A", "N", "K", "F", "U", "R", "T", "E", "U", "R", "O", "P"],
    ["C", "E", "N", "T", "R", "A", "L", "B", "A", "N", "K", "S", "E", "T"],
    ["M", "O", "N", "E", "T", "A", "R", "Y", "P", "O", "L", "I", "C", "Y"],
    ["G", "L", "O", "B", "A", "L", "R", "E", "S", "E", "R", "V", "E", "S"],
    ["S", "E", "T", "T", "L", "E", "M", "E", "N", "T", "N", "E", "T", "S"],
    ["I", "N", "T", "E", "R", "N", "A", "T", "I", "O", "N", "A", "L", "S"],
  ],
};
