import { WordSearchPuzzle, QuizPuzzle, CrosswordPuzzle } from "../types";

export const historyOfTradeWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-trade-ws1",
  title: "History of Trade in Africa: Puzzle 1",
  topic: "Global Money & Trade",
  theme: "Ancient African Mediums of Exchange",
  instruction: "Find the 12 trade items, currencies, and institutions in the grid.",
  size: 14,
  words: [
    "Tin",
    "Cowrie Shells",
    "Products",
    "Shilling",
    "Goods",
    "CBK",
    "Services",
    "Trade",
    "Rupee",
    "Grain",
    "Cent",
    "Mpesa",
  ],
  grid: [
    ["R", "R", "T", "R", "C", "E", "P", "R", "O", "D", "U", "C", "T", "S"],
    ["E", "S", "S", "S", "I", "E", "R", "O", "R", "I", "H", "T", "E", "E"],
    ["S", "L", "L", "E", "H", "S", "E", "I", "R", "W", "O", "C", "I", "R"],
    ["R", "T", "A", "C", "U", "L", "G", "L", "C", "T", "O", "R", "I", "N"],
    ["G", "I", "C", "C", "B", "E", "C", "B", "R", "N", "S", "E", "T", "S"],
    ["G", "T", "G", "N", "I", "L", "L", "I", "H", "S", "O", "C", "O", "L"],
    ["T", "C", "I", "B", "N", "E", "T", "E", "T", "S", "R", "K", "E", "H"],
    ["S", "L", "D", "U", "G", "V", "S", "E", "R", "V", "I", "C", "E", "S"],
    ["R", "C", "B", "K", "V", "H", "H", "E", "A", "R", "G", "U", "N", "A"],
    ["N", "G", "R", "A", "I", "N", "S", "P", "D", "R", "O", "M", "R", "A"],
    ["U", "S", "C", "E", "E", "I", "W", "U", "E", "U", "O", "P", "I", "D"],
    ["E", "A", "T", "E", "O", "S", "O", "R", "C", "B", "D", "E", "P", "T"],
    ["I", "R", "T", "T", "N", "D", "A", "M", "C", "S", "S", "S", "T", "E"],
    ["P", "D", "L", "E", "R", "T", "S", "S", "T", "V", "S", "A", "P", "S"],
  ],
};

export const historyOfTradeWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-trade-ws2",
  title: "History of Trade in Africa: Puzzle 2",
  topic: "Global Money & Trade",
  theme: "Trans-Saharan Caravans & Empires",
  instruction: "Find the 12 kingdom names, caravan goods, and ancient coins.",
  size: 14,
  words: [
    "Konatisa",
    "Ndururu",
    "Salt",
    "Timbuktu",
    "Ghana",
    "Aksum",
    "Value",
    "Dhow",
    "Gold",
    "Silk",
    "Wool",
    "Caravan",
  ],
  grid: [
    ["U", "O", "K", "W", "U", "A", "O", "K", "K", "K", "O", "C", "R", "K"],
    ["C", "M", "U", "O", "T", "U", "M", "I", "A", "M", "A", "T", "O", "S"],
    ["R", "M", "U", "D", "M", "U", "B", "N", "R", "W", "W", "I", "T", "A"],
    ["L", "U", "N", "A", "T", "I", "T", "A", "K", "O", "L", "M", "D", "L"],
    ["C", "S", "D", "H", "U", "T", "A", "O", "K", "H", "I", "B", "B", "T"],
    ["L", "K", "W", "R", "L", "M", "S", "R", "O", "D", "K", "U", "T", "A"],
    ["L", "A", "U", "U", "I", "V", "H", "R", "S", "L", "N", "K", "I", "A"],
    ["N", "G", "G", "V", "A", "L", "U", "E", "V", "O", "N", "T", "K", "A"],
    ["S", "C", "A", "R", "A", "V", "A", "N", "O", "T", "L", "U", "O", "U"],
    ["K", "D", "K", "G", "A", "T", "I", "N", "D", "U", "R", "U", "R", "U"],
    ["O", "A", "K", "O", "N", "A", "T", "I", "S", "A", "G", "K", "S", "W"],
    ["B", "E", "A", "R", "A", "A", "A", "D", "A", "N", "O", "L", "O", "O"],
    ["S", "I", "L", "K", "H", "D", "N", "K", "L", "R", "L", "W", "A", "O"],
    ["L", "G", "M", "N", "G", "D", "A", "H", "G", "L", "D", "B", "U", "L"],
  ],
};

export const historyOfTradeWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-trade-ws3",
  title: "History of Trade in Africa: Puzzle 3",
  topic: "Global Money & Trade",
  theme: "Indian Ocean & Swahili Coast Trade",
  instruction: "Find the 12 monsoon trade and barter commodities.",
  size: 14,
  words: [
    "Weapons",
    "Ivory",
    "Gold Dust",
    "Barter",
    "Copper",
    "Livestock",
    "Iron",
    "Monsoon",
    "Beads",
    "Cloth",
    "Camel",
    "Swahili",
  ],
  grid: [
    ["S", "V", "V", "W", "T", "A", "N", "S", "O", "A", "I", "I", "O", "P"],
    ["E", "A", "S", "L", "L", "I", "V", "E", "S", "T", "O", "C", "K", "S"],
    ["P", "O", "N", "S", "I", "S", "I", "L", "I", "H", "A", "W", "S", "M"],
    ["H", "E", "V", "N", "D", "C", "C", "A", "S", "D", "A", "E", "B", "M"],
    ["O", "I", "V", "O", "R", "Y", "L", "E", "U", "N", "N", "N", "T", "I"],
    ["I", "I", "E", "P", "O", "G", "O", "L", "D", "D", "U", "S", "T", "N"],
    ["V", "W", "D", "A", "R", "I", "O", "S", "E", "S", "B", "L", "M", "S"],
    ["O", "B", "O", "E", "T", "L", "D", "R", "O", "L", "A", "I", "W", "R"],
    ["I", "C", "A", "W", "H", "P", "H", "O", "P", "E", "R", "R", "O", "S"],
    ["A", "L", "M", "V", "D", "O", "I", "A", "R", "M", "T", "O", "C", "B"],
    ["O", "O", "M", "C", "I", "R", "O", "N", "T", "A", "E", "O", "S", "C"],
    ["A", "T", "N", "O", "O", "S", "N", "O", "M", "C", "R", "T", "A", "I"],
    ["O", "H", "P", "T", "S", "E", "E", "S", "L", "T", "E", "L", "O", "O"],
    ["L", "D", "S", "S", "C", "O", "P", "P", "E", "R", "A", "P", "I", "O"],
  ],
};

export const historyOfTradeWordSearch4: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-trade-ws4",
  title: "History of Trade in Africa: Puzzle 4",
  topic: "Global Money & Trade",
  theme: "Cross-Border Merchant Goods & Currencies",
  instruction: "Find the 13 merchant commodities and regional trade items.",
  size: 14,
  words: [
    "Commodity",
    "Manilla",
    "Mint",
    "Furniture",
    "Cross Border",
    "Silver",
    "Zanzibar",
    "Kola Nut",
    "Porcelain",
    "Bullion",
    "Amol",
    "Cattle",
    "Spices",
  ],
  grid: [
    ["I", "B", "F", "U", "R", "N", "I", "T", "U", "R", "E", "I", "C", "A"],
    ["Y", "E", "F", "S", "P", "I", "C", "E", "S", "V", "B", "A", "R", "I"],
    ["T", "L", "A", "U", "L", "O", "L", "A", "L", "S", "U", "Z", "O", "M"],
    ["I", "S", "O", "L", "L", "M", "T", "N", "V", "T", "L", "O", "S", "N"],
    ["D", "Z", "A", "N", "Z", "I", "B", "A", "R", "C", "L", "O", "S", "I"],
    ["O", "T", "V", "M", "U", "I", "A", "N", "R", "R", "I", "N", "B", "A"],
    ["M", "M", "C", "N", "S", "O", "I", "N", "A", "C", "O", "A", "O", "L"],
    ["M", "B", "I", "D", "I", "I", "A", "M", "L", "C", "N", "E", "R", "E"],
    ["O", "A", "D", "N", "U", "R", "Z", "S", "L", "A", "L", "A", "D", "C"],
    ["C", "S", "M", "I", "T", "I", "U", "D", "I", "T", "L", "N", "E", "R"],
    ["R", "R", "E", "O", "R", "E", "S", "N", "N", "T", "I", "O", "R", "O"],
    ["R", "K", "S", "I", "L", "V", "E", "R", "A", "L", "Y", "R", "R", "P"],
    ["B", "N", "N", "R", "A", "I", "F", "L", "M", "E", "A", "A", "R", "T"],
    ["O", "O", "K", "O", "L", "A", "N", "U", "T", "U", "T", "N", "O", "P"],
  ],
};

export const historyOfTradeQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-trade-quiz",
  title: "History of Trade in Africa: Quiz",
  topic: "Global Money & Trade",
  instruction: "Discover early African currencies, ancient empires, and maritime trade.",
  questions: [
    {
      id: 1,
      question: "Before coins and notes, people exchanged one item directly for another e.g. exchanging a goat for bags of grain. What is this system called?",
      options: ["Bullion", "Barter", "Mpesa", "Minting"],
      correctIndex: 1,
      explanation: "Barter was the direct exchange of goods and services without an intermediary monetary unit.",
    },
    {
      id: 2,
      question: "Which small, white sea shells were used as a popular form of 'commodity currency' across ancient Africa?",
      options: ["Amol", "Manilla", "Cowrieshell", "Beads"],
      correctIndex: 2,
      explanation: "Cowrie shells from the Indian Ocean were durable, portable, and impossible to counterfeit in inland Africa.",
    },
    {
      id: 3,
      question: "In the Trans-Saharan trade, what was famously traded 'ounce for ounce' with Gold because it was so essential for preserving food?",
      options: ["Iron", "Silk", "Copper", "Salt"],
      correctIndex: 3,
      explanation: "Rock salt mined from the Sahara was worth its weight in gold to preserve meat and maintain bodily hydration.",
    },
    {
      id: 4,
      question: "Which animal also known as the 'ship of the desert' made it possible for caravans to cross the Sahara Desert?",
      options: ["Camel", "Donkey", "Dhow", "Horse"],
      correctIndex: 0,
      explanation: "Camels can travel hundreds of kilometers without water carrying heavy loads of gold, salt, and textiles.",
    },
    {
      id: 5,
      question: "On the East African coast, Swahili traders used the ___ winds to sail their dhows to India and Arabia.",
      options: ["Zephyr", "Monsoon", "Trade", "Cyclone"],
      correctIndex: 1,
      explanation: "Seasonal monsoon winds enabled regular round-trip dhow voyages across the Indian Ocean.",
    },
    {
      id: 6,
      question: "Which famous ancient West African empire was known as the 'Land of Gold'?",
      options: ["Timbuktu", "Zanzibar", "Ghana", "Aksum"],
      correctIndex: 2,
      explanation: "The ancient Ghana Empire controlled the rich goldfields of West Africa and tax routes.",
    },
    {
      id: 7,
      question: "What luxury item, taken from the tusks of elephants, was a highly valued export from Africa for centuries?",
      options: ["Porcelain", "Wool", "Tin", "Ivory"],
      correctIndex: 3,
      explanation: "Elephant ivory was carved into art, chess sets, and royal ornaments in Asian and European palaces.",
    },
    {
      id: 8,
      question: "Before the shilling, what currency was introduced to East Africa by traders from India?",
      options: ["Rupee", "Cent", "Dollar", "Manilla"],
      correctIndex: 0,
      explanation: "The Indian Rupee was widely circulated along the East African coast due to strong commercial ties with Bombay.",
    },
    {
      id: 9,
      question: "Which of these cities served as a major maritime hub for the Swahili Coast trade?",
      options: ["Timbuktu", "Mombasa", "Nairobi", "Nakuru"],
      correctIndex: 1,
      explanation: "Mombasa, along with Kilwa and Lamu, was an ancient island city-state and central Indian Ocean trading port.",
    },
    {
      id: 10,
      question: "The Swahili language, which was born from this trade, is a blend of which two main cultures?",
      options: ["Spanish and Portuguese", "French and English", "Bantu and Arabic", "Luo and Hindi"],
      correctIndex: 2,
      explanation: "Kiswahili developed along the East African coast as a Bantu grammatical foundation enriched by Arabic merchant vocabulary.",
    },
  ],
};

export const historyOfTradeCrossword5: CrosswordPuzzle = {
  type: "crossword",
  id: "gm-trade-cw5",
  title: "History of Trade in Africa: Puzzle 5",
  topic: "Global Money & Trade",
  instruction: "Fill monsoon, bullion, and Indian Ocean trade words.",
  rows: 12,
  cols: 14,
  wordBank: ["Zanzibar", "Monsoon", "Bullion", "Porcelain", "Mint", "Vase", "Kola", "Commodity", "Mombasa", "Silver"],
  acrossClues: [
    { number: 3, clue: "Seasonal winds that enabled dhows to sail predictably between the East African coast, India, and Arabia.", answer: "MONSOON", row: 2, col: 0, direction: "across" },
    { number: 4, clue: "A shiny metal used for the Maria Theresa Thaler coin along the Kenyan coast in the 1800s.", answer: "SILVER", row: 5, col: 0, direction: "across" },
    { number: 6, clue: "A basic good used in trade, such as salt, ivory, or iron.", answer: "COMMODITY", row: 8, col: 0, direction: "across" },
    { number: 8, clue: "A luxury import from China found in archaeological sites like Great Zimbabwe.", answer: "PORCELAIN", row: 10, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 1, clue: "The East African island hub famous for the spice trade, particularly cloves.", answer: "ZANZIBAR", row: 0, col: 12, direction: "down" },
    { number: 2, clue: "High-purity gold or silver kept as bars or ingots.", answer: "BULLION", row: 0, col: 10, direction: "down" },
    { number: 5, clue: "A caffeine-rich nut grown in West African forests and traded north as a stimulant.", answer: "KOLA", row: 4, col: 4, direction: "down" },
    { number: 7, clue: "A specialized factory where official coins and notes are created.", answer: "MINT", row: 6, col: 6, direction: "down" },
  ],
};
