import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const tradeHistoryWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-trade-ws1",
  title: "Ancient African Trade: Word Search",
  topic: "Global Money & Trade",
  theme: "Trans-Saharan, Swahili Coast, and Great Zimbabwe Routes",
  instruction: "Search for ancient caravan trade goods, routes, and trading kingdoms.",
  size: 14,
  words: [
    "CARAVAN",
    "COWRIE SHELL",
    "DHOW",
    "FRANKINCENSE",
    "GOLD",
    "IVORY",
    "KILWA",
    "MANSA MUSA",
    "MONSOON",
    "MYRRH",
    "SALT",
    "SILK",
    "SPICES",
    "TIMBUKTU",
  ],
  grid: [
    ["T", "I", "M", "B", "U", "K", "T", "U", "C", "A", "R", "A", "V", "A"],
    ["M", "A", "N", "S", "A", "M", "U", "S", "A", "G", "O", "L", "D", "N"],
    ["F", "R", "A", "N", "K", "I", "N", "C", "E", "N", "S", "E", "S", "I"],
    ["C", "O", "W", "R", "I", "E", "S", "H", "E", "L", "L", "D", "P", "V"],
    ["M", "O", "N", "S", "O", "O", "N", "M", "Y", "R", "R", "H", "I", "O"],
    ["K", "I", "L", "W", "A", "I", "V", "O", "R", "Y", "S", "O", "C", "R"],
    ["S", "A", "L", "T", "S", "I", "L", "K", "D", "H", "O", "W", "E", "Y"],
    ["T", "R", "A", "N", "S", "S", "A", "H", "A", "R", "A", "N", "S", "K"],
    ["I", "N", "D", "I", "A", "N", "O", "C", "E", "A", "N", "P", "A", "E"],
    ["S", "W", "A", "H", "I", "L", "I", "C", "O", "A", "S", "T", "T", "N"],
    ["Z", "I", "M", "B", "A", "B", "W", "E", "G", "O", "L", "D", "H", "Y"],
    ["G", "H", "A", "N", "A", "E", "M", "P", "I", "R", "E", "C", "O", "A"],
    ["M", "E", "R", "C", "H", "A", "N", "T", "S", "H", "I", "P", "S", "S"],
    ["E", "X", "C", "H", "A", "N", "G", "E", "R", "A", "T", "E", "S", "P"],
  ],
};

export const tradeHistoryWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "gm-trade-ws2",
  title: "Kingdoms of Gold & Salt: Word Search",
  topic: "Global Money & Trade",
  theme: "Mali, Songhai, Axum, and Kush Empires",
  instruction: "Find ancient empires that minted coins and controlled continental trade wealth.",
  size: 14,
  words: [
    "AKSUM COINS",
    "CAMEL SADDLE",
    "COPPER INGOTS",
    "DJENNE",
    "EMPIRE",
    "GHANA",
    "KUSH",
    "MALI",
    "NUBIA",
    "OASIS",
    "SAHARA",
    "SONGHAI",
    "TAGHAZA",
    "WALATA",
  ],
  grid: [
    ["A", "K", "S", "U", "M", "C", "O", "I", "N", "S", "M", "A", "L", "I"],
    ["G", "H", "A", "N", "A", "S", "O", "N", "G", "H", "A", "I", "A", "K"],
    ["C", "A", "M", "E", "L", "S", "A", "D", "D", "L", "E", "B", "C", "U"],
    ["C", "O", "P", "P", "E", "R", "I", "N", "G", "O", "T", "S", "D", "S"],
    ["T", "A", "G", "H", "A", "Z", "A", "D", "J", "E", "N", "N", "E", "H"],
    ["W", "A", "L", "A", "T", "A", "O", "A", "S", "I", "S", "N", "U", "B"],
    ["S", "A", "H", "A", "R", "A", "E", "M", "P", "I", "R", "E", "I", "A"],
    ["T", "R", "A", "D", "E", "R", "O", "U", "T", "E", "S", "C", "A", "S"],
    ["K", "I", "N", "G", "D", "O", "M", "S", "O", "F", "G", "O", "L", "D"],
    ["C", "O", "M", "M", "E", "R", "C", "E", "H", "U", "B", "S", "T", "E"],
    ["H", "I", "S", "T", "O", "R", "I", "C", "P", "A", "T", "H", "S", "P"],
    ["M", "E", "D", "I", "T", "E", "R", "R", "A", "N", "E", "A", "N", "A"],
    ["R", "E", "D", "S", "E", "A", "P", "O", "R", "T", "S", "K", "E", "N"],
    ["A", "F", "R", "I", "C", "A", "N", "H", "E", "R", "I", "T", "A", "G"],
  ],
};

export const tradeHistoryQuiz: QuizPuzzle = {
  type: "quiz",
  id: "gm-trade-quiz",
  title: "African Trade History Quiz",
  topic: "Global Money & Trade",
  instruction: "Discover how African trade networks enriched global civilization.",
  questions: [
    {
      id: 1,
      question: "Who was Mansa Musa and why is he world-famous in economic history?",
      options: [
        "The Emperor of Mali whose 1324 pilgrimage with tons of gold demonstrated West Africa's immense wealth to the world",
        "A pirate who sailed around Antarctica",
        "The first person to use a calculator",
        "A roman emperor who invented paper",
      ],
      correctIndex: 0,
      explanation:
        "Mansa Musa ruled the wealthy Mali Empire, distributing so much gold in Cairo that it depressed gold prices for a decade.",
    },
    {
      id: 2,
      question: "Which ancient East African kingdom was among the first in the world to mint its own gold, silver, and bronze coins?",
      options: ["Kingdom of Aksum (Axum)", "Atlantis", "Sparta", "Babylon"],
      correctIndex: 0,
      explanation:
        "The Kingdom of Aksum (modern Ethiopia/Eritrea) minted intricate coins bearing kings' portraits from the 3rd century AD.",
    },
    {
      id: 3,
      question: "What natural weather phenomenon enabled trade dhows to sail between India, Arabia, and the East African Swahili Coast?",
      options: [
        "Monsoon winds (Kaskazi and Kusi seasonal wind currents)",
        "Tornadoes",
        "Volcanic eruptions",
        "Heavy snowstorms",
      ],
      correctIndex: 0,
      explanation:
        "Seasonal monsoon winds reversed direction twice a year, powering maritime trade across the Indian Ocean.",
    },
  ],
};
