import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const careersWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws1",
  title: "Careers & Employment: Puzzle 1",
  topic: "Earning & Growing Money",
  theme: "Workplace Skills & Professional Growth",
  instruction: "Find the 13 career and employment terms in the grid.",
  size: 14,
  words: [
    "Productivity",
    "Qualifications",
    "Commission",
    "Mentor",
    "Job",
    "Freelance",
    "Internship",
    "Career",
    "Talent",
    "Skillset",
    "Bonus",
    "Hire",
    "Employer",
  ],
  grid: [
    ["S", "R", "L", "P", "E", "K", "P", "I", "S", "N", "M", "O", "E", "U"],
    ["N", "I", "Y", "T", "I", "V", "I", "T", "C", "U", "D", "O", "R", "P"],
    ["O", "L", "A", "N", "B", "Y", "H", "K", "C", "N", "S", "N", "N", "O"],
    ["I", "N", "C", "R", "O", "V", "S", "N", "O", "E", "F", "M", "O", "T"],
    ["T", "U", "C", "E", "N", "Q", "N", "S", "M", "Y", "R", "T", "O", "E"],
    ["A", "O", "T", "Q", "U", "T", "R", "T", "M", "J", "E", "T", "O", "S"],
    ["C", "H", "N", "E", "S", "C", "E", "H", "I", "O", "E", "I", "C", "L"],
    ["I", "I", "E", "M", "C", "L", "T", "L", "S", "B", "L", "O", "A", "L"],
    ["F", "R", "L", "C", "E", "A", "N", "O", "S", "E", "A", "I", "R", "I"],
    ["I", "E", "A", "A", "R", "N", "I", "R", "I", "E", "N", "C", "E", "K"],
    ["L", "E", "T", "N", "U", "I", "T", "T", "O", "L", "C", "I", "E", "S"],
    ["A", "L", "K", "S", "T", "O", "O", "O", "N", "S", "E", "E", "R", "E"],
    ["U", "L", "T", "I", "R", "I", "E", "U", "R", "A", "U", "R", "I", "C"],
    ["Q", "U", "C", "E", "M", "P", "L", "O", "Y", "E", "R", "F", "S", "H"],
  ],
};

export const careersWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws2",
  title: "Careers & Employment: Puzzle 2",
  topic: "Earning & Growing Money",
  theme: "Recruitment, Contracts & Teamwork",
  instruction: "Find the 12 workplace leadership and contract terms.",
  size: 14,
  words: [
    "Application",
    "Interview",
    "Employee",
    "Responsibility",
    "Contract",
    "Workplace",
    "Promotion",
    "Leadership",
    "Salary Scale",
    "Training",
    "Profession",
    "Teamwork",
  ],
  grid: [
    ["G", "N", "I", "N", "I", "A", "R", "T", "A", "I", "E", "C", "T", "E"],
    ["A", "I", "O", "W", "D", "S", "O", "P", "I", "R", "E", "I", "N", "M"],
    ["P", "O", "P", "R", "O", "M", "O", "T", "I", "O", "N", "D", "O", "P"],
    ["P", "C", "D", "I", "S", "R", "W", "B", "N", "I", "P", "O", "I", "L"],
    ["L", "R", "N", "L", "I", "A", "K", "C", "K", "S", "A", "E", "S", "O"],
    ["I", "I", "T", "P", "E", "A", "T", "P", "I", "W", "P", "E", "S", "Y"],
    ["C", "N", "R", "C", "I", "O", "N", "O", "L", "E", "I", "A", "E", "E"],
    ["A", "T", "A", "O", "N", "E", "T", "N", "T", "A", "I", "P", "F", "E"],
    ["T", "E", "A", "M", "W", "O", "R", "K", "P", "O", "C", "A", "O", "T"],
    ["I", "R", "T", "O", "H", "O", "R", "O", "O", "S", "W", "E", "R", "P"],
    ["O", "V", "P", "I", "H", "S", "R", "E", "D", "A", "E", "L", "P", "C"],
    ["N", "I", "C", "S", "A", "L", "A", "R", "Y", "S", "C", "A", "L", "E"],
    ["R", "E", "S", "P", "O", "N", "S", "I", "B", "I", "L", "I", "T", "Y"],
    ["T", "W", "R", "Y", "L", "L", "C", "O", "N", "T", "R", "A", "C", "T"],
  ],
};

export const careersWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws3",
  title: "Careers & Employment: Puzzle 3",
  topic: "Earning & Growing Money",
  theme: "Essential Professions",
  instruction: "Find the 12 essential professions in the grid.",
  size: 14,
  words: [
    "Doctor",
    "Lawyer",
    "Mechanic",
    "Writer",
    "Lecturer",
    "Farmer",
    "Chef",
    "Banker",
    "Engineer",
    "Nurse",
    "Teacher",
    "Pilot",
  ],
  grid: [
    ["M", "E", "C", "N", "T", "C", "N", "K", "L", "R", "F", "N", "C", "N"],
    ["E", "B", "E", "O", "I", "E", "R", "N", "I", "A", "E", "M", "H", "A"],
    ["N", "A", "R", "R", "E", "T", "I", "R", "W", "W", "W", "T", "R", "C"],
    ["E", "N", "C", "C", "I", "M", "E", "C", "U", "E", "A", "Y", "R", "R"],
    ["U", "K", "I", "H", "T", "E", "E", "A", "F", "Y", "T", "N", "E", "U"],
    ["E", "E", "T", "E", "K", "C", "N", "U", "N", "A", "I", "C", "R", "R"],
    ["L", "R", "R", "F", "H", "H", "R", "L", "F", "C", "A", "I", "R", "E"],
    ["A", "O", "D", "E", "E", "A", "T", "R", "A", "T", "N", "F", "G", "N"],
    ["P", "I", "L", "O", "T", "N", "C", "N", "R", "E", "G", "R", "R", "G"],
    ["A", "E", "W", "O", "I", "I", "C", "R", "M", "I", "C", "O", "S", "I"],
    ["A", "T", "O", "L", "S", "C", "E", "T", "E", "T", "O", "T", "E", "N"],
    ["E", "R", "E", "H", "C", "A", "E", "T", "R", "R", "U", "C", "C", "E"],
    ["I", "L", "E", "C", "T", "U", "R", "E", "R", "A", "R", "O", "E", "E"],
    ["E", "S", "R", "U", "N", "E", "M", "R", "I", "E", "D", "D", "A", "R"],
  ],
};

export const careersWordSearch4: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws4",
  title: "Careers & Employment: Puzzle 4",
  topic: "Earning & Growing Money",
  theme: "Health & Science Careers",
  instruction: "Find the 13 health and science careers in the grid.",
  size: 14,
  words: [
    "Labtech",
    "Midwife",
    "Botanist",
    "Veterinarian",
    "Therapist",
    "Oculist",
    "Dentist",
    "Scientist",
    "Surgeon",
    "Psychologist",
    "Chiropractor",
    "Psychiatrist",
    "Pharmacist",
  ],
  grid: [
    ["A", "N", "P", "S", "Y", "C", "H", "O", "L", "O", "G", "I", "S", "T"],
    ["C", "T", "P", "G", "R", "S", "U", "R", "G", "E", "O", "N", "I", "S"],
    ["T", "S", "C", "I", "E", "N", "T", "I", "S", "T", "S", "G", "F", "O"],
    ["I", "C", "N", "S", "R", "C", "U", "D", "R", "S", "T", "A", "M", "S"],
    ["O", "A", "T", "O", "A", "T", "T", "E", "R", "C", "O", "R", "L", "S"],
    ["C", "V", "E", "T", "E", "R", "I", "N", "A", "R", "I", "A", "N", "T"],
    ["U", "E", "N", "I", "A", "I", "T", "T", "L", "D", "T", "P", "S", "B"],
    ["L", "T", "H", "E", "R", "A", "P", "I", "S", "T", "T", "I", "M", "O"],
    ["I", "C", "C", "U", "E", "T", "R", "S", "I", "I", "T", "B", "I", "T"],
    ["S", "S", "M", "S", "T", "T", "I", "T", "I", "I", "H", "I", "D", "A"],
    ["T", "L", "A", "B", "T", "E", "C", "H", "E", "O", "T", "T", "W", "N"],
    ["P", "S", "Y", "C", "H", "I", "A", "T", "R", "I", "S", "T", "I", "I"],
    ["R", "O", "T", "C", "A", "R", "P", "O", "R", "I", "H", "C", "F", "S"],
    ["I", "R", "P", "H", "A", "R", "M", "A", "C", "I", "S", "T", "E", "T"],
  ],
};

export const careersWordSearch5: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws5",
  title: "Careers & Employment: Puzzle 5",
  topic: "Earning & Growing Money",
  theme: "Building, Technical & Craft Careers",
  instruction: "Find the 12 technical building and trade professions.",
  size: 14,
  words: [
    "Driver",
    "Builder",
    "Carpenter",
    "Welder",
    "Architect",
    "Landlord",
    "Plumber",
    "Electrician",
    "Tailor",
    "Painter",
    "Mason",
    "Surveyor",
  ],
  grid: [
    ["B", "C", "E", "R", "L", "O", "P", "T", "C", "L", "C", "V", "I", "A"],
    ["P", "T", "E", "I", "A", "R", "L", "T", "M", "B", "I", "E", "C", "R"],
    ["A", "A", "D", "T", "D", "U", "U", "A", "M", "U", "R", "T", "L", "C"],
    ["C", "E", "R", "T", "R", "R", "M", "I", "T", "I", "I", "A", "A", "H"],
    ["D", "C", "L", "D", "P", "R", "B", "L", "E", "L", "N", "M", "R", "I"],
    ["E", "A", "R", "E", "D", "R", "E", "O", "C", "D", "N", "E", "O", "T"],
    ["P", "R", "A", "O", "C", "R", "R", "R", "L", "E", "B", "L", "Y", "E"],
    ["A", "P", "A", "R", "A", "T", "D", "O", "V", "R", "T", "W", "E", "C"],
    ["I", "E", "E", "A", "M", "A", "R", "R", "L", "U", "E", "E", "V", "T"],
    ["N", "N", "R", "L", "T", "D", "R", "I", "I", "R", "E", "L", "R", "V"],
    ["T", "T", "R", "A", "D", "R", "T", "E", "C", "V", "I", "D", "U", "V"],
    ["E", "E", "R", "R", "A", "N", "N", "E", "E", "I", "E", "E", "S", "A"],
    ["R", "R", "M", "A", "S", "O", "N", "L", "D", "R", "A", "R", "R", "T"],
    ["U", "E", "L", "B", "D", "R", "R", "P", "L", "D", "R", "N", "E", "I"],
  ],
};

export const careersWordSearch6: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws6",
  title: "Careers & Employment: Puzzle 6",
  topic: "Earning & Growing Money",
  theme: "Technology, Design & Media Careers",
  instruction: "Find the 11 tech, design, and coding professions.",
  size: 14,
  words: [
    "Designer",
    "Animator",
    "Typist",
    "Technician",
    "Developer",
    "Engineer",
    "Coder",
    "Editor",
    "Programmer",
    "Analyst",
    "Blogger",
  ],
  grid: [
    ["D", "P", "R", "O", "G", "R", "A", "M", "M", "E", "R", "R", "E", "A"],
    ["N", "M", "N", "O", "G", "E", "A", "H", "A", "R", "N", "R", "G", "N"],
    ["Y", "A", "T", "E", "T", "Y", "P", "I", "S", "T", "N", "Y", "R", "R"],
    ["L", "N", "A", "I", "C", "I", "N", "H", "C", "E", "T", "P", "E", "E"],
    ["T", "A", "M", "D", "E", "R", "L", "E", "D", "I", "T", "O", "R", "P"],
    ["B", "L", "O", "G", "G", "E", "R", "O", "E", "O", "T", "S", "R", "O"],
    ["R", "Y", "A", "A", "N", "N", "R", "I", "I", "Y", "E", "R", "N", "L"],
    ["R", "S", "E", "O", "G", "G", "N", "G", "E", "R", "L", "C", "R", "E"],
    ["A", "T", "E", "N", "G", "I", "N", "E", "E", "R", "R", "O", "E", "V"],
    ["I", "I", "I", "A", "H", "S", "O", "Y", "E", "T", "O", "D", "S", "E"],
    ["T", "N", "N", "C", "Y", "E", "E", "I", "N", "I", "R", "E", "R", "D"],
    ["E", "I", "I", "P", "R", "D", "S", "R", "E", "R", "E", "R", "G", "N"],
    ["C", "O", "A", "N", "I", "M", "A", "T", "O", "R", "V", "A", "R", "A"],
    ["R", "L", "T", "E", "A", "R", "C", "E", "N", "O", "G", "R", "I", "B"],
  ],
};

export const careersWordSearch7: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws7",
  title: "Careers & Employment: Puzzle 7",
  topic: "Earning & Growing Money",
  theme: "Agriculture, Forestry & Environment",
  instruction: "Find the 12 agricultural and wildlife careers.",
  size: 14,
  words: [
    "Herdsman",
    "Fisherman",
    "Gardener",
    "Veterinarian",
    "Ranger",
    "Horticulturist",
    "Agronomist",
    "Entrepreneur",
    "Zookeeper",
    "Forester",
    "Beekeeper",
    "Florist",
  ],
  grid: [
    ["H", "O", "R", "T", "I", "C", "U", "L", "T", "U", "R", "I", "S", "T"],
    ["S", "N", "N", "B", "E", "E", "K", "E", "E", "P", "E", "R", "N", "F"],
    ["V", "N", "E", "R", "E", "G", "H", "E", "R", "D", "S", "M", "A", "N"],
    ["F", "E", "B", "N", "O", "S", "A", "F", "L", "O", "R", "I", "S", "T"],
    ["A", "S", "T", "F", "T", "P", "E", "R", "T", "R", "O", "E", "R", "E"],
    ["G", "Z", "V", "E", "I", "R", "E", "R", "D", "E", "E", "M", "U", "E"],
    ["R", "F", "O", "M", "R", "S", "E", "T", "A", "E", "E", "E", "E", "R"],
    ["O", "A", "O", "O", "R", "I", "H", "P", "M", "E", "N", "I", "E", "A"],
    ["N", "H", "E", "R", "K", "E", "N", "E", "R", "O", "O", "E", "N", "N"],
    ["O", "F", "E", "N", "E", "E", "T", "A", "R", "E", "E", "M", "R", "G"],
    ["M", "T", "M", "R", "I", "S", "E", "O", "R", "M", "N", "G", "R", "E"],
    ["I", "T", "M", "R", "S", "E", "T", "P", "P", "I", "A", "E", "P", "R"],
    ["S", "R", "C", "F", "M", "S", "R", "E", "E", "X", "A", "N", "U", "E"],
    ["T", "T", "I", "I", "S", "V", "C", "E", "R", "R", "E", "N", "E", "R"],
  ],
};

export const careersWordSearch8: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws8",
  title: "Careers & Employment: Puzzle 8",
  topic: "Earning & Growing Money",
  theme: "Creative Arts, Journalism & Performance",
  instruction: "Find the 10 creative arts and entertainment professions.",
  size: 14,
  words: [
    "Dancer",
    "Journalist",
    "Photographer",
    "Artist",
    "Singer",
    "Actor",
    "Reporter",
    "Poet",
    "Sculptor",
    "Musician",
  ],
  grid: [
    ["I", "S", "R", "E", "A", "C", "T", "T", "R", "P", "T", "H", "O", "E"],
    ["T", "N", "C", "R", "E", "T", "R", "O", "P", "E", "R", "I", "A", "R"],
    ["R", "O", "P", "U", "J", "T", "N", "M", "R", "R", "P", "P", "E", "P"],
    ["R", "T", "R", "R", "L", "O", "G", "T", "T", "T", "E", "O", "T", "I"],
    ["R", "I", "R", "T", "R", "P", "U", "I", "A", "R", "R", "U", "E", "T"],
    ["O", "T", "L", "T", "A", "O", "T", "R", "T", "E", "H", "N", "S", "T"],
    ["O", "S", "I", "N", "G", "E", "R", "O", "N", "U", "S", "I", "A", "R"],
    ["T", "A", "J", "D", "A", "N", "C", "E", "R", "A", "T", "N", "S", "E"],
    ["A", "O", "A", "R", "S", "D", "O", "I", "P", "R", "L", "D", "T", "O"],
    ["C", "E", "A", "R", "M", "O", "A", "C", "A", "T", "R", "I", "S", "N"],
    ["T", "A", "T", "E", "I", "P", "C", "O", "E", "S", "C", "H", "S", "S"],
    ["O", "T", "P", "H", "I", "U", "U", "C", "N", "I", "C", "C", "U", "T"],
    ["R", "R", "E", "H", "P", "A", "R", "G", "O", "T", "O", "H", "P", "T"],
    ["A", "N", "A", "I", "C", "I", "S", "U", "M", "S", "U", "T", "H", "A"],
  ],
};

export const careersWordSearch9: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws9",
  title: "Careers & Employment: Puzzle 9",
  topic: "Earning & Growing Money",
  theme: "Public Service, Law & Security",
  instruction: "Find the 10 public service and law enforcement careers.",
  size: 14,
  words: [
    "Cashier",
    "Politician",
    "Manager",
    "Coach",
    "Judge",
    "Accountant",
    "Librarian",
    "Police",
    "Soldier",
    "Detective",
  ],
  grid: [
    ["L", "C", "L", "E", "T", "R", "B", "H", "N", "A", "N", "P", "A", "E"],
    ["I", "H", "L", "R", "N", "C", "A", "A", "D", "I", "H", "G", "I", "V"],
    ["A", "P", "R", "C", "T", "O", "I", "N", "S", "O", "C", "N", "G", "I"],
    ["R", "O", "E", "H", "D", "R", "E", "M", "E", "A", "A", "A", "T", "T"],
    ["P", "L", "S", "C", "A", "S", "H", "I", "E", "R", "O", "N", "J", "C"],
    ["O", "I", "L", "R", "I", "O", "E", "H", "T", "R", "C", "A", "U", "E"],
    ["E", "T", "B", "O", "C", "L", "R", "E", "K", "N", "A", "B", "D", "T"],
    ["S", "I", "S", "I", "N", "E", "O", "V", "R", "T", "A", "C", "G", "E"],
    ["L", "C", "L", "P", "C", "R", "C", "P", "K", "R", "T", "A", "E", "D"],
    ["O", "I", "M", "A", "N", "A", "G", "E", "R", "O", "A", "I", "U", "O"],
    ["T", "A", "V", "P", "R", "E", "I", "D", "L", "O", "S", "A", "E", "A"],
    ["S", "N", "C", "C", "R", "C", "A", "I", "T", "N", "T", "T", "N", "S"],
    ["I", "V", "J", "C", "I", "E", "L", "S", "S", "T", "O", "G", "I", "C"],
    ["A", "C", "C", "O", "U", "N", "T", "A", "N", "T", "R", "B", "N", "I"],
  ],
};

export const careersWordSearch10: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-careers-ws10",
  title: "Careers & Employment: Puzzle 10",
  topic: "Earning & Growing Money",
  theme: "Finance, Actuarial & Business Leaders",
  instruction: "Find the 12 business strategy, auditing, and corporate professions.",
  size: 14,
  words: [
    "Entrepreneur",
    "Retailer",
    "Trader",
    "Actuary",
    "Marketer",
    "Executive",
    "Investor",
    "Planner",
    "Broker",
    "Economist",
    "Secretary",
    "Auditor",
  ],
  grid: [
    ["M", "A", "R", "K", "E", "T", "E", "R", "R", "B", "R", "E", "T", "P"],
    ["L", "E", "E", "T", "E", "C", "E", "A", "A", "R", "S", "V", "R", "R"],
    ["E", "E", "R", "A", "P", "B", "R", "E", "U", "O", "E", "I", "U", "C"],
    ["Y", "P", "Y", "C", "R", "C", "A", "T", "C", "K", "C", "T", "E", "R"],
    ["V", "P", "S", "N", "E", "N", "S", "P", "C", "E", "R", "U", "N", "R"],
    ["R", "N", "E", "R", "K", "R", "R", "M", "L", "R", "E", "C", "E", "X"],
    ["V", "N", "R", "E", "T", "A", "I", "L", "E", "R", "T", "E", "R", "R"],
    ["T", "R", "A", "D", "E", "R", "T", "I", "T", "I", "A", "X", "P", "O"],
    ["E", "C", "O", "N", "O", "M", "I", "S", "T", "C", "R", "E", "E", "T"],
    ["R", "O", "T", "I", "D", "U", "A", "R", "O", "T", "Y", "L", "R", "S"],
    ["I", "S", "P", "L", "A", "N", "N", "E", "R", "U", "A", "C", "T", "E"],
    ["R", "A", "A", "R", "T", "Y", "R", "A", "U", "T", "C", "A", "N", "V"],
    ["R", "I", "M", "R", "S", "I", "O", "E", "R", "O", "R", "L", "E", "N"],
    ["E", "O", "R", "V", "E", "E", "I", "R", "I", "R", "D", "R", "A", "I"],
  ],
};

export const careersQuiz1: QuizPuzzle = {
  type: "quiz",
  id: "eg-careers-quiz1",
  title: "Careers & Employment: Quiz 1",
  topic: "Earning & Growing Money",
  instruction: "Test your knowledge on CVs, interviews, internships, and work contracts.",
  questions: [
    {
      id: 1,
      question: "A document that lists your education, skills, and work experience to show an employer who you are is called a?",
      options: ["Contract", "CV (Curriculum Vitae)", "Salary Scale", "Application"],
      correctIndex: 1,
      explanation: "A CV summarizes your qualifications, achievements, and career history for job applications.",
    },
    {
      id: 2,
      question: "Before getting a job, you usually attend a meeting where you answer questions to see if you are a good fit. This is an?",
      options: ["Internship", "Induction", "Interview", "Apprenticeship"],
      correctIndex: 2,
      explanation: "Job interviews allow employers to evaluate candidates' communication, character, and skills.",
    },
    {
      id: 3,
      question: "If you are a student or a recent graduate working for a short time to gain experience sometimes without pay, you are doing an?",
      options: ["Hire", "Application", "Promotion", "Internship"],
      correctIndex: 3,
      explanation: "Internships provide hands-on workplace training and professional networking opportunities.",
    },
    {
      id: 4,
      question: "A person who gives you a job and pays you for your work is your ___, while you are their ___.",
      options: [
        "Employer / Employee",
        "Professional / Freelancer",
        "Leader / Intern",
        "Mentor / Talent",
      ],
      correctIndex: 0,
      explanation: "The employer hires and provides remuneration; the employee performs assigned duties.",
    },
    {
      id: 5,
      question: "When you work for yourself and handle different projects for various clients instead of one boss, you are a?",
      options: ["Apprentice", "Freelancer", "Manager", "Trainee"],
      correctIndex: 1,
      explanation: "Freelancers are self-employed professionals contracting their expertise across multiple clients.",
    },
    {
      id: 6,
      question: "If you perform very well at your job and are given a more senior role with more responsibility, you have earned a?",
      options: ["Commission", "Bonus", "Promotion", "Qualification"],
      correctIndex: 2,
      explanation: "Promotions recognize merit with elevated rank, greater responsibility, and increased pay.",
    },
    {
      id: 7,
      question: "The specific set of abilities you have, like coding, cooking, or public speaking, is known as your?",
      options: ["Contract", "Salary Scale", "Workplace", "Skillset"],
      correctIndex: 3,
      explanation: "Your skillset encompasses both hard technical abilities and soft interpersonal strengths.",
    },
    {
      id: 8,
      question: "The legal agreement that you sign with your employer which outlines your duties and pay is a?",
      options: ["Contract", "Bonus", "Training", "CV"],
      correctIndex: 0,
      explanation: "An employment contract establishes the binding terms, working hours, benefits, and duties.",
    },
    {
      id: 9,
      question: "Degrees, diplomas, or certificates that prove you have studied and mastered a specific subject are your?",
      options: ["Skillsets", "Qualifications", "Salaries", "Talents"],
      correctIndex: 1,
      explanation: "Academic qualifications certify formal training and mastery in a specialized field.",
    },
  ],
};

export const careersQuiz2: QuizPuzzle = {
  type: "quiz",
  id: "eg-careers-quiz2",
  title: "Careers & Employment: Quiz 2",
  topic: "Earning & Growing Money",
  instruction: "Match various professional specializations with their primary workplace functions.",
  questions: [
    {
      id: 1,
      question: "Which professional is responsible for designing the plan or blueprint of a new building like a skyscraper or a house?",
      options: ["Welder", "Painter", "Architect", "Plumber"],
      correctIndex: 2,
      explanation: "Architects create the structural blueprints, aesthetic designs, and safety specs for buildings.",
    },
    {
      id: 2,
      question: "Which healthcare professional is specially trained to take care of and treat sick animals?",
      options: ["Pharmacist", "Doctor", "Dentist", "Vet"],
      correctIndex: 3,
      explanation: "Veterinarians care for livestock, domestic pets, and wildlife health.",
    },
    {
      id: 3,
      question: "A person who starts their own business, like a new shop or a tech company, to solve problems and make a profit is an?",
      options: ["Entrepreneur", "Auditor", "Manager", "Secretary"],
      correctIndex: 0,
      explanation: "Entrepreneurs take calculated risks to create enterprises that deliver value and create jobs.",
    },
    {
      id: 4,
      question: "Talented singers, dancers, or painters, fall under which general career category?",
      options: ["Scientist", "Artist", "Technician", "Public Service"],
      correctIndex: 1,
      explanation: "Artists create aesthetic, visual, musical, and expressive cultural works.",
    },
    {
      id: 5,
      question: "Which specialist would you visit if you needed to fix a leaking pipe or a broken tap in the kitchen?",
      options: ["Surveyor", "Carpenter", "Plumber", "Electrician"],
      correctIndex: 2,
      explanation: "Plumbers install and repair water supply, drainage, and piping systems.",
    },
    {
      id: 6,
      question: "A professional who works protecting wildlife in national parks from poachers, is employed as a?",
      options: ["Forester", "Gardener", "Botanist", "Ranger"],
      correctIndex: 3,
      explanation: "KWS Game Rangers safeguard Kenya's national parks, endangered wildlife, and ecosystems.",
    },
    {
      id: 7,
      question: "Which professional works in a courtroom to help a judge make fair decisions based on the law?",
      options: ["Lawyer", "Banker", "Detective", "Journalist"],
      correctIndex: 0,
      explanation: "Lawyers and advocates represent legal parties and argue cases before magistrates and judges.",
    },
    {
      id: 8,
      question: "A person who flies aeroplanes and navigates them safely across the world is a?",
      options: ["Engineer", "Pilot", "Mechanic", "Driver"],
      correctIndex: 1,
      explanation: "Aviation pilots operate commercial airliners and cargo planes globally.",
    },
    {
      id: 9,
      question: "Which career involves writing news stories and reporting on important events for the TV or newspapers?",
      options: ["Poet", "Animator", "Journalist", "Blogger"],
      correctIndex: 2,
      explanation: "Journalists investigate, interview, and report news stories to keep the public informed.",
    },
    {
      id: 10,
      question: "If you are an expert at managing money, checking bank accounts, and helping people save, you are a:",
      options: ["Cashier", "Trader", "Retailer", "Banker"],
      correctIndex: 3,
      explanation: "Bankers advise clients on deposits, credit facilities, mortgages, and wealth management.",
    },
  ],
};
