import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const earningWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-earning-ws1",
  title: "Sources of Income: Word Search",
  topic: "Young Hustler",
  theme: "Earned, Passive, and Portfolio Income Streams",
  instruction: "Find the 14 words describing active wages, freelancing, and passive earnings.",
  size: 14,
  words: [
    "BONUS",
    "COMMISSION",
    "DIVIDENDS",
    "EARNED INCOME",
    "FREELANCING",
    "INTEREST",
    "OVERTIME",
    "PASSIVE INCOME",
    "PROFIT",
    "RENTAL",
    "ROYALTIES",
    "SALARY",
    "STIPEND",
    "WAGES",
  ],
  grid: [
    ["E", "A", "R", "N", "E", "D", "I", "N", "C", "O", "M", "E", "A", "B"],
    ["P", "A", "S", "S", "I", "V", "E", "I", "N", "C", "O", "M", "E", "C"],
    ["F", "R", "E", "E", "L", "A", "N", "C", "I", "N", "G", "D", "E", "F"],
    ["C", "O", "M", "M", "I", "S", "S", "I", "O", "N", "B", "O", "N", "U"],
    ["D", "I", "V", "I", "D", "E", "N", "D", "S", "S", "A", "L", "A", "S"],
    ["R", "O", "Y", "A", "L", "T", "I", "E", "S", "P", "R", "O", "F", "R"],
    ["O", "V", "E", "R", "T", "I", "M", "E", "I", "N", "T", "E", "R", "Y"],
    ["R", "E", "N", "T", "A", "L", "S", "T", "I", "P", "E", "N", "D", "I"],
    ["W", "A", "G", "E", "S", "I", "N", "T", "E", "R", "E", "S", "T", "T"],
    ["G", "I", "G", "E", "C", "O", "N", "O", "M", "Y", "P", "A", "T", "H"],
    ["S", "I", "D", "E", "H", "U", "S", "T", "L", "E", "F", "U", "N", "D"],
    ["C", "A", "S", "H", "F", "L", "O", "W", "A", "S", "S", "E", "T", "S"],
    ["E", "N", "T", "E", "R", "P", "R", "I", "S", "E", "G", "O", "A", "L"],
    ["V", "A", "L", "U", "E", "C", "R", "E", "A", "T", "I", "O", "N", "S"],
  ],
};

export const earningQuiz: QuizPuzzle = {
  type: "quiz",
  id: "eg-earning-quiz",
  title: "Sources of Income Quiz",
  topic: "Young Hustler",
  instruction: "Understand the differences between active wages, freelance contracts, and royalties.",
  questions: [
    {
      id: 1,
      question: "What is the key distinction between 'Earned Income' and 'Passive Income'?",
      options: [
        "Earned income requires trading your direct time and labor (wages/salary); passive income flows from assets (dividends, rent, book royalties) with minimal ongoing labor",
        "Earned income is fake; passive income is real",
        "Earned income only comes from playing football",
        "Passive income is illegal",
      ],
      correctIndex: 0,
      explanation:
        "Earned income is active (wages/salary); passive income is generated by owning productive assets.",
    },
    {
      id: 2,
      question: "What is a 'Dividend'?",
      options: [
        "A portion of a company's corporate profits distributed to its shareholders",
        "A subtraction problem on a math exam",
        "A fine charged by the traffic police",
        "Money lost when shopping",
      ],
      correctIndex: 0,
      explanation:
        "When profitable companies succeed, they pay cash dividends to reward shareholders who hold their stock.",
    },
    {
      id: 3,
      question: "What are 'Royalties'?",
      options: [
        "Payments made to creators (authors, musicians, inventors) each time their copyrighted work or patent is used or sold",
        "Money given only to kings and queens",
        "A tax on crowns and jewellery",
        "A medal awarded at sports day",
      ],
      correctIndex: 0,
      explanation:
        "Royalties reward intellectual property, generating recurring passive income for creative artists and inventors.",
    },
  ],
};
