import { WordSearchPuzzle, QuizPuzzle, CrosswordPuzzle } from "../types";

export const earningWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-earning-ws1",
  title: "Earning: Puzzle 1",
  topic: "Earning & Growing Money",
  theme: "Sources of Active & Passive Income",
  instruction: "Find the 10 sources of income in the grid.",
  size: 14,
  words: [
    "Interest",
    "Tips",
    "Allowance",
    "Gift",
    "Commission",
    "Rent",
    "Salary",
    "Wage",
    "Dividends",
    "Bonus",
  ],
  grid: [
    ["I", "U", "A", "C", "D", "I", "V", "I", "D", "E", "N", "D", "S", "W"],
    ["T", "I", "D", "G", "N", "M", "G", "N", "I", "N", "T", "E", "P", "S"],
    ["E", "C", "N", "A", "W", "O", "L", "L", "A", "Y", "T", "I", "O", "L"],
    ["O", "A", "T", "I", "D", "L", "F", "A", "O", "C", "S", "T", "E", "C"],
    ["O", "S", "S", "I", "O", "R", "D", "E", "A", "Y", "S", "I", "O", "O"],
    ["I", "I", "G", "D", "P", "G", "I", "M", "N", "E", "G", "F", "A", "M"],
    ["L", "R", "D", "D", "Y", "S", "E", "W", "R", "S", "R", "U", "A", "M"],
    ["C", "L", "D", "E", "G", "I", "W", "E", "W", "E", "L", "S", "E", "I"],
    ["Y", "O", "C", "W", "A", "S", "T", "L", "F", "L", "G", "I", "G", "S"],
    ["M", "R", "A", "E", "A", "N", "P", "N", "N", "L", "I", "S", "A", "S"],
    ["L", "L", "E", "L", "I", "N", "S", "L", "C", "I", "B", "I", "W", "I"],
    ["A", "E", "A", "N", "S", "U", "E", "W", "E", "O", "A", "C", "I", "O"],
    ["C", "R", "D", "T", "T", "D", "L", "W", "E", "I", "A", "E", "Y", "N"],
    ["Y", "A", "E", "G", "I", "F", "T", "S", "B", "O", "N", "U", "S", "I"],
  ],
};

export const earningWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-earning-ws2",
  title: "Earning: Puzzle 2",
  topic: "Earning & Growing Money",
  theme: "Side Hustles, Royalties & Benefits",
  instruction: "Find the 11 terms related to gig earnings and retirement security.",
  size: 14,
  words: [
    "Pension",
    "Royalties",
    "Social Security",
    "Lottery",
    "Side Hustle",
    "Cash Back",
    "Freelance",
    "Pocket Money",
    "Business",
    "Grants",
    "Prize",
  ],
  grid: [
    ["G", "D", "C", "S", "S", "E", "N", "I", "S", "U", "B", "N", "Y", "S"],
    ["L", "E", "S", "E", "C", "O", "R", "T", "T", "Y", "S", "Z", "E", "O"],
    ["L", "P", "L", "L", "E", "U", "N", "C", "R", "D", "L", "T", "N", "C"],
    ["A", "R", "O", "U", "N", "A", "T", "E", "G", "R", "H", "E", "O", "I"],
    ["I", "I", "K", "B", "R", "E", "T", "E", "R", "O", "R", "C", "M", "A"],
    ["L", "Z", "N", "G", "D", "T", "N", "T", "B", "Y", "H", "N", "T", "L"],
    ["N", "E", "E", "S", "O", "O", "K", "U", "E", "A", "E", "A", "E", "S"],
    ["S", "Z", "R", "L", "I", "L", "L", "A", "E", "L", "I", "L", "K", "E"],
    ["E", "E", "L", "S", "R", "Y", "K", "Y", "L", "T", "R", "E", "C", "C"],
    ["B", "E", "N", "T", "A", "L", "T", "E", "I", "I", "C", "E", "O", "U"],
    ["E", "E", "R", "Y", "N", "B", "C", "E", "N", "E", "S", "R", "P", "R"],
    ["P", "N", "C", "A", "A", "T", "E", "Y", "R", "S", "C", "F", "C", "I"],
    ["E", "L", "T", "S", "U", "H", "E", "D", "I", "S", "Y", "E", "T", "T"],
    ["B", "O", "G", "U", "K", "C", "A", "B", "H", "S", "A", "C", "S", "Y"],
  ],
};

export const earningQuiz: QuizPuzzle = {
  type: "quiz",
  id: "eg-earning-quiz",
  title: "Earning: Quiz",
  topic: "Earning & Growing Money",
  instruction: "Test your knowledge on wages, salaries, bonuses, and side hustles.",
  questions: [
    {
      id: 1,
      question: "If you have a permanent job and receive a fixed amount of money every month, what is this payment called?",
      options: ["Commission", "Salary", "Wage", "Bonus"],
      correctIndex: 1,
      explanation: "A salary is a fixed regular payment, typically agreed upon in an annual contract and paid monthly.",
    },
    {
      id: 2,
      question: "What do we call the extra money given to an employee as a reward for good performance, usually at the end of the year?",
      options: ["Tip", "Pension", "Bonus", "Pocket Money"],
      correctIndex: 2,
      explanation: "A performance bonus rewards employees who surpass targets or contribute to company profits.",
    },
    {
      id: 3,
      question: "When a salesperson earns a percentage of the total sales they make, that income is called?",
      options: ["Side Hustle", "Interest", "Rent", "Commission"],
      correctIndex: 3,
      explanation: "Commission is incentive-based pay tied directly to the value of products or services sold.",
    },
    {
      id: 4,
      question: "If you own a house and let someone else live in it in exchange for a monthly fee, you are earning?",
      options: ["Rent", "Dividends", "Social Security", "Cash back"],
      correctIndex: 0,
      explanation: "Rental income is earned by leasing real estate property to tenants.",
    },
    {
      id: 5,
      question: "When you save money in a bank account, the bank pays you extra money over time called?",
      options: ["Grants", "Interest", "Royalties", "Tips"],
      correctIndex: 1,
      explanation: "Interest is the rate paid by financial institutions to depositors for holding funds in savings accounts.",
    },
    {
      id: 6,
      question: "Which term describes a small amount of money given by parents to children for their personal use?",
      options: ["Salary", "Pension", "Pocket Money", "Allowance"],
      correctIndex: 2,
      explanation: "Pocket money teaches children money management and budgeting skills at an early age.",
    },
    {
      id: 7,
      question: "Jane has a full-time job but also sells clothes on the weekends to earn extra cash, that extra job is a?",
      options: ["Social Security", "Wage", "Dividend", "Side Hustle"],
      correctIndex: 3,
      explanation: "A side hustle is secondary employment or freelancing undertaken to augment primary income.",
    },
    {
      id: 8,
      question: "Authors, musicians, and inventors earn a special type of income every time someone buys or uses their work known as?",
      options: ["Royalties", "Prizes", "Cash back", "Commission"],
      correctIndex: 0,
      explanation: "Royalties are payments made to creators for the licensed use of their intellectual property.",
    },
    {
      id: 9,
      question: "After someone retires from working for many years, the regular monthly payment they receive to support themselves is called?",
      options: ["Bonus", "Pension", "Gift", "Wage"],
      correctIndex: 1,
      explanation: "Pension funds (like NSSF) provide steady retirement payouts accumulated over a career.",
    },
    {
      id: 10,
      question: "If you win a competition or a school challenge, the money or trophy you receive is called a?",
      options: ["Commission", "Salary", "Prize", "Pension"],
      correctIndex: 2,
      explanation: "A prize is awarded as recognition and reward for exceptional competition performance.",
    },
  ],
};

export const earningCrossword1: CrosswordPuzzle = {
  type: "crossword",
  id: "eg-earning-cw1",
  title: "Types of Income: Puzzle 1",
  topic: "Earning & Growing Money",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 18,
  cols: 8,
  wordBank: ["Pay", "Wage", "Tip", "Commission", "Salary", "Bonus", "Allowance", "Cash"],
  acrossClues: [
    { number: 2, clue: "A fixed regular payment typically paid on a monthly basis by an employer.", answer: "SALARY", row: 4, col: 2, direction: "across" },
    { number: 5, clue: "Payment based on the number of hours an employee works or days completed, common for manual jobs.", answer: "WAGE", row: 6, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 2, clue: "A set amount of money given by a parent/guardian to their child for specific needs, like school fare, airtime or lunch.", answer: "ALLOWANCE", row: 4, col: 5, direction: "down" },
    { number: 3, clue: "That extra money an employee gets at the end of the year for hitting a big sales target.", answer: "BONUS", row: 0, col: 2, direction: "down" },
    { number: 4, clue: "Some additional money left for a helpful waiter at a local Java, or a nail tech for excellent service.", answer: "TIP", row: 15, col: 0, direction: "down" },
  ],
};

export const earningCrossword2: CrosswordPuzzle = {
  type: "crossword",
  id: "eg-earning-cw2",
  title: "Types of Income: Puzzle 2",
  topic: "Earning & Growing Money",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 12,
  cols: 12,
  wordBank: ["Dividend", "Cheque", "Gift", "Commission", "Rent", "Interest"],
  acrossClues: [
    { number: 3, clue: "Money earned by a salesperson for every item sold; for example, an Mpesa agent's profit.", answer: "COMMISSION", row: 2, col: 2, direction: "across" },
    { number: 5, clue: "A share of the profits paid out to people who own stock in companies like Safaricom or KCB.", answer: "DIVIDEND", row: 4, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 1, clue: "The money you receive if you own a building and let other people use it either as a house or a shop.", answer: "RENT", row: 0, col: 11, direction: "down" },
    { number: 2, clue: "Money given to you for a special occasion e.g. on your birthday.", answer: "GIFT", row: 1, col: 9, direction: "down" },
    { number: 4, clue: "The \"growth\" money you earn just for keeping your savings in a bank account or a Sacco for a given period of time.", answer: "INTEREST", row: 4, col: 1, direction: "down" },
  ],
};

export const earningCrossword3: CrosswordPuzzle = {
  type: "crossword",
  id: "eg-earning-cw3",
  title: "Types of Income: Puzzle 3",
  topic: "Earning & Growing Money",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 13,
  cols: 11,
  wordBank: ["Salary", "Prize", "Grants", "Charity", "Hustle", "Business", "Pocket Money", "Freelance"],
  acrossClues: [
    { number: 3, clue: "Working on different projects for various clients, such as doing graphic design or academic writing online.", answer: "FREELANCE", row: 4, col: 2, direction: "across" },
    { number: 4, clue: "Income earned from selling goods or services, like running a small kiosk or an online shop.", answer: "BUSINESS", row: 6, col: 0, direction: "across" },
    { number: 5, clue: "A sum of money given by an organization or government to a specific person, for a particular purpose, which does not need to be repaid.", answer: "GRANTS", row: 8, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 1, clue: "Small amounts given by parents for personal spending on things like snacks or data.", answer: "POCKETMONEY", row: 2, col: 9, direction: "down" },
    { number: 2, clue: "What you win for coming first in a competition that sometimes involves money.", answer: "PRIZE", row: 0, col: 4, direction: "down" },
  ],
};

export const earningCrossword4: CrosswordPuzzle = {
  type: "crossword",
  id: "eg-earning-cw4",
  title: "Types of Income: Puzzle 4",
  topic: "Earning & Growing Money",
  instruction: "Fill the white squares with the correct financial terms.",
  rows: 13,
  cols: 16,
  wordBank: ["Revenue", "Side Hustle", "Cashback", "Royalties", "Tax", "Bank", "Pension", "Social Security"],
  acrossClues: [
    { number: 4, clue: "A government safety net that provides financial support to those in need or the elderly.", answer: "SOCIALSECURITY", row: 4, col: 2, direction: "across" },
    { number: 5, clue: "A secondary job you do after work to earn extra cash, like selling thrifted clothes on Instagram.", answer: "SIDEHUSTLE", row: 6, col: 0, direction: "across" },
  ],
  downClues: [
    { number: 1, clue: "Payments made to creators for the ongoing use of their intellectual property.", answer: "ROYALTIES", row: 4, col: 12, direction: "down" },
    { number: 2, clue: "A small percentage of money returned to your wallet after paying for shopping via apps like Loop at partner outlets.", answer: "CASHBACK", row: 4, col: 10, direction: "down" },
    { number: 3, clue: "Regular payments received by retirees after they stop working, often from the NSSF.", answer: "PENSION", row: 0, col: 13, direction: "down" },
  ],
};

export const earningQuiz2: QuizPuzzle = {
  type: "quiz",
  id: "eg-earning-quiz2",
  title: "Types of Income: Quiz 2",
  topic: "Earning & Growing Money",
  instruction: "Interest, grants, royalties, and passive income from the book.",
  questions: [
    { id: 1, question: "Otieno works 8 hours a day at a cyber café and is paid every evening based on hours worked. This income is a?", options: ["Royalty", "Salary", "Dividend", "Wage"], correctIndex: 3, explanation: "Wages are paid by the hour or day." },
    { id: 2, question: "Wanjiku’s sister receives the same amount on the 28th of every month. She earns a?", options: ["Salary", "Commission", "Grant", "Tip"], correctIndex: 0, explanation: "A salary is a fixed monthly payment." },
    { id: 3, question: "Moraa sells thrifted clothes on TikTok. After costs, the extra she keeps is her?", options: ["Interest", "Profit", "Royalty", "Pension"], correctIndex: 1, explanation: "Profit is revenue minus costs." },
    { id: 4, question: "When Kibet pays with Loop and gets 10% back, that money is called?", options: ["Allowance", "Interest", "Cashback", "Loyalty Reward"], correctIndex: 2, explanation: "Cashback returns a slice of what you spent." },
    { id: 5, question: "A musician earns money every time her song is played on radio. That is?", options: ["Wage", "Pension", "Commission", "Royalties"], correctIndex: 3, explanation: "Royalties pay creators when their work is used." },
    { id: 6, question: "If Mutua saves 500 shillings and later finds 550, the extra 50 shillings is?", options: ["Interest", "Pocket Money", "Prize", "Dividend"], correctIndex: 0, explanation: "The bank paid interest on his savings." },
    { id: 7, question: "Which of these is a passive form of income because Achieng doesn’t have to work every day to earn it?", options: ["Salary", "Rental Income", "YouTube Videos", "Tips"], correctIndex: 1, explanation: "Rent can keep arriving after the house is already let." },
    { id: 8, question: "Baraka receives KES 50,000 from the government to start a repair shop. This one-time support is a?", options: ["Bonus", "Cashback", "Grant", "Salary"], correctIndex: 2, explanation: "A grant is support you do not repay like a loan." },
  ],
};
