import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const earningWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-earning-ws1",
  title: "Earning: Puzzle 1",
  topic: "Earning & Growing Money",
  theme: "Sources of Active & Passive Income",
  instruction: "Find the 10 sources of income in the grid.",
  size: 14,
  words: [
    "Interest",
    "Tips",
    "Allowance",
    "Gift",
    "Commission",
    "Rent",
    "Salary",
    "Wage",
    "Dividends",
    "Bonus",
  ],
  grid: [
    ["I", "U", "A", "C", "D", "I", "V", "I", "D", "E", "N", "D", "S", "W"],
    ["T", "I", "D", "G", "N", "M", "G", "N", "I", "N", "T", "E", "P", "S"],
    ["E", "C", "N", "A", "W", "O", "L", "L", "A", "Y", "T", "I", "O", "L"],
    ["O", "A", "T", "I", "D", "L", "F", "A", "O", "C", "S", "T", "E", "C"],
    ["O", "S", "S", "I", "O", "R", "D", "E", "A", "Y", "S", "I", "O", "O"],
    ["I", "I", "G", "D", "P", "G", "I", "M", "N", "E", "G", "F", "A", "M"],
    ["L", "R", "D", "D", "Y", "S", "E", "W", "R", "S", "R", "U", "A", "M"],
    ["C", "L", "D", "E", "G", "I", "W", "E", "W", "E", "L", "S", "E", "I"],
    ["Y", "O", "C", "W", "A", "S", "T", "L", "F", "L", "G", "I", "G", "S"],
    ["M", "R", "A", "E", "A", "N", "P", "N", "N", "L", "I", "S", "A", "S"],
    ["L", "L", "E", "L", "I", "N", "S", "L", "C", "I", "B", "I", "W", "I"],
    ["A", "E", "A", "N", "S", "U", "E", "W", "E", "O", "A", "C", "I", "O"],
    ["C", "R", "D", "T", "T", "D", "L", "W", "E", "I", "A", "E", "Y", "N"],
    ["Y", "A", "E", "G", "I", "F", "T", "S", "B", "O", "N", "U", "S", "I"],
  ],
};

export const earningWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-earning-ws2",
  title: "Earning: Puzzle 2",
  topic: "Earning & Growing Money",
  theme: "Side Hustles, Royalties & Benefits",
  instruction: "Find the 11 terms related to gig earnings and retirement security.",
  size: 14,
  words: [
    "Pension",
    "Royalties",
    "Social Security",
    "Lottery",
    "Side Hustle",
    "Cash Back",
    "Freelance",
    "Pocket Money",
    "Business",
    "Grants",
    "Prize",
  ],
  grid: [
    ["G", "D", "C", "S", "S", "E", "N", "I", "S", "U", "B", "N", "Y", "S"],
    ["L", "E", "S", "E", "C", "O", "R", "T", "T", "Y", "S", "Z", "E", "O"],
    ["L", "P", "L", "L", "E", "U", "N", "C", "R", "D", "L", "T", "N", "C"],
    ["A", "R", "O", "U", "N", "A", "T", "E", "G", "R", "H", "E", "O", "I"],
    ["I", "I", "K", "B", "R", "E", "T", "E", "R", "O", "R", "C", "M", "A"],
    ["L", "Z", "N", "G", "D", "T", "N", "T", "B", "Y", "H", "N", "T", "L"],
    ["N", "E", "E", "S", "O", "O", "K", "U", "E", "A", "E", "A", "E", "S"],
    ["S", "Z", "R", "L", "I", "L", "L", "A", "E", "L", "I", "L", "K", "E"],
    ["E", "E", "L", "S", "R", "Y", "K", "Y", "L", "T", "R", "E", "C", "C"],
    ["B", "E", "N", "T", "A", "L", "T", "E", "I", "I", "C", "E", "O", "U"],
    ["E", "E", "R", "Y", "N", "B", "C", "E", "N", "E", "S", "R", "P", "R"],
    ["P", "N", "C", "A", "A", "T", "E", "Y", "R", "S", "C", "F", "C", "I"],
    ["E", "L", "T", "S", "U", "H", "E", "D", "I", "S", "Y", "E", "T", "T"],
    ["B", "O", "G", "U", "K", "C", "A", "B", "H", "S", "A", "C", "S", "Y"],
  ],
};

export const earningQuiz: QuizPuzzle = {
  type: "quiz",
  id: "eg-earning-quiz",
  title: "Earning: Quiz",
  topic: "Earning & Growing Money",
  instruction: "Test your knowledge on wages, salaries, bonuses, and side hustles.",
  questions: [
    {
      id: 1,
      question: "If you have a permanent job and receive a fixed amount of money every month, what is this payment called?",
      options: ["Wage", "Salary", "Bonus", "Commission"],
      correctIndex: 1,
      explanation: "A salary is a fixed regular payment, typically agreed upon in an annual contract and paid monthly.",
    },
    {
      id: 2,
      question: "What do we call the extra money given to an employee as a reward for good performance, usually at the end of the year?",
      options: ["Tip", "Bonus", "Pension", "Pocket Money"],
      correctIndex: 1,
      explanation: "A performance bonus rewards employees who surpass targets or contribute to company profits.",
    },
    {
      id: 3,
      question: "When a salesperson earns a percentage of the total sales they make, that income is called?",
      options: ["Interest", "Rent", "Commission", "Side Hustle"],
      correctIndex: 2,
      explanation: "Commission is incentive-based pay tied directly to the value of products or services sold.",
    },
    {
      id: 4,
      question: "If you own a house and let someone else live in it in exchange for a monthly fee, you are earning?",
      options: ["Rent", "Dividends", "Social Security", "Cash back"],
      correctIndex: 0,
      explanation: "Rental income is earned by leasing real estate property to tenants.",
    },
    {
      id: 5,
      question: "When you save money in a bank account, the bank pays you extra money over time called?",
      options: ["Interest", "Royalties", "Grants", "Tips"],
      correctIndex: 0,
      explanation: "Interest is the rate paid by financial institutions to depositors for holding funds in savings accounts.",
    },
    {
      id: 6,
      question: "Which term describes a small amount of money given by parents to children for their personal use?",
      options: ["Salary", "Pocket Money", "Pension", "Allowance"],
      correctIndex: 1,
      explanation: "Pocket money teaches children money management and budgeting skills at an early age.",
    },
    {
      id: 7,
      question: "Jane has a full-time job but also sells clothes on the weekends to earn extra cash, that extra job is a?",
      options: ["Side Hustle", "Social Security", "Dividend", "Wage"],
      correctIndex: 0,
      explanation: "A side hustle is secondary employment or freelancing undertaken to augment primary income.",
    },
    {
      id: 8,
      question: "Authors, musicians, and inventors earn a special type of income every time someone buys or uses their work known as?",
      options: ["Royalties", "Prizes", "Cash back", "Commission"],
      correctIndex: 0,
      explanation: "Royalties are payments made to creators for the licensed use of their intellectual property.",
    },
    {
      id: 9,
      question: "After someone retires from working for many years, the regular monthly payment they receive to support themselves is called?",
      options: ["Pension", "Bonus", "Gift", "Wage"],
      correctIndex: 0,
      explanation: "Pension funds (like NSSF) provide steady retirement payouts accumulated over a career.",
    },
    {
      id: 10,
      question: "If you win a competition or a school challenge, the money or trophy you receive is called a?",
      options: ["Salary", "Prize", "Pension", "Commission"],
      correctIndex: 1,
      explanation: "A prize is awarded as recognition and reward for exceptional competition performance.",
    },
  ],
};
