import { WordSearchPuzzle, QuizPuzzle, ActivityPuzzle } from "../types";

export const entrepreneurshipWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-entrepreneur-ws1",
  title: "Entrepreneurship: Puzzle 1",
  topic: "Earning & Growing Money",
  theme: "Startup Foundations & Strategy",
  instruction: "Find the 10 core business and sales terms in the grid.",
  size: 14,
  words: [
    "Customer",
    "Strategy",
    "Sales",
    "Innovation",
    "Profit",
    "Inventory",
    "Hustle",
    "Market",
    "Retail",
    "Capital",
  ],
  grid: [
    ["M", "A", "R", "K", "E", "T", "R", "E", "M", "S", "P", "S", "N", "T"],
    ["R", "O", "S", "T", "S", "T", "H", "U", "S", "T", "L", "E", "I", "L"],
    ["R", "M", "S", "L", "S", "A", "T", "S", "E", "A", "I", "R", "L", "A"],
    ["A", "T", "S", "H", "O", "C", "C", "L", "R", "R", "S", "O", "A", "N"],
    ["I", "N", "V", "E", "N", "T", "O", "R", "Y", "A", "N", "T", "O", "I"],
    ["E", "T", "I", "F", "O", "R", "P", "T", "E", "I", "I", "T", "I", "A"],
    ["L", "N", "O", "I", "T", "A", "V", "O", "N", "N", "I", "L", "T", "T"],
    ["O", "S", "T", "R", "R", "P", "L", "T", "E", "E", "L", "O", "U", "S"],
    ["T", "V", "O", "I", "L", "C", "A", "P", "I", "T", "A", "L", "A", "T"],
    ["P", "R", "C", "U", "S", "T", "O", "M", "E", "R", "T", "L", "R", "T"],
    ["A", "I", "L", "R", "E", "T", "A", "I", "L", "A", "E", "T", "T", "M"],
    ["T", "S", "T", "U", "N", "R", "O", "I", "S", "S", "R", "I", "T", "V"],
    ["I", "S", "H", "Y", "I", "R", "A", "O", "S", "O", "A", "A", "E", "T"],
    ["S", "T", "R", "A", "T", "E", "G", "Y", "L", "S", "R", "V", "R", "N"],
  ],
};

export const entrepreneurshipWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-entrepreneur-ws2",
  title: "Entrepreneurship: Puzzle 2",
  topic: "Earning & Growing Money",
  theme: "Client Relations & Brand Launch",
  instruction: "Find the 10 branding and supplier terms.",
  size: 14,
  words: [
    "Client",
    "Startup",
    "Supplier",
    "Pitch",
    "Revenue",
    "Business",
    "Branding",
    "Entrepreneur",
    "Location",
    "Partnership",
  ],
  grid: [
    ["E", "I", "H", "I", "L", "O", "C", "A", "T", "I", "O", "N", "T", "R"],
    ["U", "P", "A", "R", "T", "N", "E", "R", "S", "H", "I", "P", "N", "R"],
    ["N", "A", "S", "S", "U", "P", "P", "L", "I", "E", "R", "E", "U", "S"],
    ["E", "N", "T", "R", "E", "P", "R", "E", "N", "E", "U", "R", "E", "N"],
    ["V", "I", "R", "R", "S", "N", "E", "H", "T", "B", "R", "I", "A", "B"],
    ["E", "B", "T", "T", "E", "U", "R", "S", "U", "R", "P", "S", "L", "R"],
    ["R", "C", "U", "H", "E", "T", "B", "S", "T", "A", "R", "T", "U", "P"],
    ["N", "L", "N", "S", "T", "R", "N", "R", "I", "N", "P", "R", "S", "E"],
    ["E", "I", "E", "A", "I", "I", "B", "E", "U", "D", "N", "E", "T", "U"],
    ["T", "E", "O", "P", "P", "N", "E", "P", "R", "I", "I", "A", "E", "L"],
    ["P", "N", "S", "U", "E", "S", "E", "N", "I", "N", "C", "N", "R", "T"],
    ["R", "T", "R", "D", "I", "R", "V", "S", "E", "G", "O", "R", "N", "I"],
    ["R", "E", "R", "I", "T", "T", "P", "P", "S", "B", "H", "S", "S", "R"],
    ["I", "N", "A", "P", "R", "S", "L", "T", "H", "C", "T", "I", "P", "R"],
  ],
};

export const entrepreneurshipWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-entrepreneur-ws3",
  title: "Entrepreneurship: Puzzle 3",
  topic: "Earning & Growing Money",
  theme: "Business Expansion & Permits",
  instruction: "Find the 10 business expansion and investor terms in the grid.",
  size: 14,
  words: [
    "Permit",
    "Wholesale",
    "Investor",
    "Expansion",
    "Networking",
    "Franchise",
    "Product",
    "Competitor",
    "Marketing",
    "Trade",
  ],
  grid: [
    ["T", "C", "U", "D", "O", "R", "P", "P", "T", "T", "R", "A", "D", "E"],
    ["P", "E", "R", "M", "I", "T", "I", "O", "S", "T", "N", "C", "E", "D"],
    ["U", "I", "N", "E", "E", "E", "X", "P", "A", "N", "S", "I", "O", "N"],
    ["G", "M", "A", "R", "K", "E", "T", "I", "N", "G", "A", "N", "S", "A"],
    ["X", "W", "H", "O", "L", "E", "S", "A", "L", "E", "A", "E", "A", "R"],
    ["A", "A", "F", "A", "I", "N", "H", "S", "P", "E", "V", "T", "F", "O"],
    ["N", "U", "N", "R", "C", "G", "T", "I", "L", "U", "P", "W", "O", "T"],
    ["N", "E", "D", "E", "A", "R", "M", "R", "M", "T", "G", "O", "I", "I"],
    ["E", "C", "R", "E", "P", "N", "W", "U", "N", "S", "S", "R", "O", "T"],
    ["O", "T", "O", "H", "N", "C", "C", "A", "S", "E", "N", "K", "P", "E"],
    ["N", "S", "I", "E", "D", "E", "C", "H", "N", "H", "E", "I", "R", "P"],
    ["E", "S", "W", "O", "T", "A", "D", "I", "I", "H", "L", "N", "P", "M"],
    ["I", "I", "N", "V", "E", "S", "T", "O", "R", "S", "N", "G", "R", "O"],
    ["I", "T", "R", "R", "G", "H", "P", "H", "W", "R", "E", "E", "E", "C"],
  ],
};

export const entrepreneurshipQuiz: QuizPuzzle = {
  type: "quiz",
  id: "eg-entrepreneur-quiz",
  title: "Entrepreneurship: Quiz",
  topic: "Earning & Growing Money",
  instruction: "Test your entrepreneurial acumen on capital, business plans, and pricing.",
  questions: [
    {
      id: 1,
      question: "An entrepreneur is someone who identifies a problem and starts a business to solve it while taking a financial?",
      options: ["Holiday", "Risk", "Nap", "Loan"],
      correctIndex: 1,
      explanation: "Entrepreneurs accept financial and operational risks in pursuit of creating valuable enterprises.",
    },
    {
      id: 2,
      question: "In Kenya, many small businesses start as a 'Jua Kali' enterprise. What does this Swahili term literally mean?",
      options: ["Cold wind", "Fierce sun", "Big market", "Hard work"],
      correctIndex: 1,
      explanation: "Jua Kali means 'fierce sun', reflecting Kenya's resilient informal artisans working in open-air markets.",
    },
    {
      id: 3,
      question: "What do we call the initial money used to start a business, such as buying equipment or stock?",
      options: ["Salary", "Debt", "Capital", "Change"],
      correctIndex: 2,
      explanation: "Startup capital is the seed money required to purchase initial inventory, tools, and licenses.",
    },
    {
      id: 4,
      question: "If a young entrepreneur sells handmade bracelets for 200 KES but spent 120 KES on beads, the 80 KES left over is called?",
      options: ["Profit", "Loss", "Revenue", "Expense"],
      correctIndex: 0,
      explanation: "Profit = Selling Price (KES 200) - Cost of Goods Sold (KES 120) = KES 80.",
    },
    {
      id: 5,
      question: "Which document acts as a 'map' for a business, describing its goals and how it plans to achieve them?",
      options: ["School Report", "Business Plan", "Shopping List", "Receipt"],
      correctIndex: 1,
      explanation: "A business plan details the target audience, product strategy, pricing model, and financial projections.",
    },
    {
      id: 6,
      question: "A side hustle is a common term in Kenya for a business that someone runs?",
      options: [
        "Only on holidays",
        "Alongside their main job or studies",
        "In a different country",
        "Only when it rains",
      ],
      correctIndex: 1,
      explanation: "Side hustles generate extra revenue while maintaining daytime school or career commitments.",
    },
    {
      id: 7,
      question: "What is the term for the people or other businesses that buy the products or services an entrepreneur offers?",
      options: ["Competitors", "Suppliers", "Customers", "Employees"],
      correctIndex: 2,
      explanation: "Customers provide the revenue that sustains and grows any commercial venture.",
    },
    {
      id: 8,
      question: "If you have a unique idea for a business, it is important to check your competition. This means looking at?",
      options: [
        "Other businesses selling similar things",
        "Your business partners",
        "The weather forecast",
        "Your bank balance",
      ],
      correctIndex: 0,
      explanation: "Market and competitor analysis helps you differentiate your product quality and pricing.",
    },
    {
      id: 9,
      question: "In entrepreneurship, 'Innovation' means?",
      options: [
        "Copying exactly what others do",
        "Creating new or better ways to do things",
        "Spending all your money at once",
        "Closing a business early",
      ],
      correctIndex: 1,
      explanation: "Innovation introduces superior designs, faster delivery, or improved customer experiences.",
    },
    {
      id: 10,
      question: "Many Kenyan entrepreneurs use mobile money to receive payments. What is the most famous platform used for this?",
      options: ["Tik Tok", "M-Pesa", "Instagram", "WhatsApp"],
      correctIndex: 1,
      explanation: "M-Pesa Till numbers (Buy Goods) and Paybill numbers power everyday commerce across Kenya.",
    },
  ],
};

export const photographerGigActivity: ActivityPuzzle = {
  type: "activity",
  id: "eg-photographer-gig",
  title: "Entrepreneurial Project: The Family Photographer Gig",
  topic: "Earning & Growing Money",
  subtype: "photographer_gig",
  instruction: "Design a neighborhood photography service, calculate startup costs, and package pricing.",
  config: {
    startupCost: 0,
    packages: [
      {
        id: "intro",
        name: "The 'Intro' Package",
        price: 1000,
        includes: "30-minute session + 5 edited digital photos + 2 physical prints",
        transportAndPrintingCost: 500,
        profit: 500,
      },
      {
        id: "family",
        name: "The 'Family Reunion' Package",
        price: 2500,
        includes: "60-minute session + 15 edited digital photos + 6 physical prints",
        transportAndPrintingCost: 1100,
        profit: 1400,
      },
    ],
    growthSteps: [
      "Inner Circle Marketing: Launch discount for friends & family in exchange for portfolio rights.",
      "Equipment Fund: Set aside 10% of every payment for future gear repairs and lens upgrades.",
    ],
  },
};
