import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const investingWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-investing-ws1",
  title: "Investing: Puzzle 1",
  topic: "Earning & Growing Money",
  theme: "Asset Classes & Portfolio Growth",
  instruction: "Find the 12 investment and portfolio terms in the grid.",
  size: 14,
  words: [
    "Dividend",
    "Return",
    "Risk",
    "Portfolio",
    "Interest",
    "Diversify",
    "Stock",
    "Allocation",
    "Asset",
    "Invest",
    "Principal",
    "Shares",
  ],
  grid: [
    ["I", "N", "T", "E", "R", "E", "S", "T", "O", "C", "I", "D", "E", "E"],
    ["N", "K", "I", "E", "A", "L", "L", "O", "C", "A", "T", "I", "O", "N"],
    ["R", "R", "R", "O", "I", "I", "C", "E", "I", "S", "N", "E", "R", "E"],
    ["E", "T", "R", "E", "A", "R", "H", "E", "S", "E", "N", "P", "T", "I"],
    ["O", "S", "N", "S", "T", "L", "E", "R", "O", "A", "L", "R", "N", "Y"],
    ["D", "H", "D", "T", "I", "U", "T", "O", "S", "N", "O", "I", "I", "F"],
    ["O", "A", "I", "L", "N", "R", "R", "N", "K", "V", "A", "N", "T", "I"],
    ["S", "R", "V", "O", "K", "U", "E", "N", "V", "E", "E", "C", "S", "S"],
    ["I", "E", "I", "A", "Y", "C", "R", "I", "S", "K", "P", "I", "P", "R"],
    ["N", "S", "D", "S", "V", "V", "O", "P", "I", "L", "A", "P", "C", "E"],
    ["E", "R", "E", "S", "C", "I", "A", "T", "C", "N", "D", "A", "C", "V"],
    ["I", "I", "N", "E", "D", "S", "V", "T", "S", "L", "C", "L", "R", "I"],
    ["I", "I", "D", "T", "P", "O", "R", "T", "F", "O", "L", "I", "O", "D"],
    ["T", "S", "E", "V", "N", "I", "R", "O", "V", "D", "D", "R", "R", "H"],
  ],
};

export const investingWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-investing-ws2",
  title: "Investing: Puzzle 2",
  topic: "Earning & Growing Money",
  theme: "Bonds, Real Estate & Compound Growth",
  instruction: "Find the 12 wealth building and compound growth vehicles.",
  size: 14,
  words: [
    "Loss",
    "Gain",
    "Business",
    "Inflation",
    "Education",
    "Bond",
    "Capital",
    "Commodities",
    "Real Estate",
    "Savings",
    "Compound",
    "Fixed Deposit",
  ],
  grid: [
    ["C", "A", "A", "N", "E", "D", "C", "A", "P", "I", "T", "A", "L", "A"],
    ["F", "I", "X", "E", "D", "D", "E", "P", "O", "S", "I", "T", "N", "S"],
    ["G", "A", "U", "D", "U", "N", "T", "N", "O", "O", "M", "O", "N", "E"],
    ["T", "A", "E", "S", "C", "O", "A", "O", "N", "S", "C", "O", "T", "T"],
    ["L", "O", "I", "G", "A", "I", "T", "P", "L", "E", "D", "A", "S", "A"],
    ["O", "I", "T", "N", "T", "T", "S", "C", "B", "I", "I", "N", "E", "S"],
    ["S", "E", "F", "I", "I", "A", "E", "D", "U", "T", "X", "O", "O", "I"],
    ["S", "I", "N", "V", "O", "L", "L", "N", "S", "I", "G", "O", "N", "B"],
    ["P", "P", "E", "A", "N", "F", "A", "U", "I", "D", "U", "T", "E", "A"],
    ["D", "A", "O", "S", "T", "N", "E", "O", "N", "O", "N", "O", "A", "U"],
    ["E", "L", "N", "I", "N", "I", "R", "P", "E", "M", "L", "A", "I", "E"],
    ["E", "I", "N", "D", "T", "B", "F", "M", "S", "M", "U", "P", "O", "F"],
    ["I", "N", "D", "A", "N", "O", "O", "O", "S", "O", "S", "G", "S", "D"],
    ["O", "S", "D", "A", "S", "O", "E", "C", "S", "C", "F", "L", "I", "L"],
  ],
};

export const investingWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-investing-ws3",
  title: "Investing: Puzzle 3",
  topic: "Earning & Growing Money",
  theme: "Nairobi Securities Exchange & Capital Markets",
  instruction: "Find the 11 stock exchange, broker, and passive income terms.",
  size: 14,
  words: [
    "Risk",
    "Shares",
    "Holdings",
    "NSE",
    "Asset",
    "Long-Term Goal",
    "Liability",
    "Capital Gains",
    "Passive Income",
    "Bond",
    "Broker",
  ],
  grid: [
    ["B", "E", "A", "G", "R", "L", "B", "E", "A", "T", "E", "G", "G", "S"],
    ["I", "A", "M", "R", "S", "G", "N", "I", "D", "L", "O", "H", "O", "N"],
    ["S", "L", "N", "E", "S", "L", "A", "T", "B", "R", "O", "K", "E", "R"],
    ["A", "Y", "R", "A", "I", "C", "E", "O", "R", "A", "A", "E", "S", "N"],
    ["P", "A", "S", "S", "I", "V", "E", "I", "N", "C", "O", "M", "E", "S"],
    ["I", "N", "S", "K", "S", "I", "R", "S", "S", "E", "L", "I", "L", "E"],
    ["E", "I", "D", "S", "N", "A", "I", "E", "T", "A", "T", "D", "Y", "G"],
    ["B", "S", "E", "Y", "E", "R", "M", "R", "I", "G", "I", "O", "E", "A"],
    ["O", "N", "K", "O", "R", "T", "R", "A", "L", "A", "Y", "A", "E", "D"],
    ["N", "G", "H", "Y", "E", "R", "B", "H", "I", "B", "R", "G", "A", "P"],
    ["D", "N", "N", "A", "E", "Y", "T", "S", "S", "N", "L", "M", "B", "I"],
    ["T", "S", "N", "I", "A", "G", "L", "A", "T", "I", "P", "A", "C", "A"],
    ["O", "T", "L", "O", "N", "G", "T", "E", "R", "M", "G", "O", "A", "L"],
    ["L", "L", "I", "A", "B", "I", "L", "I", "T", "Y", "N", "I", "P", "R"],
  ],
};

export const investingWordSearch4: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-investing-ws4",
  title: "Investing: Puzzle 4",
  topic: "Earning & Growing Money",
  theme: "Market Liquidity & Short-Term Goals",
  instruction: "Find the 11 equity, liquidity, and dividend terms in the grid.",
  size: 14,
  words: [
    "Growth",
    "Value",
    "Liquidity",
    "Compound",
    "Market",
    "Equity",
    "Dividend",
    "Short Term Goal",
    "Inflation",
    "Portfolio",
    "Asset",
  ],
  grid: [
    ["L", "I", "Q", "U", "I", "D", "I", "T", "Y", "O", "L", "T", "Q", "O"],
    ["I", "U", "C", "S", "U", "M", "R", "A", "I", "T", "E", "R", "S", "M"],
    ["I", "M", "O", "O", "P", "T", "V", "O", "P", "Q", "D", "I", "S", "P"],
    ["P", "C", "O", "T", "S", "I", "Y", "R", "U", "A", "E", "M", "O", "I"],
    ["E", "E", "O", "I", "M", "S", "A", "I", "T", "V", "U", "R", "M", "D"],
    ["I", "I", "N", "F", "L", "A", "T", "I", "O", "N", "T", "A", "A", "N"],
    ["W", "E", "O", "P", "G", "Y", "F", "T", "O", "F", "R", "S", "R", "U"],
    ["T", "D", "D", "D", "R", "N", "T", "T", "O", "I", "I", "S", "K", "O"],
    ["T", "L", "Q", "L", "O", "G", "I", "L", "N", "S", "I", "E", "E", "P"],
    ["A", "D", "T", "R", "W", "F", "I", "Q", "L", "I", "O", "T", "T", "M"],
    ["O", "M", "H", "N", "T", "O", "U", "F", "A", "S", "E", "O", "N", "O"],
    ["T", "L", "I", "S", "H", "D", "I", "V", "I", "D", "E", "N", "D", "C"],
    ["S", "H", "O", "R", "T", "T", "E", "R", "M", "G", "O", "A", "L", "T"],
    ["T", "P", "N", "V", "V", "A", "L", "U", "E", "D", "S", "H", "M", "C"],
  ],
};

export const investingWordSearch5: WordSearchPuzzle = {
  type: "wordsearch",
  id: "eg-investing-ws5",
  title: "Investing: Puzzle 5",
  topic: "Earning & Growing Money",
  theme: "Cryptocurrency, Unit Trusts & Net Worth",
  instruction: "Find the 12 cryptocurrency, unit trust, and net worth terms.",
  size: 14,
  words: [
    "Loss",
    "Property",
    "Cryptocurrency",
    "Diversify",
    "Capital",
    "Return",
    "Networth",
    "Reinvest",
    "Bitcoin",
    "Unit",
    "Stock",
    "Trust",
  ],
  grid: [
    ["T", "E", "E", "Y", "T", "R", "E", "P", "O", "R", "P", "F", "K", "C"],
    ["B", "Y", "F", "I", "S", "R", "E", "V", "I", "D", "U", "S", "C", "R"],
    ["C", "R", "E", "H", "S", "I", "S", "U", "C", "O", "N", "R", "O", "Y"],
    ["R", "E", "S", "N", "E", "T", "W", "O", "R", "T", "H", "T", "T", "P"],
    ["Y", "T", "T", "O", "T", "H", "R", "R", "C", "R", "R", "N", "S", "T"],
    ["T", "C", "S", "E", "R", "N", "T", "R", "T", "S", "U", "R", "Y", "O"],
    ["P", "S", "U", "F", "U", "T", "I", "N", "U", "T", "R", "O", "R", "C"],
    ["R", "T", "R", "T", "S", "S", "B", "T", "T", "S", "S", "O", "L", "U"],
    ["R", "E", "T", "T", "E", "B", "C", "A", "N", "C", "T", "N", "R", "R"],
    ["E", "N", "N", "R", "B", "I", "T", "C", "O", "I", "N", "E", "O", "R"],
    ["T", "U", "E", "R", "N", "I", "L", "A", "T", "I", "P", "A", "C", "E"],
    ["U", "Y", "E", "T", "S", "E", "V", "N", "I", "E", "R", "S", "S", "N"],
    ["R", "T", "T", "N", "I", "O", "S", "O", "N", "C", "N", "Y", "Y", "C"],
    ["N", "I", "T", "T", "D", "R", "C", "S", "P", "R", "N", "T", "R", "Y"],
  ],
};

export const investingQuiz1: QuizPuzzle = {
  type: "quiz",
  id: "eg-investing-quiz1",
  title: "Investing: Quiz 1",
  topic: "Earning & Growing Money",
  instruction: "Explore stocks, compound interest, bonds, and asset appreciation.",
  questions: [
    {
      id: 1,
      question: "When you use your money to buy something that you hope will make you more money in the future, you are choosing to?",
      options: ["Lose", "Invest", "Gift", "Spend"],
      correctIndex: 1,
      explanation: "Investing commits capital with the expectation of generating future financial returns and capital growth.",
    },
    {
      id: 2,
      question: "A company like Safaricom might sell small units of ownership to the public. These units are called?",
      options: ["Bonds", "Commodities", "Stocks or Shares", "Fixed Deposits"],
      correctIndex: 2,
      explanation: "Shares represent equity fractional ownership in a publicly traded corporation.",
    },
    {
      id: 3,
      question: "If Anna has 1,000 bob in her savings account and the bank pays her extra money for keeping it there, that extra money is called?",
      options: ["Principal", "Capital", "Inflation", "Interest"],
      correctIndex: 3,
      explanation: "Interest is the percentage paid by financial institutions on deposited savings balances.",
    },
    {
      id: 4,
      question: "The original amount of money a person first puts into an investment before it grows is the?",
      options: ["Principal", "Dividend", "Asset", "Gain"],
      correctIndex: 0,
      explanation: "Principal is the baseline initial sum invested or loaned before compounding and interest.",
    },
    {
      id: 5,
      question: "Which of these is an example of an 'Asset' that can increase in value over time?",
      options: [
        "A loaf of bread",
        "Real Estate (Land or Houses)",
        "A used textbook",
        "Cinema tickets",
      ],
      correctIndex: 1,
      explanation: "Land and property are appreciating assets that historically increase in monetary value.",
    },
    {
      id: 6,
      question: "When a company makes a profit and decides to share some of that cash with its shareholders, the payment is called a?",
      options: ["Commission", "Bonus", "Dividend", "Royalty"],
      correctIndex: 2,
      explanation: "Dividends distribute corporate earnings directly to stock owners.",
    },
    {
      id: 7,
      question: "'Don't put all your eggs in one basket' is a famous saying about why you should ___ your investments.",
      options: ["Sell", "Hide", "Compound", "Diversify"],
      correctIndex: 3,
      explanation: "Diversification spreads investments across multiple asset classes to mitigate volatility and risk.",
    },
    {
      id: 8,
      question: "If you buy a bag of maize today for 100 Shillings but the price of everything rises so it costs 150 Shillings next year, this is called?",
      options: ["Inflation", "Interest", "Allocation", "Gain"],
      correctIndex: 0,
      explanation: "Inflation erodes purchasing power over time as general prices rise.",
    },
    {
      id: 9,
      question: "When your investment earns interest, and then that interest starts earning its own interest, it is called ___ interest.",
      options: ["Fixed", "Compound", "Simple", "Risk"],
      correctIndex: 1,
      explanation: "Compound interest is interest calculated on both initial principal and accumulated interest.",
    },
    {
      id: 10,
      question: "Gold, oil, and coffee are raw materials that can be traded as investments. These are known as:",
      options: ["Stocks", "Assets", "Commodities", "Bonds"],
      correctIndex: 2,
      explanation: "Commodities are basic raw materials or agricultural goods bought and sold in global markets.",
    },
    {
      id: 11,
      question: "Every investment has a chance that you might lose money instead of making it. This possibility is called?",
      options: ["Allocation", "Return", "Gain", "Risk"],
      correctIndex: 3,
      explanation: "Investment risk is the probability of financial loss relative to anticipated gain.",
    },
    {
      id: 12,
      question: "Which type of investment is a loan you give to the government or a big company for a set period in exchange for regular interest?",
      options: ["Bond", "Share", "Real Estate", "Business"],
      correctIndex: 0,
      explanation: "Treasury and corporate bonds are fixed-income debt securities paying coupon interest.",
    },
  ],
};

export const investingQuiz2: QuizPuzzle = {
  type: "quiz",
  id: "eg-investing-quiz2",
  title: "Investing: Quiz 2",
  topic: "Earning & Growing Money",
  instruction: "Test your understanding of the Nairobi Securities Exchange, net worth, and liquidity.",
  questions: [
    {
      id: 1,
      question: "What is the name of the main market in Kenya where people go to buy and sell Shares in big companies?",
      options: [
        "Central Bank",
        "NSE (Nairobi Securities Exchange)",
        "M-Pesa",
        "KICC",
      ],
      correctIndex: 1,
      explanation: "The Nairobi Securities Exchange (NSE) is the licensed bourse for trading Kenyan equities and bonds.",
    },
    {
      id: 2,
      question: "When you buy a small piece of ownership in a company like Safaricom or KCB, you are buying:",
      options: ["A Liability", "A Bond", "Shares (or Stock)", "A Loan"],
      correctIndex: 2,
      explanation: "Buying shares gives you partial equity ownership and voting rights in the company.",
    },
    {
      id: 3,
      question: "Something you own that puts money in your pocket or grows in value over time is called an:",
      options: ["Liability", "Expense", "Loss", "Asset"],
      correctIndex: 3,
      explanation: "Assets (like rental houses, dividend shares, and treasury bills) generate positive cash flow.",
    },
    {
      id: 4,
      question: "Money you earn regularly without having to work for it every day (like Rent or Dividends) is:",
      options: ["Passive Income", "Wage", "Salary", "Bonus"],
      correctIndex: 0,
      explanation: "Passive income flows automatically from established investments without ongoing manual labor.",
    },
    {
      id: 5,
      question: "When you take the money you earned from an investment and put it back in to buy more, you are choosing to:",
      options: ["Spend", "Reinvest", "Default", "Withdraw"],
      correctIndex: 1,
      explanation: "Reinvesting dividends accelerates wealth accumulation through the power of compounding.",
    },
    {
      id: 6,
      question: "Something that takes money out of your pocket like a car that needs constant repairs is a?",
      options: ["Equity", "Portfolio", "Liability", "Asset"],
      correctIndex: 2,
      explanation: "Liabilities create continuous recurring costs and drain your financial resources.",
    },
    {
      id: 7,
      question: "How easily and quickly you can turn an investment into cash is known as its?",
      options: ["Risk", "Value", "Growth", "Liquidity"],
      correctIndex: 3,
      explanation: "High liquidity means assets can be converted to physical cash immediately without loss of value.",
    },
    {
      id: 8,
      question: "Digital currencies like ___ are part of a new technology called:",
      options: [
        "Bitcoin / Cryptocurrency",
        "Unit Trust / Equity",
        "Bond / Property",
        "Capital / Loss",
      ],
      correctIndex: 0,
      explanation: "Bitcoin and Ethereum are digital decentralized cryptocurrencies secured by cryptographic blockchains.",
    },
    {
      id: 9,
      question: "A professional person who helps you buy and sell shares on the market is called a:",
      options: ["Teller", "Broker", "Manager", "Landlord"],
      correctIndex: 1,
      explanation: "Stockbrokers are licensed intermediaries authorized to execute trades on stock exchanges.",
    },
    {
      id: 10,
      question: "If you want to calculate your ___, you subtract all your Liabilities from all your Assets.",
      options: ["Return", "Capital", "Net Worth", "Portfolio"],
      correctIndex: 2,
      explanation: "Net Worth = Total Assets - Total Liabilities.",
    },
  ],
};
