import { WordSearchPuzzle, QuizPuzzle, ActivityPuzzle } from "../types";

export const bankingWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-banking-ws1",
  title: "Banking: Puzzle 1",
  topic: "Spending Wisely",
  theme: "Branch Operations & Account Statements",
  instruction: "Find the 11 banking operations and statement terms in the grid.",
  size: 14,
  words: [
    "ATM",
    "Sacco",
    "Savings",
    "Bill",
    "Mobile Banking",
    "Teller",
    "Statement",
    "Verification",
    "Alert",
    "Phishing",
    "Pay",
  ],
  grid: [
    ["A", "T", "L", "C", "N", "P", "H", "I", "S", "H", "I", "N", "G", "E"],
    ["I", "A", "M", "B", "I", "A", "B", "A", "N", "B", "V", "H", "S", "R"],
    ["A", "V", "O", "P", "S", "C", "C", "T", "T", "T", "O", "N", "Y", "B"],
    ["A", "E", "B", "S", "A", "C", "C", "O", "N", "L", "T", "C", "L", "S"],
    ["H", "R", "I", "Y", "H", "A", "M", "L", "I", "E", "H", "N", "A", "H"],
    ["T", "I", "L", "A", "S", "T", "T", "N", "I", "A", "T", "S", "N", "C"],
    ["A", "F", "E", "M", "T", "M", "E", "G", "I", "E", "N", "C", "E", "M"],
    ["S", "I", "B", "S", "A", "S", "H", "I", "E", "A", "N", "S", "O", "S"],
    ["P", "C", "A", "L", "T", "L", "L", "M", "O", "T", "L", "E", "I", "A"],
    ["A", "A", "N", "O", "E", "A", "R", "A", "L", "E", "A", "H", "T", "V"],
    ["Y", "T", "K", "S", "M", "E", "I", "I", "B", "L", "L", "V", "S", "I"],
    ["I", "I", "I", "E", "E", "I", "I", "A", "H", "L", "E", "V", "N", "N"],
    ["G", "O", "N", "I", "N", "A", "L", "B", "T", "E", "R", "H", "I", "G"],
    ["A", "N", "G", "E", "T", "B", "I", "L", "L", "R", "T", "F", "A", "S"],
  ],
};

export const bankingWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-banking-ws2",
  title: "Banking: Puzzle 2",
  topic: "Spending Wisely",
  theme: "Digital Wallets, Chamas & Saccos",
  instruction: "Find the 11 digital wallet, chama, and card security terms.",
  size: 14,
  words: [
    "Block",
    "Digital Wallet",
    "Interest",
    "Confirmation",
    "Receipt",
    "Withdraw",
    "Chama",
    "Simcard",
    "Fraud",
    "Transfer",
    "Account",
  ],
  grid: [
    ["D", "S", "E", "I", "T", "R", "A", "N", "S", "F", "E", "R", "N", "L"],
    ["I", "I", "N", "O", "I", "T", "A", "M", "R", "I", "F", "N", "O", "C"],
    ["W", "C", "G", "A", "I", "M", "T", "I", "A", "I", "P", "E", "U", "E"],
    ["A", "E", "T", "I", "I", "F", "I", "N", "T", "E", "R", "E", "S", "T"],
    ["F", "R", "R", "C", "T", "I", "A", "T", "I", "P", "A", "C", "I", "D"],
    ["T", "T", "C", "L", "L", "A", "S", "C", "A", "U", "A", "M", "R", "I"],
    ["N", "B", "C", "T", "D", "W", "L", "I", "H", "C", "C", "U", "C", "I"],
    ["U", "R", "A", "B", "N", "C", "I", "W", "M", "A", "R", "C", "R", "O"],
    ["O", "R", "E", "A", "L", "I", "N", "T", "A", "C", "M", "B", "A", "F"],
    ["C", "G", "C", "C", "N", "O", "A", "A", "H", "L", "A", "A", "D", "R"],
    ["C", "T", "H", "O", "E", "L", "C", "R", "W", "D", "L", "R", "I", "A"],
    ["A", "D", "O", "C", "N", "I", "K", "K", "M", "W", "R", "E", "D", "U"],
    ["T", "S", "M", "N", "A", "W", "P", "E", "U", "T", "T", "A", "T", "D"],
    ["D", "R", "A", "D", "C", "L", "T", "T", "A", "R", "T", "O", "W", "K"],
  ],
};

export const bankingQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-banking-quiz",
  title: "Banking: Quiz",
  topic: "Spending Wisely",
  instruction: "Explore account security, SACCOs, chamas, and teller services.",
  questions: [
    {
      id: 1,
      question: "A 'safe' place where people keep their money at the bank so they can track their spending and saving is their?",
      options: ["Account", "Sim Card", "Receipt", "Bill"],
      correctIndex: 0,
      explanation: "A bank account securely stores your funds and produces itemized financial statements.",
    },
    {
      id: 2,
      question: "When Joseph wants to get physical cash out of his account, he visits an?",
      options: ["ATM (Automated Teller Machine)", "Alert", "Interest", "Account"],
      correctIndex: 0,
      explanation: "ATMs dispense cash 24/7 using your debit card and secret PIN.",
    },
    {
      id: 3,
      question: "In many Kenyan communities, people pool their money together in a small group to save or invest. This group is called a?",
      options: ["Chama", "SACCO", "Digital Wallet", "Teller"],
      correctIndex: 0,
      explanation: "A Chama is an informal community savings circle or investment cooperative in Kenya.",
    },
    {
      id: 4,
      question: "A person who works behind the counter at a bank to help customers deposit or withdraw money is called a?",
      options: ["Teller", "Agent", "Manager", "Auditor"],
      correctIndex: 0,
      explanation: "Bank tellers process cash deposits, withdrawals, cheques, and foreign currency exchanges.",
    },
    {
      id: 5,
      question: "The extra money the bank pays their customer as a reward for keeping their money in a savings account is known as?",
      options: ["Interest", "Tax", "Penalty", "Statement"],
      correctIndex: 0,
      explanation: "Savings accounts earn annual interest based on average maintained balances.",
    },
    {
      id: 6,
      question: "If Mary loses her bank card or it is stolen, the first thing she should do is ask the bank to?",
      options: ["Block the card", "Send a Statement", "Change the SIM Card", "Withdraw money"],
      correctIndex: 0,
      explanation: "Immediately freezing or blocking a lost card prevents unauthorized card charges.",
    },
    {
      id: 7,
      question: "Which document shows a list of all the transactions e.g. money in and out, that a person has made weekly, monthly, or yearly?",
      options: ["Statement", "Receipt", "Bill", "Confirmation"],
      correctIndex: 0,
      explanation: "Bank statements track all debit and credit transaction history over a specific timeframe.",
    },
    {
      id: 8,
      question: "A 'digital wallet' on a person's phone, like M-pesa, is linked to that person's identity through their?",
      options: ["SIM Card", "ATM", "Teller", "Chama"],
      correctIndex: 0,
      explanation: "Your SIM card holds your phone number and cryptographic identity registered under KYC regulations.",
    },
    {
      id: 9,
      question: "If Samuel receives a fake call from someone pretending to be a bank official asking for his PIN, he is being targeted by?",
      options: ["Scammers", "Verification", "Transfer", "Interest"],
      correctIndex: 0,
      explanation: "Banks will NEVER call asking for your secret PIN or one-time OTP passwords.",
    },
    {
      id: 10,
      question: "When Sophia sends money from her account to her friend's phone or bank, she is doing a?",
      options: ["Transfer", "Phishing", "Block", "Statement"],
      correctIndex: 0,
      explanation: "A funds transfer routes money between financial accounts electronically via PesaLink or EFT.",
    },
  ],
};

export const bankAccountsMatcherActivity: ActivityPuzzle = {
  type: "activity",
  id: "sw-bank-accounts-matcher",
  title: "Types of Bank Accounts: 21-Scenario Matcher",
  topic: "Spending Wisely",
  subtype: "account_matcher",
  instruction: "Match each of the 21 real-world scenarios to its most suitable bank account type.",
  config: {
    accountTypes: [
      "Junior / Kids Savings Account",
      "Teen / Youth Account (with Parental Control)",
      "Student Account",
      "Basic / Savings Account",
      "Digital / Mobile-Only Bank Account",
      "Salary Account (Current Account)",
      "Business Account",
      "Fixed Deposit Account",
      "Money Market Fund (MMF)",
      "Trust Account / Custodial Account",
      "Joint Account",
      "Sharia Account",
      "Pension / Retirement Account",
      "Foreign Currency Account",
      "Investment Account",
      "Off-shore Account",
      "Government Bonds",
      "High-Yield Savings Account",
    ],
    scenarios: [
      {
        id: "s1",
        text: "Achieng's parents want to help her start saving a portion of her pocket money in a safe place. She is 10 years old.",
        correctAccount: "Junior / Kids Savings Account",
      },
      {
        id: "s2",
        text: "Kamau is 14 and just started a small snack business. He wants an account with a debit card his parents can monitor.",
        correctAccount: "Teen / Youth Account (with Parental Control)",
      },
      {
        id: "s3",
        text: "A student at the University of Nairobi needs an account with zero monthly maintenance fees because budget is tight.",
        correctAccount: "Student Account",
      },
      {
        id: "s4",
        text: "Wanjiku wants a very simple account with the lowest possible fees just to keep her money safe.",
        correctAccount: "Basic / Savings Account",
      },
      {
        id: "s5",
        text: "Juma uses his phone for everything and wants to open an account using an app without ever visiting a bank building.",
        correctAccount: "Digital / Mobile-Only Bank Account",
      },
      {
        id: "s6",
        text: "Mr. Otieno works at KPLC. Every month, his employer sends his salary directly to this account.",
        correctAccount: "Salary Account (Current Account)",
      },
      {
        id: "s7",
        text: "A shopkeeper on Biashara Street needs an account where she can deposit cash and pay suppliers multiple times a day.",
        correctAccount: "Business Account",
      },
      {
        id: "s8",
        text: "A family wants to save money for emergencies and earn steady interest.",
        correctAccount: "Basic / Savings Account",
      },
      {
        id: "s9",
        text: "Akinyi has 50,000 Shillings she won't need for 12 months. She wants the bank to pay a high, guaranteed fixed rate.",
        correctAccount: "Fixed Deposit Account",
      },
      {
        id: "s10",
        text: "A group of friends want an account that earns high daily compound interest with quick withdrawal when good deals appear.",
        correctAccount: "Money Market Fund (MMF)",
      },
      {
        id: "s11",
        text: "A father wants to save money for his daughter's future college fees and legally manage the funds until she turns 18.",
        correctAccount: "Trust Account / Custodial Account",
      },
      {
        id: "s12",
        text: "A brother and sister want to save up together to buy a gift for their parents' wedding anniversary.",
        correctAccount: "Joint Account",
      },
      {
        id: "s13",
        text: "Halima wants an account that follows Islamic principles and does not pay traditional interest but shares collective profits.",
        correctAccount: "Sharia Account",
      },
      {
        id: "s14",
        text: "James is saving a small portion of his salary every month so he can have a comfortable life when he stops working at 60.",
        correctAccount: "Pension / Retirement Account",
      },
      {
        id: "s15",
        text: "Sylvia, an airline pilot, flies to the UK and USA often. She wants to keep money in US Dollars to avoid exchange losses.",
        correctAccount: "Foreign Currency Account",
      },
      {
        id: "s16",
        text: "A wealthy investor wants to buy shares in Safaricom or KCB through the bank and stock market.",
        correctAccount: "Investment Account",
      },
      {
        id: "s17",
        text: "A business owner wants to hold reserve funds in a bank in Switzerland to protect wealth against local economic issues.",
        correctAccount: "Off-shore Account",
      },
      {
        id: "s18",
        text: "A big corporation wants to park extra cash in very safe short-term government treasury bills to earn high returns.",
        correctAccount: "Government Bonds",
      },
      {
        id: "s19",
        text: "A family sets up a formal legal structure where a bank trust department manages their estate for grandchildren's education.",
        correctAccount: "Trust Account / Custodial Account",
      },
      {
        id: "s20",
        text: "Anthony needs an account for everyday spending basics like groceries, bus fare, and electricity tokens to stick to his budget.",
        correctAccount: "Basic / Savings Account",
      },
      {
        id: "s21",
        text: "Zoe is looking for the absolute highest interest rate possible for her long-term savings fund.",
        correctAccount: "High-Yield Savings Account",
      },
    ],
  },
};
