import { WordSearchPuzzle, QuizPuzzle, ActivityPuzzle } from "../types";

export const bankingWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-banking-ws1",
  title: "Banking: Puzzle 1",
  topic: "Spending Wisely",
  theme: "Branch Operations & Account Statements",
  instruction: "Find the 11 banking operations and statement terms in the grid.",
  size: 14,
  words: [
    "ATM",
    "Sacco",
    "Savings",
    "Bill",
    "Mobile Banking",
    "Teller",
    "Statement",
    "Verification",
    "Alert",
    "Phishing",
    "Pay",
  ],
  grid: [
    ["A", "T", "L", "C", "N", "P", "H", "I", "S", "H", "I", "N", "G", "E"],
    ["I", "A", "M", "B", "I", "A", "B", "A", "N", "B", "V", "H", "S", "R"],
    ["A", "V", "O", "P", "S", "C", "C", "T", "T", "T", "O", "N", "Y", "B"],
    ["A", "E", "B", "S", "A", "C", "C", "O", "N", "L", "T", "C", "L", "S"],
    ["H", "R", "I", "Y", "H", "A", "M", "L", "I", "E", "H", "N", "A", "H"],
    ["T", "I", "L", "A", "S", "T", "T", "N", "I", "A", "T", "S", "N", "C"],
    ["A", "F", "E", "M", "T", "M", "E", "G", "I", "E", "N", "C", "E", "M"],
    ["S", "I", "B", "S", "A", "S", "H", "I", "E", "A", "N", "S", "O", "S"],
    ["P", "C", "A", "L", "T", "L", "L", "M", "O", "T", "L", "E", "I", "A"],
    ["A", "A", "N", "O", "E", "A", "R", "A", "L", "E", "A", "H", "T", "V"],
    ["Y", "T", "K", "S", "M", "E", "I", "I", "B", "L", "L", "V", "S", "I"],
    ["I", "I", "I", "E", "E", "I", "I", "A", "H", "L", "E", "V", "N", "N"],
    ["G", "O", "N", "I", "N", "A", "L", "B", "T", "E", "R", "H", "I", "G"],
    ["A", "N", "G", "E", "T", "B", "I", "L", "L", "R", "T", "F", "A", "S"],
  ],
};

export const bankingWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-banking-ws2",
  title: "Banking: Puzzle 2",
  topic: "Spending Wisely",
  theme: "Digital Wallets, Chamas & Saccos",
  instruction: "Find the 11 digital wallet, chama, and card security terms.",
  size: 14,
  words: [
    "Block",
    "Digital Wallet",
    "Interest",
    "Confirmation",
    "Receipt",
    "Withdraw",
    "Chama",
    "Simcard",
    "Fraud",
    "Transfer",
    "Account",
  ],
  grid: [
    ["D", "S", "E", "I", "T", "R", "A", "N", "S", "F", "E", "R", "N", "L"],
    ["I", "I", "N", "O", "I", "T", "A", "M", "R", "I", "F", "N", "O", "C"],
    ["W", "C", "G", "A", "I", "M", "T", "I", "A", "I", "P", "E", "U", "E"],
    ["A", "E", "T", "I", "I", "F", "I", "N", "T", "E", "R", "E", "S", "T"],
    ["F", "R", "R", "C", "T", "I", "A", "T", "I", "P", "A", "C", "I", "D"],
    ["T", "T", "C", "L", "L", "A", "S", "C", "A", "U", "A", "M", "R", "I"],
    ["N", "B", "C", "T", "D", "W", "L", "I", "H", "C", "C", "U", "C", "I"],
    ["U", "R", "A", "B", "N", "C", "I", "W", "M", "A", "R", "C", "R", "O"],
    ["O", "R", "E", "A", "L", "I", "N", "T", "A", "C", "M", "B", "A", "F"],
    ["C", "G", "C", "C", "N", "O", "A", "A", "H", "L", "A", "A", "D", "R"],
    ["C", "T", "H", "O", "E", "L", "C", "R", "W", "D", "L", "R", "I", "A"],
    ["A", "D", "O", "C", "N", "I", "K", "K", "M", "W", "R", "E", "D", "U"],
    ["T", "S", "M", "N", "A", "W", "P", "E", "U", "T", "T", "A", "T", "D"],
    ["D", "R", "A", "D", "C", "L", "T", "T", "A", "R", "T", "O", "W", "K"],
  ],
};

export const bankingQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-banking-quiz",
  title: "Banking: Quiz",
  topic: "Spending Wisely",
  instruction: "Explore account security, SACCOs, chamas, and teller services.",
  questions: [
    {
      id: 1,
      question: "A 'safe' place where people keep their money at the bank so they can track their spending and saving is their?",
      options: ["Bill", "Account", "Receipt", "Sim Card"],
      correctIndex: 1,
      explanation: "A bank account securely stores your funds and produces itemized financial statements.",
    },
    {
      id: 2,
      question: "When Joseph wants to get physical cash out of his account, he visits an?",
      options: ["Alert", "Interest", "ATM (Automated Teller Machine)", "Account"],
      correctIndex: 2,
      explanation: "ATMs dispense cash 24/7 using your debit card and secret PIN.",
    },
    {
      id: 3,
      question: "In many Kenyan communities, people pool their money together in a small group to save or invest. This group is called a?",
      options: ["Digital Wallet", "Teller", "SACCO", "Chama"],
      correctIndex: 3,
      explanation: "A Chama is an informal community savings circle or investment cooperative in Kenya.",
    },
    {
      id: 4,
      question: "A person who works behind the counter at a bank to help customers deposit or withdraw money is called a?",
      options: ["Teller", "Manager", "Auditor", "Agent"],
      correctIndex: 0,
      explanation: "Bank tellers process cash deposits, withdrawals, cheques, and foreign currency exchanges.",
    },
    {
      id: 5,
      question: "The extra money the bank pays their customer as a reward for keeping their money in a savings account is known as?",
      options: ["Statement", "Interest", "Tax", "Penalty"],
      correctIndex: 1,
      explanation: "Savings accounts earn annual interest based on average maintained balances.",
    },
    {
      id: 6,
      question: "If Mary loses her bank card or it is stolen, the first thing she should do is ask the bank to?",
      options: ["Withdraw money", "Send a Statement", "Block the card", "Change the SIM Card"],
      correctIndex: 2,
      explanation: "Immediately freezing or blocking a lost card prevents unauthorized card charges.",
    },
    {
      id: 7,
      question: "Which document shows a list of all the transactions e.g. money in and out, that a person has made weekly, monthly, or yearly?",
      options: ["Receipt", "Bill", "Confirmation", "Statement"],
      correctIndex: 3,
      explanation: "Bank statements track all debit and credit transaction history over a specific timeframe.",
    },
    {
      id: 8,
      question: "A 'digital wallet' on a person's phone, like M-pesa, is linked to that person's identity through their?",
      options: ["SIM Card", "ATM", "Chama", "Teller"],
      correctIndex: 0,
      explanation: "Your SIM card holds your phone number and cryptographic identity registered under KYC regulations.",
    },
    {
      id: 9,
      question: "If Samuel receives a fake call from someone pretending to be a bank official asking for his PIN, he is being targeted by?",
      options: ["Transfer", "Scammers", "Verification", "Interest"],
      correctIndex: 1,
      explanation: "Banks will NEVER call asking for your secret PIN or one-time OTP passwords.",
    },
    {
      id: 10,
      question: "When Sophia sends money from her account to her friend's phone or bank, she is doing a?",
      options: ["Block", "Phishing", "Transfer", "Statement"],
      correctIndex: 2,
      explanation: "A funds transfer routes money between financial accounts electronically via PesaLink or EFT.",
    },
  ],
};

export const bankAccountsMatcherActivity: ActivityPuzzle = {
  type: "activity",
  id: "sw-bank-accounts-matcher",
  title: "Piggy Vault Match-Up",
  topic: "Saving",
  subtype: "account_matcher",
  instruction: "Pick the account that matches the story.",
  config: {
    accountTypes: [
      "Junior / Kids Savings Account",
      "Teen / Youth Account (with Parental Control)",
      "Student Account",
      "Basic / Savings Account",
      "Digital / Mobile-Only Bank Account",
      "Salary Account (Current Account)",
      "Business Account",
      "Savings Account",
      "Fixed Deposit Account",
      "Money Market Fund (MMF)",
      "Trust Account",
      "Joint Account",
      "Sharia Account",
      "Pension / Retirement Account",
      "Foreign Currency Account",
      "Investment Account",
      "Offshore Account",
      "Government Bonds",
      "Family Trust",
      "Current Account",
      "High-yield Savings Account",
    ],
    scenarios: [
      {
        id: "s1",
        customer: "Achieng, age 10",
        art: "kid",
        text: "Achieng’s parents want her pocket money to live in a safe kids’ box at the bank — not under the mattress!",
        correctAccount: "Junior / Kids Savings Account",
        explanation: "The matching box is Junior / Kids Savings Account.",
      },
      {
        id: "s2",
        customer: "Kamau, age 14",
        art: "teen",
        text: "Kamau sells snacks at school. He wants a debit card, but Mum and Dad must still watch the account.",
        correctAccount: "Teen / Youth Account (with Parental Control)",
        explanation: "The matching box is Teen / Youth Account (with Parental Control).",
      },
      {
        id: "s3",
        customer: "Nairobi campus",
        art: "student",
        text: "A university student needs a bank home with almost no monthly fees while school fees are already heavy.",
        correctAccount: "Student Account",
        explanation: "The matching box is Student Account.",
      },
      {
        id: "s4",
        customer: "Wanjiku",
        art: "woman",
        text: "Wanjiku wants the simplest, lowest-fee box — just a safe place to keep her money, nothing fancy.",
        correctAccount: "Basic / Savings Account",
        explanation: "The matching box is Basic / Savings Account.",
      },
      {
        id: "s5",
        customer: "Juma + phone",
        art: "phone",
        text: "Juma does everything on his phone. He wants to open a bank box in an app and never walk into a branch.",
        correctAccount: "Digital / Mobile-Only Bank Account",
        explanation: "The matching box is Digital / Mobile-Only Bank Account.",
      },
      {
        id: "s6",
        customer: "Mr Otieno",
        art: "worker",
        text: "Every month KPLC sends Mr Otieno’s pay straight into this box — it is built to catch a salary.",
        correctAccount: "Salary Account (Current Account)",
        explanation: "The matching box is Salary Account (Current Account).",
      },
      {
        id: "s7",
        customer: "Biashara shop",
        art: "shop",
        text: "A shopkeeper deposits cash and pays suppliers many times a day. She needs a box made for a business.",
        correctAccount: "Business Account",
        explanation: "The matching box is Business Account.",
      },
      {
        id: "s8",
        customer: "The Mwangi family",
        art: "piggy",
        text: "This family wants a classic box for rainy-day money that can also grow a little interest.",
        correctAccount: "Savings Account",
        explanation: "The matching box is Savings Account.",
      },
      {
        id: "s9",
        customer: "Akinyi’s 50,000",
        art: "lock",
        text: "Akinyi will not touch KSh 50,000 for 12 months. She wants a locked box with a promised fixed rate.",
        correctAccount: "Fixed Deposit Account",
        explanation: "The matching box is Fixed Deposit Account.",
      },
      {
        id: "s10",
        customer: "Friends’ club",
        art: "rocket",
        text: "Friends want high daily interest, but they must still pull money out quickly when a good deal pops up.",
        correctAccount: "Money Market Fund (MMF)",
        explanation: "The matching box is Money Market Fund (MMF).",
      },
      {
        id: "s11",
        customer: "Dad + college",
        art: "dad",
        text: "A dad is saving for his daughter’s college. He must legally look after the money until she turns 18.",
        correctAccount: "Trust Account",
        explanation: "The matching box is Trust Account.",
      },
      {
        id: "s12",
        customer: "Brother & sister",
        art: "siblings",
        text: "A brother and sister want one shared box so they can save together for Mum and Dad’s anniversary gift.",
        correctAccount: "Joint Account",
        explanation: "The matching box is Joint Account.",
      },
      {
        id: "s13",
        customer: "Halima",
        art: "lantern",
        text: "Halima wants a box that follows Islamic rules — no ordinary interest, but a share of honest profits.",
        correctAccount: "Sharia Account",
        explanation: "The matching box is Sharia Account.",
      },
      {
        id: "s14",
        customer: "James at work",
        art: "medal",
        text: "James puts away a slice of his salary every month so life is comfy when he stops working at 60.",
        correctAccount: "Pension / Retirement Account",
        explanation: "The matching box is Pension / Retirement Account.",
      },
      {
        id: "s15",
        customer: "Pilot Sylvia",
        art: "plane",
        text: "Sylvia flies to the UK and USA. She wants to keep dollars in the box so she does not lose money changing currency.",
        correctAccount: "Foreign Currency Account",
        explanation: "The matching box is Foreign Currency Account.",
      },
      {
        id: "s16",
        customer: "Share hunter",
        art: "trophy",
        text: "An investor wants a box that can buy shares like Safaricom or KCB on the stock market.",
        correctAccount: "Investment Account",
        explanation: "The matching box is Investment Account.",
      },
      {
        id: "s17",
        customer: "Far-away vault",
        art: "globe",
        text: "A business owner wants extra funds kept in a bank in another country, like Switzerland, for extra safety.",
        correctAccount: "Offshore Account",
        explanation: "The matching box is Offshore Account.",
      },
      {
        id: "s18",
        customer: "Safe government IOU",
        art: "bank",
        text: "A big company parks spare cash in very safe government paper that pays them back later.",
        correctAccount: "Government Bonds",
        explanation: "The matching box is Government Bonds.",
      },
      {
        id: "s19",
        customer: "Grandkids’ future",
        art: "sprout",
        text: "A family sets up a legal box so the bank can look after their estate for the grandchildren’s school.",
        correctAccount: "Family Trust",
        explanation: "The matching box is Family Trust.",
      },
      {
        id: "s20",
        customer: "Anthony’s daily spend",
        art: "coin",
        text: "Anthony needs a box for everyday spending — groceries, bus fare, and electricity tokens.",
        correctAccount: "Current Account",
        explanation: "The matching box is Current Account.",
      },
      {
        id: "s21",
        customer: "Zoe the grower",
        art: "crown",
        text: "Zoe wants the highest interest she can get for money she will leave sitting a long time.",
        correctAccount: "High-yield Savings Account",
        explanation: "The matching box is High-yield Savings Account.",
      },
    ],
  },
};

export const savingWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-saving-ws1",
  title: "Saving: Word Search",
  topic: "Spending Wisely",
  theme: "Savings Goals, Interest & Emergency Funds",
  instruction: "Find the 15 saving terms from the puzzle book word bank.",
  size: 14,
  words: [
    "Budget",
    "Savings",
    "Interest",
    "Needs",
    "Wants",
    "Emergency",
    "Goal",
    "Income",
    "Expense",
    "Bucks",
    "Asset",
    "Debt",
    "Allowance",
    "Stock",
    "Investment",
  ],
  grid: [
    ["L", "Z", "X", "T", "F", "C", "U", "Q", "V", "D", "B", "J", "R", "P"],
    ["Z", "O", "V", "A", "H", "U", "J", "S", "G", "N", "I", "V", "A", "S"],
    ["C", "P", "O", "R", "I", "N", "T", "E", "R", "E", "S", "T", "H", "F"],
    ["G", "I", "K", "Z", "A", "L", "L", "O", "W", "A", "N", "C", "E", "N"],
    ["B", "B", "N", "Y", "B", "E", "X", "P", "E", "N", "S", "E", "L", "E"],
    ["Z", "U", "G", "V", "Z", "D", "E", "B", "T", "A", "Z", "M", "H", "E"],
    ["B", "T", "D", "X", "E", "D", "E", "R", "N", "S", "D", "A", "G", "D"],
    ["U", "I", "J", "G", "B", "S", "I", "N", "C", "O", "M", "E", "H", "S"],
    ["C", "K", "D", "T", "E", "S", "T", "G", "M", "Y", "L", "A", "O", "G"],
    ["K", "Y", "M", "B", "T", "T", "H", "M", "T", "C", "F", "Q", "S", "B"],
    ["S", "J", "U", "N", "B", "Y", "C", "N", "E", "G", "R", "E", "M", "E"],
    ["S", "F", "A", "J", "K", "C", "O", "T", "S", "N", "Q", "L", "A", "V"],
    ["J", "W", "C", "P", "B", "J", "N", "W", "R", "N", "T", "E", "B", "P"],
    ["A", "H", "N", "H", "X", "T", "E", "S", "S", "A", "P", "E", "S", "J"],
  ],
};

export const bankingSwahiliWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-banking-swahili-ws",
  title: "Banking Swahili: Word Search",
  topic: "Spending Wisely",
  theme: "Swahili Banking Vocabulary",
  instruction: "Find the 18 Swahili money and banking words in the grid.",
  size: 15,
  words: [
    "Wiana",
    "Karani",
    "Hela",
    "Benki",
    "Uhamisho",
    "Kadi",
    "Deni",
    "Hundi",
    "Akaunti",
    "Noti",
    "Stakabadhi",
    "Akiba",
    "Hawala",
    "Malipo",
    "Saini",
    "Salio",
    "Dhamana",
    "Riba",
  ],
  grid: [
    ["G", "T", "H", "P", "K", "N", "J", "X", "L", "J", "E", "K", "D", "B", "I"],
    ["B", "C", "H", "D", "A", "Y", "J", "O", "P", "I", "L", "A", "M", "W", "P"],
    ["B", "T", "S", "A", "L", "I", "O", "N", "X", "K", "B", "R", "C", "G", "N"],
    ["K", "S", "L", "X", "F", "A", "Y", "W", "N", "A", "L", "A", "W", "A", "H"],
    ["N", "S", "T", "A", "K", "A", "B", "A", "D", "H", "I", "N", "I", "H", "A"],
    ["L", "T", "P", "F", "B", "Y", "S", "I", "I", "D", "W", "I", "T", "D", "T"],
    ["J", "O", "A", "X", "Y", "A", "J", "O", "K", "X", "E", "I", "B", "R", "V"],
    ["K", "Y", "W", "Q", "I", "T", "H", "H", "N", "A", "A", "N", "A", "X", "O"],
    ["V", "M", "W", "N", "S", "S", "J", "Y", "E", "O", "N", "Q", "I", "N", "L"],
    ["H", "X", "I", "I", "I", "D", "A", "R", "B", "A", "A", "E", "D", "K", "A"],
    ["M", "S", "C", "M", "D", "T", "X", "I", "A", "M", "M", "Y", "W", "H", "S"],
    ["K", "Q", "A", "X", "D", "N", "K", "B", "L", "R", "A", "O", "K", "U", "T"],
    ["V", "H", "U", "L", "R", "A", "U", "A", "E", "U", "H", "O", "W", "I", "U"],
    ["U", "N", "F", "E", "D", "X", "N", "H", "H", "V", "D", "G", "N", "U", "M"],
    ["R", "N", "B", "I", "T", "O", "N", "I", "T", "N", "U", "A", "K", "A", "Q"],
  ],
};
