import { WordSearchPuzzle, QuizPuzzle, ActivityPuzzle } from "../types";

export const budgetingWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-budgeting-ws1",
  title: "Budgeting: Puzzle 1",
  topic: "Spending Wisely",
  theme: "Needs, Wants & Priorities",
  instruction: "Find the 10 budgeting and prioritization words in the grid.",
  size: 14,
  words: [
    "Fare",
    "Wants",
    "Goalsetting",
    "Prioritise",
    "Rent",
    "Target",
    "Needs",
    "List",
    "Allocate",
    "Food",
  ],
  grid: [
    ["R", "L", "G", "W", "A", "N", "T", "S", "R", "T", "I", "A", "S", "T"],
    ["G", "T", "I", "D", "I", "L", "R", "G", "O", "A", "E", "L", "O", "T"],
    ["O", "O", "F", "P", "R", "R", "O", "A", "C", "R", "N", "A", "W", "S"],
    ["E", "I", "A", "O", "R", "D", "S", "I", "S", "G", "C", "A", "T", "S"],
    ["E", "L", "E", "L", "S", "I", "T", "N", "E", "E", "D", "S", "T", "E"],
    ["R", "I", "G", "R", "S", "E", "O", "L", "R", "T", "R", "N", "A", "F"],
    ["E", "S", "D", "A", "R", "E", "E", "R", "I", "D", "N", "R", "D", "I"],
    ["R", "T", "A", "O", "L", "P", "T", "I", "I", "L", "R", "R", "S", "I"],
    ["A", "D", "G", "T", "S", "L", "T", "T", "I", "T", "F", "E", "F", "S"],
    ["E", "S", "F", "R", "T", "T", "O", "S", "I", "T", "I", "T", "N", "R"],
    ["T", "A", "F", "O", "A", "D", "D", "C", "R", "N", "E", "S", "E", "T"],
    ["E", "E", "I", "A", "O", "E", "T", "S", "A", "S", "G", "S", "E", "S"],
    ["I", "I", "T", "G", "R", "D", "T", "C", "D", "T", "R", "O", "L", "L"],
    ["A", "G", "O", "N", "W", "E", "I", "O", "E", "E", "E", "T", "C", "L"],
  ],
};

export const budgetingWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-budgeting-ws2",
  title: "Budgeting: Puzzle 2",
  topic: "Spending Wisely",
  theme: "Expense Forecasts & Cutbacks",
  instruction: "Find the 10 financial review and planning terms.",
  size: 14,
  words: [
    "Compare",
    "Planner",
    "School Fees",
    "Prepare",
    "Control",
    "Cutbacks",
    "Review",
    "Adjust",
    "Savings",
    "Forecast",
  ],
  grid: [
    ["L", "O", "I", "E", "N", "S", "L", "N", "I", "R", "O", "L", "J", "I"],
    ["O", "D", "M", "R", "T", "R", "E", "N", "N", "A", "L", "P", "E", "E"],
    ["R", "E", "A", "T", "P", "R", "E", "P", "A", "R", "E", "E", "D", "T"],
    ["T", "F", "O", "R", "E", "C", "A", "S", "T", "S", "P", "C", "C", "A"],
    ["N", "E", "A", "D", "J", "U", "S", "T", "S", "L", "U", "O", "A", "O"],
    ["O", "K", "P", "A", "S", "C", "H", "O", "O", "L", "F", "E", "E", "S"],
    ["C", "O", "C", "R", "L", "E", "E", "S", "G", "N", "I", "V", "A", "S"],
    ["E", "R", "A", "S", "J", "E", "M", "E", "E", "F", "O", "B", "I", "S"],
    ["R", "E", "V", "I", "E", "W", "S", "C", "V", "O", "L", "E", "R", "P"],
    ["L", "U", "S", "E", "R", "A", "P", "M", "O", "C", "U", "C", "F", "J"],
    ["P", "P", "O", "L", "C", "N", "E", "O", "L", "T", "T", "T", "O", "P"],
    ["P", "C", "S", "J", "R", "E", "R", "S", "A", "S", "A", "S", "R", "E"],
    ["T", "J", "W", "W", "R", "O", "C", "P", "V", "L", "E", "A", "H", "E"],
    ["T", "S", "C", "P", "K", "C", "U", "T", "B", "A", "C", "K", "S", "H"],
  ],
};

export const budgetingWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-budgeting-ws3",
  title: "Budgeting: Puzzle 3",
  topic: "Spending Wisely",
  theme: "Fixed vs Variable Costs & Cash Flow",
  instruction: "Find the 12 spending and cost categories in the grid.",
  size: 14,
  words: [
    "Utilities",
    "Monthly",
    "Emergency",
    "Fixed Cost",
    "Variable Cost",
    "Spending",
    "Balance",
    "Impulse",
    "Cash Flow",
    "Surplus",
    "Bills",
    "Shortage",
  ],
  grid: [
    ["L", "T", "S", "O", "C", "D", "E", "X", "I", "F", "S", "E", "L", "A"],
    ["S", "L", "S", "H", "O", "R", "T", "A", "G", "E", "H", "T", "C", "I"],
    ["F", "T", "L", "M", "O", "N", "T", "H", "L", "Y", "H", "S", "A", "C"],
    ["N", "H", "H", "V", "E", "I", "A", "A", "R", "O", "B", "O", "T", "B"],
    ["B", "I", "L", "L", "S", "L", "G", "C", "U", "I", "A", "C", "C", "C"],
    ["W", "E", "I", "M", "M", "C", "N", "S", "T", "I", "L", "E", "Y", "A"],
    ["U", "T", "I", "L", "I", "T", "I", "E", "S", "A", "A", "L", "C", "S"],
    ["I", "T", "H", "B", "L", "E", "D", "T", "A", "S", "N", "B", "N", "H"],
    ["L", "L", "X", "T", "T", "L", "N", "M", "U", "N", "C", "A", "E", "F"],
    ["N", "T", "G", "E", "L", "G", "E", "R", "E", "S", "E", "I", "G", "L"],
    ["E", "P", "L", "S", "R", "U", "P", "G", "E", "E", "P", "R", "R", "O"],
    ["H", "E", "T", "X", "Y", "L", "S", "A", "O", "L", "W", "A", "E", "W"],
    ["G", "I", "E", "Y", "U", "E", "U", "I", "S", "T", "S", "V", "M", "E"],
    ["N", "X", "X", "S", "E", "I", "M", "P", "U", "L", "S", "E", "E", "O"],
  ],
};

export const budgetingQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-budgeting-quiz",
  title: "Budgeting: Quiz",
  topic: "Spending Wisely",
  instruction: "Test your understanding of needs vs wants, fixed costs, and emergency funds.",
  questions: [
    {
      id: 1,
      question: "Essential things you must have to survive, like food and water, are called?",
      options: ["Wants", "Needs", "Impulse", "Surplus"],
      correctIndex: 1,
      explanation: "Needs are basic survival essentials including food, clean water, shelter, and healthcare.",
    },
    {
      id: 2,
      question: "Things you would like to have but can live without, like a new gaming console or fancy snacks, are called?",
      options: ["Needs", "Fixed Costs", "Wants", "Bills"],
      correctIndex: 2,
      explanation: "Wants are discretionary desires that enhance comfort but are not essential for survival.",
    },
    {
      id: 3,
      question: "When you decide which expenses are the most important to pay first, you are learning to?",
      options: ["Cutback", "Adjust", "Forecast", "Prioritise"],
      correctIndex: 3,
      explanation: "Prioritization ensures non-negotiable obligations (rent, food, fees) are satisfied before entertainment.",
    },
    {
      id: 4,
      question: "A specific amount of money you aim to save for something big, like a new bike, is called a?",
      options: ["Target", "Shortage", "Rent", "Variable Cost"],
      correctIndex: 0,
      explanation: "A savings target gives you a clear financial milestone to work toward systematically.",
    },
    {
      id: 5,
      question: "Costs that stay the same every month, like Rent or School Fees, are known as?",
      options: ["Cash Flow", "Fixed Costs", "Utilities", "Variable Costs"],
      correctIndex: 1,
      explanation: "Fixed costs remain consistent in amount each payment period regardless of usage.",
    },
    {
      id: 6,
      question: "Costs that change depending on how much you use them, like Electricity or Airtime, are called?",
      options: ["Savings Plans", "Fixed Costs", "Variable Costs", "Goals"],
      correctIndex: 2,
      explanation: "Variable costs fluctuate directly with consumption and usage habits.",
    },
    {
      id: 7,
      question: "When you buy something suddenly without planning for it first, it is called an ___ purchase.",
      options: ["Emergency", "Adjusted", "Allocated", "Impulse"],
      correctIndex: 3,
      explanation: "Impulse buying bypasses budget plans and can quickly drain personal savings.",
    },
    {
      id: 8,
      question: "If you have more money coming in than you are spending, you have a?",
      options: ["Surplus", "Bill", "Shortage", "Balance"],
      correctIndex: 0,
      explanation: "A budget surplus occurs when total income exceeds total expenditure.",
    },
    {
      id: 9,
      question: "When you don't have enough money to cover all your planned expenses, you are facing a?",
      options: ["Surplus", "Shortage", "Savings Plan", "Forecast"],
      correctIndex: 1,
      explanation: "A budget shortage or deficit requires cutting non-essential wants or increasing income.",
    },
    {
      id: 10,
      question: "It is important to put some money aside every month into an 'Emergency Fund' to ___ for unexpected problems.",
      options: ["Compare", "Review", "Prepare", "Prioritise"],
      correctIndex: 2,
      explanation: "Emergency funds provide a safety cushion against unexpected medical expenses or repairs.",
    },
  ],
};

export const schoolBudgetChallengeActivity: ActivityPuzzle = {
  type: "activity",
  id: "sw-school-budget-challenge",
  title: "The KSh 8,000 Back-to-School Challenge",
  topic: "Spending Wisely",
  subtype: "budget_challenge",
  instruction: "You have been given 8,000 bob to prepare for the new term. Choose one item from every category and maximize your savings!",
  config: {
    budget: 8000,
    categories: [
      {
        name: "Uniforms",
        required: true,
        options: [
          { name: "Full New Set (shirt, skirt/trouser, socks, tie, sweater)", price: 5000 },
          { name: "Freshen Up (new shirt and 2 pairs of socks)", price: 3000 },
          { name: "Full set thrifted second-hand at the market", price: 3500 },
        ],
      },
      {
        name: "Footwear",
        required: true,
        options: [
          { name: "Official Bata Toughees", price: 2500 },
          { name: "Thrifted black leather shoes", price: 1000 },
          { name: "New Sports/P.E Shoes", price: 3000 },
        ],
      },
      {
        name: "Stationery",
        required: true,
        options: [
          { name: "All new Bookshop Stationery", price: 2500 },
          { name: "Basic Supermarket Pack", price: 2000 },
        ],
      },
      {
        name: "Backpack",
        required: true,
        options: [
          { name: "High Quality Orthopedic Bag", price: 2500 },
          { name: "Standard durable Backpack", price: 1500 },
          { name: "Thrifted bag in good condition", price: 1000 },
        ],
      },
      {
        name: "Extras",
        required: false,
        options: [
          { name: "New Water Bottle", price: 800 },
          { name: "Cool Notebook or Diary", price: 500 },
        ],
      },
    ],
  },
};

export const homeTreasureHuntActivity: ActivityPuzzle = {
  type: "activity",
  id: "sw-home-treasure-hunt",
  title: "Home 'Treasure Hunt' & Waste Audit",
  topic: "Spending Wisely",
  subtype: "home_treasure_hunt",
  instruction: "Audit your home desk, draw a Needs vs Wants T-chart, and become a price detective.",
  config: {
    steps: [
      {
        step: 1,
        title: "Find 5 Reusable Items",
        description: "Check your desk, backpack, and drawers. Find 5 reusable items (half-full notebooks, rulers, sharpeners) and calculate money saved.",
      },
      {
        step: 2,
        title: "Needs vs Wants T-Chart",
        description: "Draw a line down your page. List Needs (pens, rubbers) on left and Wants (fuzzy pencil case, branded sneakers) on right with target prices.",
      },
      {
        step: 3,
        title: "Be a Price Detective",
        description: "Check a 12-pack of HB pencils vs single pencils at Naivas, Quickmart, or Jumia to calculate the best unit value.",
      },
      {
        step: 4,
        title: "The KSh 2,000 Budget Battle",
        description: "With KSh 2,000 for personal supplies, fund all Needs first. Whatever surplus remains can purchase items from your Wants list.",
      },
      {
        step: 5,
        title: "Hidden Cost Check",
        description: "Remember travel fare and carrier bag fees! Bringing your own reusable bag saves 10 to 50 bob every single shopping trip.",
      },
    ],
  },
};
