import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const consumerSkillsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "ss-consumer-ws1",
  title: "Consumer Skills & Bargaining: Word Search",
  topic: "Smart Spender",
  theme: "Smart Shopping & Consumer Rights",
  instruction: "Find the 14 words on bargaining, warranty, and consumer rights.",
  size: 14,
  words: [
    "ADVERTISING",
    "BARGAIN",
    "COMPARISON",
    "DISCOUNT",
    "EXPIRY DATE",
    "GUARANTEE",
    "IMPULSE BUY",
    "QUALITY",
    "RECEIPT",
    "REFUND",
    "REVIEWS",
    "UNIT PRICE",
    "VALUE",
    "WARRANTY",
  ],
  grid: [
    ["A", "D", "V", "E", "R", "T", "I", "S", "I", "N", "G", "A", "B", "C"],
    ["B", "A", "R", "G", "A", "I", "N", "D", "I", "S", "C", "O", "U", "N"],
    ["C", "O", "M", "P", "A", "R", "I", "S", "O", "N", "D", "E", "F", "T"],
    ["G", "U", "A", "R", "A", "N", "T", "E", "E", "U", "N", "I", "T", "P"],
    ["I", "M", "P", "U", "L", "S", "E", "B", "U", "Y", "Q", "U", "A", "R"],
    ["E", "X", "P", "I", "R", "Y", "D", "A", "T", "E", "L", "I", "T", "I"],
    ["Q", "U", "A", "L", "I", "T", "Y", "R", "E", "C", "E", "I", "P", "C"],
    ["R", "E", "F", "U", "N", "D", "R", "E", "V", "I", "E", "W", "S", "E"],
    ["W", "A", "R", "R", "A", "N", "T", "Y", "V", "A", "L", "U", "E", "S"],
    ["B", "E", "S", "T", "B", "U", "Y", "M", "A", "R", "K", "E", "T", "S"],
    ["S", "H", "O", "P", "P", "I", "N", "G", "L", "I", "S", "T", "S", "A"],
    ["C", "O", "N", "S", "U", "M", "E", "R", "P", "R", "O", "T", "E", "V"],
    ["F", "A", "I", "R", "P", "R", "I", "C", "I", "N", "G", "L", "A", "E"],
    ["K", "E", "B", "S", "S", "T", "A", "N", "D", "A", "R", "D", "S", "R"],
  ],
};

export const consumerSkillsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "ss-consumer-ws2",
  title: "Unit Pricing & Brand Awareness: Word Search",
  topic: "Smart Spender",
  theme: "Comparing Products by Weight and Volume",
  instruction: "Find terms related to evaluating true product cost and package sizing.",
  size: 14,
  words: [
    "BARCODE",
    "BEST BEFORE",
    "BULK BUYING",
    "EXPIRATION",
    "GENERIC",
    "GRAMS",
    "KEBS MARK",
    "KILOGRAMS",
    "LABELS",
    "LITRES",
    "MILLILITRES",
    "NAME BRAND",
    "PACKAGING",
    "UNIT COST",
  ],
  grid: [
    ["B", "U", "L", "K", "B", "U", "Y", "I", "N", "G", "B", "A", "R", "C"],
    ["B", "E", "S", "T", "B", "E", "F", "O", "R", "E", "O", "D", "E", "O"],
    ["K", "E", "B", "S", "M", "A", "R", "K", "L", "A", "B", "E", "L", "D"],
    ["K", "I", "L", "O", "G", "R", "A", "M", "S", "G", "R", "A", "M", "E"],
    ["M", "I", "L", "L", "I", "L", "I", "T", "R", "E", "S", "L", "I", "T"],
    ["N", "A", "M", "E", "B", "R", "A", "N", "D", "G", "E", "N", "E", "R"],
    ["P", "A", "C", "K", "A", "G", "I", "N", "G", "U", "N", "I", "T", "E"],
    ["E", "X", "P", "I", "R", "A", "T", "I", "O", "N", "C", "O", "S", "S"],
    ["S", "T", "A", "N", "D", "A", "R", "D", "I", "Z", "A", "T", "I", "O"],
    ["C", "O", "M", "P", "A", "R", "I", "S", "O", "N", "S", "H", "O", "P"],
    ["S", "H", "R", "I", "N", "K", "F", "L", "A", "T", "I", "O", "N", "Q"],
    ["P", "R", "O", "M", "O", "T", "I", "O", "N", "C", "A", "M", "P", "A"],
    ["C", "E", "R", "T", "I", "F", "I", "C", "A", "T", "I", "O", "N", "S"],
    ["C", "O", "N", "S", "U", "M", "E", "R", "G", "U", "A", "R", "D", "S"],
  ],
};

export const consumerSkillsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "ss-consumer-quiz",
  title: "Consumer Skills & Smart Buying Quiz",
  topic: "Smart Spender",
  instruction: "Demonstrate your shopping savvy and consumer rights knowledge.",
  questions: [
    {
      id: 1,
      question: "What is 'Unit Pricing' and why is it important?",
      options: [
        "The cost per single unit of measure (e.g. per gram or per litre), allowing you to accurately compare packages of different sizes",
        "The price of an entire delivery truck",
        "The amount paid to a cashier as a tip",
        "The number on your receipt barcode",
      ],
      correctIndex: 0,
      explanation:
        "Unit pricing shows the exact cost per gram/ml, revealing whether the bigger box is truly cheaper.",
    },
    {
      id: 2,
      question: "What is the recommended '24-Hour Rule' for non-essential purchases?",
      options: [
        "Wait 24 hours before buying an impulse want to see if you still feel it is necessary",
        "You must spend all your money within 24 hours of earning it",
        "Shops close forever after 24 hours",
        "All food expires in 24 hours",
      ],
      correctIndex: 0,
      explanation:
        "The 24-hour waiting rule breaks impulsive emotional buying habits and prevents buyer's remorse.",
    },
    {
      id: 3,
      question: "What does the KEBS Standardization Mark on products in Kenya certify?",
      options: [
        "That the product has been tested and meets national safety, health, and quality standards",
        "That the product was imported from outer space",
        "That the product is free of charge",
        "That the shopkeeper is famous",
      ],
      correctIndex: 0,
      explanation:
        "Kenya Bureau of Standards (KEBS) ensures products sold locally meet strict health, safety, and quality regulations.",
    },
    {
      id: 4,
      question: "Why should you always ask for and retain your purchase receipt?",
      options: [
        "It serves as legal proof of purchase required for returns, warranties, or refunds",
        "It is used as wrapping paper",
        "You must show it to every neighbor",
        "It generates free electricity",
      ],
      correctIndex: 0,
      explanation:
        "A receipt is your binding legal proof of purchase if an item is defective or needs replacement.",
    },
    {
      id: 5,
      question: "What is 'Shrinkflation'?",
      options: [
        "When manufacturers reduce the size or quantity of a product while keeping the retail price unchanged",
        "When clothes shrink in the wash",
        "When coins become smaller in size",
        "When shop doors shrink",
      ],
      correctIndex: 0,
      explanation:
        "Shrinkflation is a subtle form of price inflation where you pay the same price for fewer grams or millilitres.",
    },
  ],
};
