import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const consumerSkillsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-consumer-ws1",
  title: "Consumer Skills: Puzzle 1",
  topic: "Spending Wisely",
  theme: "Smart Shopping & Value Evaluation",
  instruction: "Find the 10 consumer and audit terms in the grid.",
  size: 14,
  words: [
    "Asset",
    "Comparison",
    "Audit",
    "Consumer",
    "ATM",
    "Coupon",
    "Barter",
    "Cosign",
    "Budget",
    "Brand",
  ],
  grid: [
    ["N", "A", "T", "S", "D", "B", "E", "A", "A", "O", "D", "I", "R", "S"],
    ["O", "S", "U", "U", "T", "A", "O", "O", "P", "O", "B", "U", "R", "S"],
    ["M", "A", "S", "S", "E", "T", "O", "N", "D", "O", "B", "R", "T", "B"],
    ["G", "A", "A", "B", "N", "T", "G", "A", "S", "U", "R", "T", "P", "U"],
    ["E", "E", "G", "B", "P", "A", "M", "A", "O", "M", "A", "O", "B", "D"],
    ["C", "S", "U", "A", "U", "N", "S", "U", "S", "S", "N", "A", "N", "G"],
    ["G", "A", "R", "A", "D", "R", "U", "D", "C", "M", "D", "T", "O", "E"],
    ["C", "N", "M", "I", "A", "I", "A", "I", "N", "R", "N", "M", "E", "T"],
    ["U", "U", "S", "A", "N", "R", "S", "T", "O", "G", "A", "P", "N", "R"],
    ["T", "D", "D", "O", "E", "R", "T", "B", "I", "S", "O", "U", "O", "E"],
    ["C", "O", "M", "P", "A", "R", "I", "S", "O", "N", "N", "T", "P", "T"],
    ["U", "R", "O", "D", "A", "N", "O", "A", "E", "G", "E", "C", "U", "R"],
    ["B", "T", "R", "S", "O", "C", "N", "U", "O", "R", "P", "O", "O", "A"],
    ["C", "A", "R", "E", "M", "U", "S", "N", "O", "C", "N", "M", "C", "B"],
  ],
};

export const consumerSkillsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-consumer-ws2",
  title: "Consumer Skills: Puzzle 2",
  topic: "Spending Wisely",
  theme: "Credit, Inflation & Consumer Protection",
  instruction: "Find the 10 credit, inflation, and vendor terms.",
  size: 14,
  words: [
    "Recession",
    "Credit",
    "Fraud",
    "Expense",
    "Income",
    "Vendor",
    "Interest",
    "Donate",
    "Inflation",
    "Debt",
  ],
  grid: [
    ["N", "D", "D", "L", "S", "I", "I", "T", "E", "T", "I", "B", "T", "D"],
    ["N", "O", "E", "X", "O", "C", "E", "R", "V", "F", "C", "O", "C", "R"],
    ["E", "S", "D", "O", "N", "A", "T", "E", "I", "E", "R", "T", "P", "S"],
    ["E", "T", "A", "E", "N", "S", "C", "C", "C", "R", "N", "A", "S", "R"],
    ["M", "E", "S", "C", "S", "R", "R", "E", "S", "O", "D", "P", "U", "E"],
    ["O", "R", "T", "B", "T", "O", "E", "S", "M", "I", "X", "F", "F", "D"],
    ["C", "C", "R", "E", "D", "I", "T", "S", "X", "O", "B", "C", "D", "E"],
    ["N", "C", "N", "T", "I", "I", "A", "I", "O", "T", "A", "O", "I", "X"],
    ["I", "E", "L", "O", "U", "E", "R", "O", "D", "N", "E", "V", "C", "P"],
    ["E", "O", "B", "T", "E", "U", "T", "N", "E", "M", "D", "E", "N", "E"],
    ["N", "I", "P", "F", "E", "I", "I", "E", "I", "T", "R", "O", "A", "N"],
    ["B", "E", "E", "T", "N", "R", "A", "S", "R", "B", "R", "O", "T", "S"],
    ["I", "N", "F", "L", "A", "T", "I", "O", "N", "E", "E", "E", "E", "E"],
    ["R", "T", "S", "E", "R", "E", "T", "N", "I", "D", "S", "I", "R", "E"],
  ],
};

export const consumerSkillsWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-consumer-ws3",
  title: "Consumer Skills: Puzzle 3",
  topic: "Spending Wisely",
  theme: "Privacy, Receipts & Fraud Defense",
  instruction: "Find the 10 consumer rights and security terms in the grid.",
  size: 14,
  words: [
    "Phishing",
    "Privacy",
    "Lease",
    "Rebate",
    "Overdraft",
    "Logo",
    "Receipt",
    "Profit",
    "Loan",
    "Quality",
  ],
  grid: [
    ["P", "E", "O", "F", "V", "T", "P", "I", "E", "C", "E", "R", "O", "R"],
    ["R", "I", "S", "F", "I", "I", "I", "E", "L", "O", "A", "N", "Q", "A"],
    ["I", "N", "R", "I", "E", "V", "O", "E", "H", "P", "I", "R", "L", "D"],
    ["L", "I", "R", "E", "Y", "T", "I", "L", "A", "U", "Q", "I", "C", "H"],
    ["T", "C", "T", "R", "R", "E", "Y", "C", "A", "V", "I", "R", "P", "I"],
    ["O", "L", "N", "Y", "T", "R", "E", "I", "E", "A", "V", "H", "O", "I"],
    ["E", "O", "U", "O", "L", "L", "E", "A", "S", "E", "I", "T", "H", "E"],
    ["L", "O", "S", "I", "R", "G", "O", "V", "A", "V", "O", "T", "C", "T"],
    ["O", "L", "P", "L", "I", "O", "V", "E", "R", "D", "R", "A", "F", "T"],
    ["G", "P", "P", "P", "R", "O", "F", "I", "T", "N", "H", "H", "C", "A"],
    ["O", "A", "I", "C", "O", "L", "P", "E", "N", "Y", "L", "E", "G", "L"],
    ["R", "E", "B", "A", "T", "E", "R", "E", "I", "P", "R", "P", "D", "O"],
    ["R", "F", "A", "I", "P", "P", "H", "I", "S", "H", "I", "N", "G", "A"],
    ["O", "R", "O", "F", "A", "S", "N", "A", "Y", "A", "L", "P", "B", "T"],
  ],
};

export const consumerSkillsWordSearch4: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-consumer-ws4",
  title: "Consumer Skills: Puzzle 4",
  topic: "Spending Wisely",
  theme: "Subscriptions, Redress & Refunds",
  instruction: "Find the 10 consumer redress and digital subscription terms.",
  size: 14,
  words: [
    "Redress",
    "Reviews",
    "Subscription",
    "Scarcity",
    "Refund",
    "Service",
    "Trend",
    "Scam",
    "Taxes",
    "Skill",
  ],
  grid: [
    ["S", "U", "B", "S", "C", "R", "I", "P", "T", "I", "O", "N", "I", "S"],
    ["I", "R", "E", "D", "R", "E", "S", "S", "E", "C", "D", "C", "O", "T"],
    ["S", "D", "A", "E", "I", "B", "S", "O", "S", "D", "N", "E", "R", "T"],
    ["O", "T", "R", "I", "E", "C", "K", "S", "S", "Y", "C", "R", "S", "E"],
    ["S", "E", "I", "S", "R", "E", "R", "B", "V", "S", "V", "U", "T", "S"],
    ["S", "W", "S", "K", "X", "S", "E", "X", "A", "T", "E", "A", "V", "C"],
    ["C", "E", "E", "I", "T", "S", "V", "R", "S", "E", "R", "S", "C", "N"],
    ["A", "S", "T", "L", "C", "R", "C", "S", "E", "L", "Y", "S", "A", "I"],
    ["R", "S", "R", "L", "N", "E", "R", "S", "E", "F", "S", "S", "F", "I"],
    ["C", "X", "E", "C", "I", "V", "R", "E", "S", "R", "U", "C", "E", "S"],
    ["I", "E", "A", "M", "R", "I", "T", "E", "C", "A", "U", "N", "W", "I"],
    ["T", "R", "C", "U", "E", "E", "B", "E", "S", "S", "W", "A", "D", "C"],
    ["Y", "R", "R", "E", "L", "W", "E", "C", "I", "E", "S", "E", "E", "V"],
    ["P", "R", "S", "S", "R", "S", "S", "R", "B", "M", "A", "C", "S", "A"],
  ],
};

export const consumerSkillsWordSearch5: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-consumer-ws5",
  title: "Consumer Skills: Puzzle 5",
  topic: "Spending Wisely",
  theme: "Warranties, Clearance & Wholesale",
  instruction: "Find the 11 retail warranties and wholesale terms in the grid.",
  size: 14,
  words: [
    "Loyalty",
    "Wants",
    "Liabilities",
    "Clearance",
    "Rent",
    "Unit",
    "Warranty",
    "Bargain",
    "Value",
    "Label",
    "Wholesale",
  ],
  grid: [
    ["W", "L", "E", "B", "A", "L", "L", "I", "N", "V", "R", "T", "W", "R"],
    ["E", "A", "L", "I", "L", "L", "A", "R", "G", "O", "I", "N", "E", "S"],
    ["G", "A", "N", "B", "A", "O", "L", "Y", "A", "A", "I", "R", "R", "I"],
    ["Y", "L", "T", "T", "A", "Y", "A", "U", "R", "T", "A", "N", "N", "G"],
    ["Y", "H", "I", "S", "S", "A", "N", "V", "A", "L", "U", "E", "A", "I"],
    ["W", "A", "N", "T", "I", "L", "Y", "T", "N", "A", "R", "R", "A", "W"],
    ["R", "N", "U", "A", "A", "T", "E", "N", "I", "A", "G", "R", "A", "B"],
    ["R", "N", "I", "V", "E", "Y", "B", "L", "N", "S", "T", "S", "N", "S"],
    ["A", "E", "L", "I", "A", "B", "I", "L", "I", "T", "I", "E", "S", "I"],
    ["R", "C", "L", "E", "A", "R", "A", "N", "C", "E", "T", "E", "N", "N"],
    ["A", "E", "N", "B", "L", "B", "A", "L", "A", "A", "I", "A", "N", "B"],
    ["E", "T", "N", "A", "O", "T", "R", "L", "T", "A", "A", "B", "L", "A"],
    ["R", "R", "C", "T", "N", "B", "L", "N", "C", "A", "R", "W", "W", "R"],
    ["E", "L", "A", "S", "E", "L", "O", "H", "W", "L", "A", "A", "C", "T"],
  ],
};

export const consumerSkillsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-consumer-quiz",
  title: "Consumer Skills: Quiz",
  topic: "Spending Wisely",
  instruction: "Test your consumer rights, bargaining strategies, and fraud defense.",
  questions: [
    {
      id: 1,
      question: "When you go to a market like Gikomba or Toi and try to agree on a lower price with the seller, you are trying to?",
      options: ["Overdraft", "Bargain", "Audit", "Lease"],
      correctIndex: 1,
      explanation: "Bargaining / negotiation helps shoppers secure fair prices in open-air markets.",
    },
    {
      id: 2,
      question: "Before buying a new phone, it is wise to check what other people say about it online. These comments are called?",
      options: ["Labels", "Logos", "Reviews", "Coupons"],
      correctIndex: 2,
      explanation: "Customer reviews highlight build quality, battery life, and common defects before purchase.",
    },
    {
      id: 3,
      question: "A promise from a manufacturer to fix or replace a product if it breaks within a certain time like one year is a?",
      options: ["Receipt", "Logo", "Trend", "Warranty"],
      correctIndex: 3,
      explanation: "A written warranty guarantees manufacturer repair or replacement for defective items.",
    },
    {
      id: 4,
      question: "To make sure you are getting the best deal, you should look at the same item in different shops. This skill is called?",
      options: [
        "Comparison shopping",
        "Privacy shopping",
        "Clearance shopping",
        "Wholesale shopping",
      ],
      correctIndex: 0,
      explanation: "Comparison shopping prevents overpaying and identifies seasonal discounts across merchants.",
    },
    {
      id: 5,
      question: "Which piece of paper is your proof of payment and should always be kept in case you need to return an item?",
      options: ["Logo", "Receipt", "Coupon", "Label"],
      correctIndex: 1,
      explanation: "Official receipts are legally required to claim refunds, warranties, and product exchanges.",
    },
    {
      id: 6,
      question: "If you receive a fake SMS or email asking for your M-PESA PIN to 'update your account,' you are being targeted by?",
      options: ["Loyalty", "Redress", "Phishing", "Auditing"],
      correctIndex: 2,
      explanation: "Phishing scams impersonate legitimate brands to trick you into revealing sensitive passwords or PINs.",
    },
    {
      id: 7,
      question: "When a shop wants to sell off old stock quickly at very low prices, they often have a?",
      options: ["Recession", "Wholesale", "Subscription", "Clearance sale"],
      correctIndex: 3,
      explanation: "Clearance sales liquidate end-of-season inventory at steep markdowns.",
    },
    {
      id: 8,
      question: "Buying items in large quantities at a lower price per unit like a whole bale of flour is called buying?",
      options: ["Wholesale", "Retail", "On Lease", "On Credit"],
      correctIndex: 0,
      explanation: "Wholesale purchasing cuts per-unit packaging and retail markup costs significantly.",
    },
    {
      id: 9,
      question: "A symbol or design that helps you identify a specific company or Brand like the Safaricom 'S' is known as?",
      options: ["Label", "Logo", "Unit", "Trend"],
      correctIndex: 1,
      explanation: "A corporate logo visually represents the company's identity and registered trademark.",
    },
    {
      id: 10,
      question: "When there isn't enough of a product to go around for example water during a drought, it causes?",
      options: ["Profit", "Surplus", "Scarcity", "Inflation"],
      correctIndex: 2,
      explanation: "Economic scarcity occurs when demand exceeds the limited available physical supply.",
    },
  ],
};
