import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const creditLoansWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-credit-ws1",
  title: "Credit & Loans: Puzzle 1",
  topic: "Spending Wisely",
  theme: "Borrowing, Debt & Credit Scores",
  instruction: "Find the 8 credit scoring and loan terms in the grid.",
  size: 14,
  words: [
    "Lender",
    "Loan",
    "Debt",
    "Credit Card",
    "Debit",
    "Fine",
    "Penalty Digital",
    "Guarantor",
    "Credit Score",
  ],
  grid: [
    ["C", "R", "E", "D", "I", "T", "S", "C", "O", "R", "E", "P", "E", "R"],
    ["E", "C", "I", "G", "E", "R", "R", "D", "T", "F", "I", "N", "C", "R"],
    ["D", "R", "N", "B", "D", "L", "I", "G", "I", "D", "N", "N", "P", "O"],
    ["T", "E", "D", "R", "N", "E", "E", "R", "N", "E", "T", "I", "E", "P"],
    ["P", "D", "I", "E", "R", "B", "I", "D", "D", "B", "E", "P", "N", "E"],
    ["L", "I", "D", "C", "Y", "R", "R", "R", "E", "I", "R", "C", "I", "N"],
    ["E", "T", "D", "R", "C", "A", "C", "N", "E", "T", "E", "I", "F", "A"],
    ["L", "C", "E", "R", "T", "U", "A", "D", "E", "S", "S", "C", "T", "L"],
    ["S", "A", "E", "N", "P", "T", "D", "T", "T", "T", "T", "A", "R", "T"],
    ["E", "R", "N", "O", "L", "E", "N", "D", "E", "R", "R", "I", "A", "Y"],
    ["D", "D", "I", "G", "I", "T", "A", "L", "L", "O", "A", "N", "D", "A"],
    ["L", "R", "O", "T", "N", "A", "R", "A", "U", "G", "T", "I", "Y", "O"],
    ["T", "G", "D", "E", "A", "E", "R", "I", "T", "B", "E", "D", "D", "A"],
    ["D", "D", "O", "E", "E", "R", "I", "S", "D", "T", "E", "L", "B", "L"],
  ],
};

export const creditLoansWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-credit-ws2",
  title: "Credit & Loans: Puzzle 2",
  topic: "Spending Wisely",
  theme: "BNPL, Collateral & Repayment Schedules",
  instruction: "Find the 11 collateral, installment, and loan contract terms.",
  size: 14,
  words: [
    "BNPL",
    "Buy",
    "Default",
    "Borrow",
    "Collateral",
    "Loan",
    "Repay",
    "Approval",
    "Installment",
    "Overdue",
    "Contract",
  ],
  grid: [
    ["A", "E", "A", "P", "O", "M", "R", "R", "T", "O", "P", "O", "L", "A"],
    ["P", "R", "P", "P", "T", "N", "E", "B", "U", "Y", "R", "U", "O", "R"],
    ["P", "T", "C", "R", "O", "P", "P", "L", "L", "C", "L", "P", "N", "B"],
    ["R", "B", "O", "A", "N", "A", "A", "O", "O", "V", "N", "V", "L", "T"],
    ["O", "C", "L", "L", "O", "B", "Y", "F", "A", "E", "O", "O", "A", "N"],
    ["V", "D", "L", "O", "R", "O", "L", "L", "N", "E", "A", "T", "N", "E"],
    ["A", "E", "A", "E", "V", "R", "S", "I", "T", "L", "T", "M", "A", "M"],
    ["L", "F", "T", "C", "R", "R", "T", "U", "E", "A", "C", "T", "O", "L"],
    ["B", "A", "E", "E", "T", "O", "L", "U", "B", "L", "A", "O", "E", "L"],
    ["A", "U", "R", "O", "Y", "W", "D", "I", "E", "A", "R", "O", "A", "A"],
    ["P", "L", "A", "O", "L", "R", "U", "A", "V", "V", "T", "T", "E", "T"],
    ["M", "T", "L", "B", "E", "O", "N", "R", "U", "E", "N", "T", "R", "S"],
    ["L", "Y", "B", "V", "T", "D", "E", "A", "O", "R", "O", "R", "P", "N"],
    ["E", "I", "O", "O", "P", "L", "L", "A", "P", "A", "C", "O", "T", "I"],
  ],
};

export const creditLoansQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-credit-quiz",
  title: "Credit & Loans: Quiz",
  topic: "Spending Wisely",
  instruction: "Learn how interest, collateral, credit bureaus, and BNPL agreements work.",
  questions: [
    {
      id: 1,
      question: "When Joy gets money from a bank or a friend with the promise to pay it back later, she's choosing to?",
      options: ["Donate", "Borrow", "Default", "Fine"],
      correctIndex: 1,
      explanation: "Borrowing creates a legal and financial liability to repay the principal plus agreed terms.",
    },
    {
      id: 2,
      question: "The extra money Joy has to pay back on top of the original amount she borrowed is called?",
      options: ["Interest", "Approval", "Installment", "Debit"],
      correctIndex: 0,
      explanation: "Interest represents the cost of borrowing capital from a financial institution.",
    },
    {
      id: 3,
      question: "A person or a bank that gives out money to borrowers to be repaid later is called?",
      options: ["Lender", "Guarantor", "Borrower", "Default"],
      correctIndex: 0,
      explanation: "Lenders provide credit facilities, personal loans, and asset financing.",
    },
    {
      id: 4,
      question: "If David takes a loan to buy a new phone today and pay for it in small bits every month, those regular payments are called?",
      options: ["Fines", "Installments", "Collateral", "Contracts"],
      correctIndex: 1,
      explanation: "Monthly installments divide the total loan balance into manageable scheduled payments.",
    },
    {
      id: 5,
      question: "What is the formal name for the money Joy owes after she borrows it?",
      options: ["Debt", "Credit Score", "Penalty", "Approval"],
      correctIndex: 0,
      explanation: "Debt is an obligation owed by one party (debtor) to a second party (creditor).",
    },
    {
      id: 6,
      question: "Sometimes, a lender asks for something valuable like a car logbook or title deed, to hold onto until the borrower finishes paying their loan. This is called?",
      options: ["Collateral", "BNPL", "Debit", "Fine"],
      correctIndex: 0,
      explanation: "Collateral pledges an asset as security to ensure repayment of a secured loan.",
    },
    {
      id: 7,
      question: "A friend or relative who promises to pay your loan if Joy is unable to repay it is known as a?",
      options: ["Lender", "Guarantor", "Default", "Digital Loan"],
      correctIndex: 1,
      explanation: "Guarantors assume legal responsibility for settling debts if the primary borrower defaults.",
    },
    {
      id: 8,
      question: "Apps that can let a person borrow small amounts of money quickly are examples of a?",
      options: ["Digital Loan", "Credit Card", "Fine", "Collateral"],
      correctIndex: 0,
      explanation: "Digital lending apps evaluate mobile credit metrics to provide micro-loans instantly.",
    },
    {
      id: 9,
      question: "'Buy Now, Pay Later' is a popular way to shop today. What is the short form for this?",
      options: ["BNPL", "Debit", "Loan", "Repay"],
      correctIndex: 0,
      explanation: "BNPL financing allows shoppers to receive goods upfront and spread payments over installments.",
    },
    {
      id: 10,
      question: "To keep a good reputation with banks, you need a high ___, which shows you are good at paying back money.",
      options: ["Penalty", "Credit Score", "Fine", "Interest"],
      correctIndex: 1,
      explanation: "Credit reference bureaus (CRBs) track repayment history to calculate credit scores.",
    },
  ],
};
