import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const creditLoansWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "ss-credit-ws1",
  title: "Credit & Borrowing: Word Search",
  topic: "Smart Spender",
  theme: "Loans, Debt, Collateral, and Credit Scores",
  instruction: "Find the 14 words covering borrowing, interest obligations, and credit health.",
  size: 14,
  words: [
    "BORROWER",
    "COLLATERAL",
    "CREDIT CRB",
    "CREDIT SCORE",
    "DEFAULT",
    "GUARANTOR",
    "INTEREST",
    "LENDER",
    "MORTGAGE",
    "PENALTY",
    "PRINCIPAL",
    "REPAYMENT",
    "SACCO LOAN",
    "TENURE",
  ],
  grid: [
    ["C", "O", "L", "L", "A", "T", "E", "R", "A", "L", "P", "R", "I", "N"],
    ["C", "R", "E", "D", "I", "T", "S", "C", "O", "R", "E", "G", "U", "A"],
    ["B", "O", "R", "R", "O", "W", "E", "R", "D", "E", "F", "A", "U", "R"],
    ["L", "E", "N", "D", "E", "R", "M", "O", "R", "T", "G", "A", "G", "A"],
    ["P", "R", "I", "N", "C", "I", "P", "A", "L", "I", "N", "T", "E", "N"],
    ["R", "E", "P", "A", "Y", "M", "E", "N", "T", "T", "E", "N", "U", "T"],
    ["S", "A", "C", "C", "O", "L", "O", "A", "N", "P", "E", "N", "A", "O"],
    ["C", "R", "E", "D", "I", "T", "C", "R", "B", "R", "A", "T", "I", "R"],
    ["F", "I", "N", "A", "N", "C", "I", "A", "L", "H", "E", "A", "L", "T"],
    ["D", "E", "B", "T", "C", "O", "U", "N", "S", "E", "L", "L", "I", "N"],
    ["M", "O", "B", "I", "L", "E", "L", "O", "A", "N", "A", "P", "P", "S"],
    ["B", "A", "D", "D", "E", "B", "T", "A", "U", "D", "I", "T", "O", "R"],
    ["A", "P", "P", "R", "O", "V", "A", "L", "C", "H", "E", "C", "K", "S"],
    ["G", "O", "O", "D", "C", "R", "E", "D", "I", "T", "P", "A", "T", "H"],
  ],
};

export const creditLoansWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "ss-credit-ws2",
  title: "Debt Traps & Mobile Lending: Word Search",
  topic: "Smart Spender",
  theme: "Predatory Apps, Compound Charges & Credit Repair",
  instruction: "Search for warnings on digital loan apps, predatory debt, and CRB listing.",
  size: 14,
  words: [
    "APR RATE",
    "BLACK LIST",
    "COMPOUND DEBT",
    "CRB CLEARANCE",
    "DEBT TRAP",
    "DIGITAL LOAN",
    "DUE DATE",
    "FEES",
    "LATE CHARGE",
    "LISTING",
    "LOAN SHARK",
    "OVERDUE",
    "RECOVERY",
    "ROLLOVER",
  ],
  grid: [
    ["C", "O", "M", "P", "O", "U", "N", "D", "D", "E", "B", "T", "A", "B"],
    ["D", "E", "B", "T", "T", "R", "A", "P", "D", "U", "E", "D", "A", "T"],
    ["D", "I", "G", "I", "T", "A", "L", "L", "O", "A", "N", "L", "A", "E"],
    ["L", "O", "A", "N", "S", "H", "A", "R", "K", "F", "E", "E", "S", "C"],
    ["C", "R", "B", "C", "L", "E", "A", "R", "A", "N", "C", "E", "C", "H"],
    ["B", "L", "A", "C", "K", "L", "I", "S", "T", "I", "N", "G", "A", "A"],
    ["O", "V", "E", "R", "D", "U", "E", "R", "O", "L", "L", "O", "R", "R"],
    ["R", "E", "C", "O", "V", "E", "R", "Y", "A", "G", "E", "N", "T", "G"],
    ["A", "P", "R", "R", "A", "T", "E", "H", "I", "D", "D", "E", "N", "E"],
    ["S", "P", "E", "N", "D", "I", "N", "G", "A", "U", "D", "I", "T", "S"],
    ["F", "I", "N", "A", "N", "C", "I", "A", "L", "R", "I", "S", "K", "S"],
    ["D", "I", "G", "I", "T", "A", "L", "P", "R", "I", "V", "A", "C", "Y"],
    ["C", "O", "L", "L", "E", "C", "T", "I", "O", "N", "C", "A", "L", "L"],
    ["B", "E", "W", "A", "R", "E", "O", "F", "S", "C", "A", "M", "S", "X"],
  ],
};

export const creditLoansQuiz: QuizPuzzle = {
  type: "quiz",
  id: "ss-credit-quiz",
  title: "Credit & Debt Management Quiz",
  topic: "Smart Spender",
  instruction: "Test your understanding of loan mechanics, credit bureaus, and good vs bad debt.",
  questions: [
    {
      id: 1,
      question: "What is the role of a Credit Reference Bureau (CRB) in Kenya?",
      options: [
        "It collects and maintains credit histories and repayment records of borrowers to determine creditworthiness",
        "It prints paper banknotes for the government",
        "It sells laptops to students",
        "It is a social media club",
      ],
      correctIndex: 0,
      explanation:
        "CRBs (e.g. Metropol, TransUnion, Creditinfo) compile credit scores based on timely loan repayment.",
    },
    {
      id: 2,
      question: "What is 'Collateral' in a secured loan?",
      options: [
        "An asset (such as a title deed, car logbook, or shares) pledged as security to the lender in case of default",
        "A free gift from the bank manager",
        "A photo of your pet",
        "A lottery ticket",
      ],
      correctIndex: 0,
      explanation:
        "Collateral protects the lender: if the borrower defaults, the asset can be liquidated to recover the loan balance.",
    },
    {
      id: 3,
      question: "What differentiates 'Good Debt' from 'Bad Debt'?",
      options: [
        "Good debt finances assets or investments that appreciate in value or generate income; bad debt finances perishable consumables at high interest",
        "Good debt never has to be paid back",
        "Bad debt only comes from relatives",
        "All loans are bad debt",
      ],
      correctIndex: 0,
      explanation:
        "Good debt (e.g. education, student loans, mortgage, business inventory) grows net worth; bad debt funds lifestyle luxuries.",
    },
    {
      id: 4,
      question: "What is an APR (Annual Percentage Rate)?",
      options: [
        "The true total annual cost of borrowing, including interest rate plus all hidden processing fees",
        "The number of days in a leap year",
        "The bank's opening hours in April",
        "An application on a smartphone",
      ],
      correctIndex: 0,
      explanation:
        "APR reveals the actual yearly expense of taking credit by adding up loan interest and administrative charges.",
    },
    {
      id: 5,
      question: "What happens if a borrower consistently fails to repay digital mobile loans on time?",
      options: [
        "Their credit score plunges, they get negative CRB listing, and future formal loan access is blocked",
        "The loan magically turns into free cash",
        "Their phone battery increases",
        "Nothing happens",
      ],
      correctIndex: 0,
      explanation:
        "Defaulting damages your national credit score, disqualifying you from bank mortgages, business loans, and jobs.",
    },
  ],
};
