import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const digitalEconomyWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-digital-ws1",
  title: "Digital Economy: Puzzle",
  topic: "Spending Wisely",
  theme: "AI, Online Gigs & Cloud Technologies",
  instruction: "Find the 14 digital economy and software tools in the grid.",
  size: 14,
  words: [
    "Data Analytics",
    "Gig Economy",
    "Freelance",
    "Portfolio",
    "Ajira",
    "Cloud",
    "Python",
    "Cybersecurity",
    "Coding",
    "ChatGPT",
    "Blockchain",
    "SEO",
    "Canva",
    "Digital Market",
  ],
  grid: [
    ["D", "I", "G", "I", "T", "A", "L", "M", "A", "R", "K", "E", "T", "I"],
    ["T", "D", "A", "T", "A", "A", "N", "A", "L", "Y", "T", "I", "C", "S"],
    ["Y", "M", "O", "N", "O", "C", "E", "E", "C", "R", "T", "N", "R", "E"],
    ["N", "C", "Y", "C", "P", "G", "P", "I", "G", "C", "A", "N", "V", "A"],
    ["Y", "K", "S", "O", "O", "I", "L", "O", "F", "T", "R", "O", "P", "E"],
    ["T", "A", "E", "E", "G", "C", "O", "D", "I", "N", "G", "D", "A", "H"],
    ["Y", "T", "I", "R", "U", "C", "E", "S", "R", "E", "B", "Y", "C", "T"],
    ["A", "C", "F", "R", "E", "E", "L", "A", "N", "C", "E", "G", "T", "A"],
    ["C", "I", "O", "C", "E", "P", "P", "Y", "T", "H", "O", "N", "O", "M"],
    ["A", "C", "S", "A", "J", "T", "P", "G", "T", "A", "H", "C", "R", "A"],
    ["R", "C", "L", "S", "N", "I", "A", "H", "C", "K", "C", "O", "L", "B"],
    ["T", "G", "N", "O", "E", "G", "T", "C", "L", "T", "C", "I", "T", "O"],
    ["A", "C", "I", "O", "U", "O", "A", "T", "E", "A", "A", "D", "U", "O"],
    ["T", "E", "B", "G", "U", "D", "E", "T", "A", "J", "I", "R", "A", "R"],
  ],
};

export const digitalEconomyQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-digital-quiz",
  title: "Digital Economy: Quiz",
  topic: "Spending Wisely",
  instruction: "Explore AI, Python coding, Ajira digital work, and cybersecurity skills.",
  questions: [
    {
      id: 1,
      question: "A system where people do short-term tasks like driving for a ride-share app or writing articles online instead of full-time office jobs is the?",
      options: ["Gig Economy", "Data Analytics", "Cloud", "SEO"],
      correctIndex: 0,
      explanation: "The gig economy enables flexible, independent on-demand contracting via digital platforms.",
    },
    {
      id: 2,
      question: "Which Kenyan government program helps young people get the skills they need to find work online?",
      options: ["Ajira", "ChatGPT", "Python", "Canva"],
      correctIndex: 0,
      explanation: "The Ajira Digital Program equips Kenyan youth with training for online freelancing and remote jobs.",
    },
    {
      id: 3,
      question: "If Collins wants to build websites, apps, or software, he needs to learn how to write instructions for computers, which is called?",
      options: ["Coding", "SEO", "Blockchain", "Freelance"],
      correctIndex: 0,
      explanation: "Coding or programming is the language through which developers build digital applications.",
    },
    {
      id: 4,
      question: "Which of these is a popular and easy-to-learn programming language used for web development and AI?",
      options: ["Python", "Canva", "Cloud", "Portfolio"],
      correctIndex: 0,
      explanation: "Python is universally favored for machine learning, automation, and backend development.",
    },
    {
      id: 5,
      question: "An AI tool that can answer questions, write stories, and help Brian solve math problems is called?",
      options: ["ChatGPT", "SEO", "Ajira", "Data Analytics"],
      correctIndex: 0,
      explanation: "ChatGPT and generative AI assistants understand and generate conversational text responses.",
    },
    {
      id: 6,
      question: "To show potential clients the work she's done like graphic designs or articles, Lilian puts them all together in a digital?",
      options: ["Portfolio", "Cloud", "Blockchain", "Python"],
      correctIndex: 0,
      explanation: "A digital portfolio curates case studies and creative samples to win freelance contracts.",
    },
    {
      id: 7,
      question: "Which easy-to-use graphic design tool is used to create posters, social media posts, and logos?",
      options: ["Canva", "Python", "SEO", "Ajira"],
      correctIndex: 0,
      explanation: "Canva simplifies visual design and branding with drag-and-drop template workflows.",
    },
    {
      id: 8,
      question: "If Zach works from home for different companies around the world rather than one boss in an office, he's a?",
      options: ["Freelancer", "Data Analyst", "Cloud Engineer", "Coder"],
      correctIndex: 0,
      explanation: "Global freelancing empowers remote professionals to earn foreign exchange from international clients.",
    },
    {
      id: 9,
      question: "When Rose uses the internet and social media to promote products or businesses, she is working as?",
      options: ["Digital Marketing", "Cybersecurity", "Blockchain", "SEO"],
      correctIndex: 0,
      explanation: "Digital marketing spans social media campaigns, influencer partnerships, and online ads.",
    },
    {
      id: 10,
      question: "Making sure a website shows up at the top of the list when someone searches on Google is called?",
      options: ["SEO (Search Engine Optimization)", "Cloud", "Canva", "Ajira"],
      correctIndex: 0,
      explanation: "SEO optimizes web content structure so search engines rank your page on top search results.",
    },
    {
      id: 11,
      question: "The practice of protecting computers, networks, and data from digital attacks or hackers is?",
      options: ["Cybersecurity", "Blockchain", "Data Analytics", "Coding"],
      correctIndex: 0,
      explanation: "Cybersecurity protects user accounts, servers, and sensitive data against malware and intrusions.",
    },
    {
      id: 12,
      question: "When John saves his photos or documents on the internet like on Google Drive, instead of just saving on his phone, he is using the?",
      options: ["Cloud", "Python", "Portfolio", "Gig Economy"],
      correctIndex: 0,
      explanation: "Cloud storage provides secure, off-site data backup accessible from any connected device.",
    },
  ],
};
