import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const paymentMethodsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "ss-payment-ws1",
  title: "Methods of Payment: Word Search",
  topic: "Smart Spender",
  theme: "Modes of Exchange & Modern Settlement Systems",
  instruction: "Search for traditional, digital, and banking payment methods.",
  size: 14,
  words: [
    "BANK DRAFT",
    "CASH",
    "CHEQUE",
    "CREDIT CARD",
    "DEBIT CARD",
    "EFT",
    "MOBILE MONEY",
    "ONLINE BANKING",
    "PAYPAL",
    "PREPAID CARD",
    "RTGS",
    "STANDING ORDER",
    "WALLET",
    "WIRE TRANSFER",
  ],
  grid: [
    ["M", "O", "B", "I", "L", "E", "M", "O", "N", "E", "Y", "C", "A", "S"],
    ["D", "E", "B", "I", "T", "C", "A", "R", "D", "P", "A", "Y", "P", "H"],
    ["C", "R", "E", "D", "I", "T", "C", "A", "R", "D", "E", "F", "T", "A"],
    ["C", "H", "E", "Q", "U", "E", "W", "A", "L", "L", "E", "T", "B", "L"],
    ["B", "A", "N", "K", "D", "R", "A", "F", "T", "R", "T", "G", "S", "C"],
    ["O", "N", "L", "I", "N", "E", "B", "A", "N", "K", "I", "N", "G", "A"],
    ["P", "R", "E", "P", "A", "I", "D", "C", "A", "R", "D", "S", "T", "R"],
    ["W", "I", "R", "E", "T", "R", "A", "N", "S", "F", "E", "R", "A", "D"],
    ["S", "T", "A", "N", "D", "I", "N", "G", "O", "R", "D", "E", "N", "S"],
    ["P", "E", "S", "A", "L", "I", "N", "K", "C", "L", "E", "A", "D", "E"],
    ["C", "O", "N", "T", "A", "C", "T", "L", "E", "S", "S", "P", "I", "N"],
    ["B", "I", "O", "M", "E", "T", "R", "I", "C", "P", "A", "S", "S", "T"],
    ["A", "U", "T", "H", "E", "N", "T", "I", "C", "A", "T", "I", "O", "N"],
    ["P", "A", "Y", "M", "E", "N", "T", "G", "A", "T", "E", "W", "A", "Y"],
  ],
};

export const paymentMethodsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "ss-payment-ws2",
  title: "Payment Card Security: Word Search",
  topic: "Smart Spender",
  theme: "EMV Chips, Magnetic Stripes, and CVV Codes",
  instruction: "Find the security components built into debit and credit cards.",
  size: 14,
  words: [
    "AUTHENTICATION",
    "CARD NUMBER",
    "CHIP AND PIN",
    "CONTACTLESS",
    "CVV CODE",
    "EMV CHIP",
    "EXPIRY DATE",
    "HOLOGRAM",
    "ISSUER",
    "MAGNETIC STRIP",
    "NFC",
    "OTP CODE",
    "SIGNATURE",
    "TOKENIZATION",
  ],
  grid: [
    ["C", "H", "I", "P", "A", "N", "D", "P", "I", "N", "A", "B", "C", "D"],
    ["C", "A", "R", "D", "N", "U", "M", "B", "E", "R", "E", "F", "G", "H"],
    ["C", "O", "N", "T", "A", "C", "T", "L", "E", "S", "S", "I", "J", "K"],
    ["C", "V", "V", "C", "O", "D", "E", "E", "M", "V", "C", "H", "I", "P"],
    ["E", "X", "P", "I", "R", "Y", "D", "A", "T", "E", "L", "M", "N", "O"],
    ["M", "A", "G", "N", "E", "T", "I", "C", "S", "T", "R", "I", "P", "P"],
    ["H", "O", "L", "O", "G", "R", "A", "M", "I", "S", "S", "U", "E", "R"],
    ["O", "T", "P", "C", "O", "D", "E", "S", "I", "G", "N", "A", "T", "U"],
    ["T", "O", "K", "E", "N", "I", "Z", "A", "T", "I", "O", "N", "R", "E"],
    ["A", "U", "T", "H", "E", "N", "T", "I", "C", "A", "T", "I", "O", "N"],
    ["N", "F", "C", "T", "E", "C", "H", "N", "O", "L", "O", "G", "Y", "S"],
    ["P", "A", "S", "S", "C", "O", "D", "E", "S", "E", "C", "U", "R", "E"],
    ["F", "R", "A", "U", "D", "P", "R", "E", "V", "E", "N", "T", "I", "O"],
    ["P", "O", "I", "N", "T", "O", "F", "S", "A", "L", "E", "T", "E", "R"],
  ],
};

export const paymentMethodsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "ss-payment-quiz",
  title: "Methods of Payment Quiz",
  topic: "Smart Spender",
  instruction: "Assess your understanding of payment instruments, clearing systems, and security.",
  questions: [
    {
      id: 1,
      question: "What is the crucial difference between a Debit Card and a Credit Card?",
      options: [
        "A debit card withdraws directly from your own deposited bank balance, while a credit card borrows funds from the bank up to a limit",
        "A credit card is only made of wood",
        "A debit card gives you free money that you never need to pay back",
        "There is no difference at all",
      ],
      correctIndex: 0,
      explanation:
        "Debit spends your own money immediately; credit borrows from the card issuer, incurring interest if not repaid.",
    },
    {
      id: 2,
      question: "What is the 3-digit CVV number on the back of bank cards used for?",
      options: [
        "To verify cardholder possession during online / 'card-not-present' transactions",
        "To tell you how many coins are left in the ATM",
        "It is your secret PIN number",
        "It tells the bank your age",
      ],
      correctIndex: 0,
      explanation:
        "The Card Verification Value (CVV) provides cryptographic proof that the physical card is present during e-commerce checkout.",
    },
    {
      id: 3,
      question: "What is a 'Standing Order' in banking?",
      options: [
        "An instruction to your bank to automatically transfer a fixed amount on a regular date (e.g. for monthly rent)",
        "Standing up while doing banking in person",
        "Ordering food from a bank cashier",
        "A card that can only be used standing upright",
      ],
      correctIndex: 0,
      explanation:
        "A standing order automates recurring fixed payments directly from your checking account.",
    },
    {
      id: 4,
      question: "What does RTGS stand for in large interbank fund transfers?",
      options: [
        "Real-Time Gross Settlement",
        "Random Telegraph Gold System",
        "Rapid Telephone Game Service",
        "Regional Trade Gold Standard",
      ],
      correctIndex: 0,
      explanation:
        "RTGS clears and settles high-value bank transfers individually and instantaneously without netting delays.",
    },
    {
      id: 5,
      question: "Why should you never click banking links sent via unverified SMS or email?",
      options: [
        "They are phishing traps designed to steal your PIN, passwords, and one-time OTP codes",
        "They might upgrade your phone",
        "They only work on desktop screens",
        "Banks do not own computers",
      ],
      correctIndex: 0,
      explanation:
        "Phishing attacks impersonate legitimate banks to trick users into disclosing private credentials.",
    },
  ],
};
