import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const paymentMethodsWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-payment-ws1",
  title: "Methods of Payment: Puzzle 1",
  topic: "Spending Wisely",
  theme: "Cards, Vouchers & Wire Transfers",
  instruction: "Find the 12 payment instruments in the grid.",
  size: 14,
  words: [
    "Money Order",
    "Mobile Pay",
    "Debit Card",
    "Prepaid Card",
    "Voucher",
    "Merchant",
    "Cheque",
    "Wire Transfer",
    "Remittance",
    "POS",
    "Loan",
  ],
  grid: [
    ["I", "M", "R", "V", "O", "U", "C", "H", "E", "R", "E", "R", "P", "E"],
    ["M", "W", "N", "O", "R", "A", "U", "E", "E", "P", "E", "R", "P", "E"],
    ["E", "I", "N", "L", "C", "D", "E", "M", "O", "D", "R", "R", "R", "O"],
    ["R", "R", "R", "O", "A", "L", "E", "S", "R", "D", "E", "A", "E", "R"],
    ["C", "E", "L", "A", "E", "H", "Y", "O", "A", "M", "T", "A", "P", "D"],
    ["H", "T", "O", "N", "Q", "R", "Y", "A", "I", "Y", "R", "R", "A", "R"],
    ["A", "R", "C", "O", "F", "E", "T", "T", "N", "A", "A", "L", "I", "A"],
    ["N", "A", "O", "O", "N", "E", "T", "E", "M", "P", "O", "E", "D", "C"],
    ["T", "N", "H", "O", "A", "A", "A", "R", "O", "E", "H", "U", "C", "T"],
    ["E", "S", "M", "N", "N", "Q", "N", "R", "E", "L", "P", "Q", "A", "I"],
    ["A", "F", "O", "C", "M", "S", "Q", "O", "W", "I", "P", "E", "R", "B"],
    ["I", "E", "E", "C", "N", "E", "C", "C", "D", "B", "M", "H", "D", "E"],
    ["A", "R", "L", "V", "B", "E", "O", "H", "D", "O", "E", "C", "O", "D"],
    ["H", "D", "V", "R", "E", "E", "B", "T", "B", "M", "Y", "Q", "F", "E"],
  ],
};

export const paymentMethodsWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-payment-ws2",
  title: "Methods of Payment: Puzzle 2",
  topic: "Spending Wisely",
  theme: "Contactless, Apps & Standing Orders",
  instruction: "Find the 12 payment channels and digital card methods.",
  size: 14,
  words: [
    "Gift Card",
    "Standing Order",
    "Bitcoin",
    "Contactless",
    "Till",
    "Bank Transfer",
    "Bank App",
    "Credit Cards",
    "Cash",
    "Paypal",
    "Deposit",
  ],
  grid: [
    ["B", "P", "P", "I", "I", "B", "S", "A", "E", "A", "A", "R", "A", "T"],
    ["P", "H", "E", "L", "T", "A", "T", "T", "C", "A", "A", "A", "P", "T"],
    ["D", "N", "N", "T", "A", "N", "A", "A", "T", "G", "T", "R", "T", "I"],
    ["C", "S", "D", "N", "I", "K", "N", "L", "C", "K", "E", "D", "C", "S"],
    ["B", "K", "P", "I", "T", "T", "D", "A", "O", "A", "S", "I", "R", "O"],
    ["A", "E", "D", "O", "A", "R", "I", "E", "N", "I", "R", "A", "E", "P"],
    ["N", "R", "R", "C", "P", "A", "N", "A", "T", "O", "E", "T", "D", "E"],
    ["K", "I", "A", "T", "K", "N", "G", "K", "A", "C", "L", "G", "I", "D"],
    ["A", "R", "C", "I", "F", "S", "O", "T", "C", "C", "A", "A", "T", "P"],
    ["P", "D", "T", "B", "A", "F", "R", "L", "T", "A", "P", "O", "C", "A"],
    ["P", "R", "F", "N", "A", "E", "D", "L", "L", "S", "Y", "R", "A", "T"],
    ["C", "N", "I", "D", "N", "R", "E", "N", "E", "H", "A", "R", "R", "D"],
    ["D", "C", "G", "T", "I", "C", "R", "E", "S", "N", "P", "N", "D", "N"],
    ["S", "N", "T", "I", "L", "L", "C", "T", "S", "R", "R", "R", "S", "A"],
  ],
};

export const paymentMethodsWordSearch3: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-payment-ws3",
  title: "Methods of Payment: Puzzle 3",
  topic: "Spending Wisely",
  theme: "Mobile Banking & QR Code Transfers",
  instruction: "Find the 11 digital banking and cashless payment terms.",
  size: 14,
  words: [
    "Mpesa",
    "Mobile Banking",
    "Crypto",
    "Transfer",
    "Wallet",
    "Pin",
    "Overdraft",
    "Interest",
    "Funds",
    "Cashless",
    "QR Code",
  ],
  grid: [
    ["T", "I", "N", "T", "E", "R", "E", "S", "T", "S", "O", "C", "E", "C"],
    ["N", "A", "P", "W", "L", "R", "E", "F", "S", "N", "A", "R", "T", "R"],
    ["K", "O", "V", "A", "S", "D", "S", "L", "A", "V", "I", "G", "G", "Y"],
    ["F", "P", "N", "L", "Q", "F", "S", "L", "A", "D", "C", "T", "O", "P"],
    ["U", "S", "O", "L", "R", "D", "S", "R", "S", "O", "P", "I", "N", "T"],
    ["N", "A", "N", "E", "C", "V", "L", "T", "E", "D", "I", "S", "P", "O"],
    ["D", "G", "A", "T", "O", "C", "S", "L", "P", "N", "R", "D", "O", "S"],
    ["S", "Y", "F", "N", "D", "S", "S", "I", "M", "I", "S", "Y", "O", "S"],
    ["A", "T", "F", "L", "E", "D", "T", "V", "A", "L", "T", "H", "F", "T"],
    ["G", "N", "I", "K", "N", "A", "B", "E", "L", "I", "B", "O", "M", "O"],
    ["A", "S", "M", "L", "N", "D", "A", "O", "M", "G", "T", "Y", "U", "S"],
    ["S", "O", "S", "R", "R", "E", "I", "E", "E", "H", "S", "H", "A", "O"],
    ["T", "P", "C", "A", "S", "H", "L", "E", "S", "S", "O", "S", "A", "R"],
    ["T", "A", "T", "S", "T", "F", "R", "A", "D", "R", "E", "V", "O", "R"],
  ],
};

export const paymentMethodsQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-payment-quiz",
  title: "Methods of Payment: Quiz",
  topic: "Spending Wisely",
  instruction: "Explore POS machines, QR codes, debit cards, and standing orders.",
  questions: [
    {
      id: 1,
      question: "Which famous Kenyan service allows you to send money and pay for goods using your mobile phone?",
      options: ["Bitcoin", "Mpesa", "Cheque", "Money Order"],
      correctIndex: 1,
      explanation: "M-PESA is East Africa's leading mobile phone-based money transfer, financing, and microfinancing service.",
    },
    {
      id: 2,
      question: "What is the secret 4-digit number you must keep private to protect your bank card or mobile wallet?",
      options: ["QR Code", "PIN", "Till", "Voucher"],
      correctIndex: 1,
      explanation: "Your Personal Identification Number (PIN) authorizes transactions and must never be disclosed.",
    },
    {
      id: 3,
      question: "Which term describes a society where people use cards and phones instead of physical notes and coins?",
      options: ["Cashless", "Interest", "Deposit", "Funds"],
      correctIndex: 0,
      explanation: "Cashless economies conduct digital payments through mobile wallets, NFC cards, and instant bank transfers.",
    },
    {
      id: 4,
      question: "To pay for something online, you might scan a square pattern of black and white dots called a?",
      options: ["Barcode", "QR Code", "Bank App", "POS"],
      correctIndex: 1,
      explanation: "Quick Response (QR) codes encode merchant till details for swift camera scanning and payment.",
    },
    {
      id: 5,
      question: "When you borrow money from a bank and have to pay it back later, it is called a?",
      options: ["Gift Card", "Loan", "Remittance", "Standing Order"],
      correctIndex: 1,
      explanation: "A bank loan is a credit facility that must be repaid over time alongside agreed interest.",
    },
    {
      id: 6,
      question: "Which of these is a digital currency that exists only on the internet and isn't printed by any government?",
      options: ["Bitcoin", "Cash", "Shilling", "Debit Card"],
      correctIndex: 0,
      explanation: "Bitcoin is a decentralized peer-to-peer cryptocurrency operating without central bank intervention.",
    },
    {
      id: 7,
      question: "When you go to a shop and see another customer use a card on a small handheld machine to pay, that machine is called a?",
      options: ["POS (Point of Sale)", "Wallet", "Till", "Bank App"],
      correctIndex: 0,
      explanation: "Point of Sale (POS) terminals securely process debit and credit card chip/contactless payments.",
    },
    {
      id: 8,
      question: "If your parent or guardian wants their bank to automatically pay your school fees every month on a specific date, they set up a?",
      options: ["Standing Order", "Money Order", "Cash Transfer", "Overdraft"],
      correctIndex: 0,
      explanation: "A standing order automates recurring fixed payments directly from a bank account.",
    },
    {
      id: 9,
      question: "Money sent by Kenyans living abroad back to their families at home is known as?",
      options: ["Interest", "Remittance", "Voucher", "Bitcoin"],
      correctIndex: 1,
      explanation: "Diaspora remittances represent billions of shillings sent home annually to support families and invest in development.",
    },
    {
      id: 10,
      question: "When you use a card to spend money that is already in your bank account, you are using a?",
      options: ["Credit Card", "Debit Card", "Prepaid Card", "Gift Card"],
      correctIndex: 1,
      explanation: "Debit cards directly deduct transaction amounts from your existing bank account balance.",
    },
  ],
};
