import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const savvyShopperWordSearch: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-savvy-ws1",
  title: "Savvy Shopper: Puzzle",
  topic: "Spending Wisely",
  theme: "E-Commerce, Online Markets & Order Tracking",
  instruction: "Find the 16 online shopping and courier terms in the grid.",
  size: 14,
  words: [
    "Wishlist",
    "Books",
    "Gadgets",
    "Discount",
    "Password",
    "Refund",
    "Cart",
    "Delivery",
    "Sale",
    "Jiji",
    "Courier",
    "Order",
    "Kilimall",
    "Jumia",
    "Reviews",
    "Receipt",
  ],
  grid: [
    ["L", "R", "E", "D", "I", "B", "O", "O", "K", "S", "T", "T", "B", "L"],
    ["G", "E", "D", "I", "S", "C", "O", "U", "N", "T", "G", "E", "L", "K"],
    ["I", "C", "G", "O", "L", "O", "R", "A", "L", "G", "P", "I", "C", "R"],
    ["M", "E", "A", "W", "S", "E", "D", "K", "M", "R", "A", "R", "D", "R"],
    ["T", "I", "D", "K", "R", "O", "E", "J", "A", "A", "S", "R", "N", "V"],
    ["D", "P", "G", "R", "A", "O", "R", "U", "E", "I", "S", "U", "U", "I"],
    ["E", "T", "E", "N", "A", "A", "W", "M", "A", "L", "W", "G", "F", "R"],
    ["L", "I", "T", "D", "T", "N", "O", "I", "A", "V", "O", "I", "E", "E"],
    ["I", "D", "S", "R", "S", "E", "E", "A", "S", "O", "R", "I", "R", "V"],
    ["V", "T", "A", "A", "M", "D", "J", "S", "O", "H", "D", "O", "F", "I"],
    ["E", "C", "L", "I", "L", "G", "K", "I", "W", "P", "L", "I", "T", "E"],
    ["R", "E", "J", "R", "A", "E", "T", "E", "J", "P", "K", "I", "A", "W"],
    ["Y", "A", "C", "O", "U", "R", "I", "E", "R", "I", "I", "C", "S", "S"],
    ["R", "K", "I", "L", "I", "M", "A", "L", "L", "M", "L", "O", "E", "T"],
  ],
};

export const savvyShopperQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-savvy-quiz",
  title: "Savvy Shopper: Quiz",
  topic: "Spending Wisely",
  instruction: "Test your digital shopping safety and e-commerce knowledge.",
  questions: [
    {
      id: 1,
      question: "When you are ready to pay for several items at once on a website, you check your virtual?",
      options: ["Sale", "Cart", "Review", "Delivery"],
      correctIndex: 1,
      explanation: "The shopping cart holds selected items and item quantities before final checkout.",
    },
    {
      id: 2,
      question: "To try and protect your account from hackers on shopping apps, you must create a very strong?",
      options: ["Order", "Discount", "Password", "Receipt"],
      correctIndex: 2,
      explanation: "Strong passwords combining symbols, numbers, and uppercase letters safeguard stored payment details.",
    },
    {
      id: 3,
      question: "If you buy a cool new gadget and it arrives broken, you should immediately contact the seller to ask for a?",
      options: ["Password", "Sale", "Wishlist", "Refund"],
      correctIndex: 3,
      explanation: "Consumer protection policies on platforms like Jumia and Kilimall entitle buyers to a replacement or refund.",
    },
    {
      id: 4,
      question: "When a shop drops its prices during 'Black Friday' or 'Back to School,' it is having a?",
      options: ["Sale", "Receipt", "Password", "Refund"],
      correctIndex: 0,
      explanation: "Sales promotions offer promotional discounts to boost transaction volume.",
    },
    {
      id: 5,
      question: "What do you call the digital or paper proof that shows exactly what you bought and how much you paid?",
      options: ["Order", "Receipt", "Gadget", "Discount"],
      correctIndex: 1,
      explanation: "An e-receipt or printed invoice confirms payment completion and delivery terms.",
    },
  ],
};
