import { WordSearchPuzzle, QuizPuzzle } from "../types";

export const taxesWordSearch1: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-taxes-ws1",
  title: "Taxes: Puzzle 1",
  topic: "Spending Wisely",
  theme: "Kenya Revenue Authority & National Treasury",
  instruction: "Find the 10 taxation, revenue, and public finance terms in the grid.",
  size: 14,
  words: [
    "KRA",
    "Tax",
    "Economy",
    "Import Duty",
    "Revenue",
    "PAYE",
    "Levy",
    "VAT",
    "Development",
    "Treasury",
  ],
  grid: [
    ["R", "A", "M", "T", "N", "T", "E", "R", "D", "R", "K", "P", "X", "U"],
    ["T", "N", "E", "M", "P", "O", "L", "E", "V", "E", "D", "A", "E", "E"],
    ["E", "X", "V", "E", "P", "K", "A", "A", "L", "T", "R", "Y", "Y", "L"],
    ["R", "C", "Y", "P", "T", "M", "T", "O", "A", "U", "O", "E", "T", "E"],
    ["O", "T", "O", "E", "A", "V", "K", "R", "A", "D", "O", "E", "M", "V"],
    ["E", "T", "U", "N", "M", "V", "T", "T", "E", "E", "V", "M", "R", "Y"],
    ["E", "A", "O", "T", "O", "Y", "A", "R", "N", "A", "A", "S", "Y", "T"],
    ["T", "U", "T", "R", "L", "M", "Y", "E", "T", "C", "S", "T", "R", "Y"],
    ["A", "R", "L", "M", "V", "N", "Y", "A", "L", "M", "E", "U", "U", "V"],
    ["K", "Y", "R", "O", "T", "E", "X", "A", "I", "T", "T", "L", "R", "E"],
    ["P", "Y", "T", "U", "D", "T", "R", "O", "P", "M", "I", "E", "T", "Y"],
    ["U", "A", "U", "V", "T", "T", "R", "E", "V", "E", "N", "U", "E", "D"],
    ["M", "T", "U", "E", "D", "K", "E", "E", "E", "N", "A", "R", "A", "P"],
    ["M", "T", "Y", "S", "N", "T", "M", "T", "Y", "P", "Y", "A", "E", "E"],
  ],
};

export const taxesWordSearch2: WordSearchPuzzle = {
  type: "wordsearch",
  id: "sw-taxes-ws2",
  title: "Taxes: Puzzle 2",
  topic: "Spending Wisely",
  theme: "Subsidies, Tariffs & Trade Quotas",
  instruction: "Find the 10 trade policy, quota, and fiscal terms in the grid.",
  size: 14,
  words: [
    "Subsidy",
    "Excise",
    "Tariffs",
    "Debt",
    "Export",
    "Quota",
    "Budgeting",
    "Services",
    "Embargo",
    "Public",
  ],
  grid: [
    ["D", "S", "U", "B", "S", "I", "D", "Y", "X", "B", "I", "X", "I", "I"],
    ["T", "E", "E", "G", "X", "G", "O", "T", "E", "E", "N", "B", "E", "G"],
    ["A", "M", "A", "T", "I", "N", "U", "M", "A", "O", "R", "G", "I", "R"],
    ["R", "B", "T", "B", "I", "I", "X", "I", "Y", "I", "A", "I", "G", "O"],
    ["I", "A", "O", "V", "R", "T", "E", "S", "I", "E", "U", "A", "E", "I"],
    ["F", "R", "U", "I", "G", "E", "R", "E", "D", "X", "S", "I", "E", "E"],
    ["F", "G", "Q", "M", "E", "G", "X", "R", "I", "P", "I", "B", "S", "E"],
    ["S", "O", "E", "I", "E", "D", "B", "E", "S", "O", "B", "U", "R", "T"],
    ["A", "S", "T", "T", "R", "U", "T", "R", "B", "R", "T", "N", "B", "I"],
    ["T", "X", "B", "T", "L", "B", "R", "U", "U", "T", "Q", "P", "S", "B"],
    ["S", "E", "C", "I", "V", "R", "E", "S", "S", "D", "V", "I", "C", "B"],
    ["D", "E", "I", "B", "N", "R", "S", "F", "D", "T", "E", "T", "B", "G"],
    ["E", "B", "R", "F", "B", "E", "P", "U", "B", "L", "I", "C", "E", "C"],
    ["O", "R", "D", "Q", "E", "X", "C", "I", "S", "E", "U", "I", "F", "S"],
  ],
};

export const taxesQuiz: QuizPuzzle = {
  type: "quiz",
  id: "sw-taxes-quiz",
  title: "Taxes: Quiz",
  topic: "Spending Wisely",
  instruction: "Explore KRA revenue collection, PAYE, VAT, and public infrastructure budgets.",
  questions: [
    {
      id: 1,
      question: "Which government body is responsible for collecting all taxes in Kenya?",
      options: ["Central Bank", "KRA (Kenya Revenue Authority)", "The Treasury", "Parliament"],
      correctIndex: 1,
      explanation: "KRA is the state agency mandated to assess, collect, and account for all government revenues.",
    },
    {
      id: 2,
      question: "When Sandra buys a soda or a loaf of bread, she pays a small tax called ___ that is already included in the price.",
      options: ["PAYE", "Excise Duty", "VAT (Value Added Tax)", "Import Duty"],
      correctIndex: 2,
      explanation: "Value Added Tax (16% standard rate) is a consumption tax charged on taxable goods and services.",
    },
    {
      id: 3,
      question: "Adults who are employed have a portion of their monthly salary deducted as tax. This system is known as?",
      options: ["Levy", "Subsidy", "Revenue", "PAYE (Pay As You Earn)"],
      correctIndex: 3,
      explanation: "PAYE is income tax deducted directly at the source by employers from employee salaries.",
    },
    {
      id: 4,
      question: "All the money the government collects from taxes and other sources to pay for schools, roads and hospitals is called?",
      options: ["Revenue", "Debt", "Budgeting", "Profit"],
      correctIndex: 0,
      explanation: "Public revenue funds development infrastructure, national security, education, and universal healthcare.",
    },
    {
      id: 5,
      question: "Which government department is in charge of managing Kenya's national financial policy and preparing the annual budget?",
      options: ["The Police", "The Treasury", "KRA", "The Judiciary"],
      correctIndex: 1,
      explanation: "The National Treasury prepares the national budget and allocates resources across all ministries.",
    },
    {
      id: 6,
      question: "When goods like cars or electronics are brought into Kenya from another country, the tax paid on them is called?",
      options: ["VAT", "Export Tax", "Import Duty", "PAYE"],
      correctIndex: 2,
      explanation: "Customs and import duties are collected at ports of entry on imported commodities.",
    },
    {
      id: 7,
      question: "A tax on specific goods like cigarettes, alcohol, or sweetened juices to discourage their consumption or raise extra funds is called?",
      options: ["Quota", "Tariff", "Subsidy", "Excise Duty"],
      correctIndex: 3,
      explanation: "Excise duty (sin tax) is levied on specific luxury or high-consumption manufactured goods.",
    },
    {
      id: 8,
      question: "When the government borrows money from other countries or banks to build roads and railways, this money is called?",
      options: ["Public Debt", "Development", "Revenue", "Economy"],
      correctIndex: 0,
      explanation: "Public debt consists of external bilateral loans and domestic sovereign treasury bonds.",
    },
    {
      id: 9,
      question: "To help local farmers, the government might pay part of the cost of fertilisers. This financial help is called a?",
      options: ["Levy", "Subsidy", "Tariff", "Quota"],
      correctIndex: 1,
      explanation: "Agricultural subsidies lower producer costs to ensure food security and affordable staple prices.",
    },
    {
      id: 10,
      question: "If the government wants to protect local industries, it might put a limit on the amount of a certain product like rice that can be imported. This limit is a?",
      options: ["Embargo", "VAT", "Quota", "Tariff"],
      correctIndex: 2,
      explanation: "Import quotas set physical volume limits to shield domestic producers from foreign competition.",
    },
  ],
};
